// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DriverData Information about the storage driver used to store the container's and
 * image's filesystem.
 * 
 * swagger:model DriverData
 */
export class DriverData {
    /**
     * Low-level storage metadata, provided as key/value pairs.
     * 
     * This information is driver-specific, and depends on the storage-driver
     * in use, and should be used for informational purposes only.
     * 
     * Example: {"MergedDir":"/var/lib/docker/overlay2/ef749362d13333e65fc95c572eb525abbe0052e16e086cb64bc3b98ae9aa6d74/merged","UpperDir":"/var/lib/docker/overlay2/ef749362d13333e65fc95c572eb525abbe0052e16e086cb64bc3b98ae9aa6d74/diff","WorkDir":"/var/lib/docker/overlay2/ef749362d13333e65fc95c572eb525abbe0052e16e086cb64bc3b98ae9aa6d74/work"}
     * Required: true
     */
    "Data": { [_: string]: string };

    /**
     * Name of the storage driver.
     * Example: overlay2
     * Required: true
     */
    "Name": string;

    /** Creates a new DriverData instance. */
    constructor($$source: Partial<DriverData> = {}) {
        if (!("Data" in $$source)) {
            this["Data"] = {};
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DriverData instance from a string or object.
     */
    static createFrom($$source: any = {}): DriverData {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Data" in $$parsedSource) {
            $$parsedSource["Data"] = $$createField0_0($$parsedSource["Data"]);
        }
        return new DriverData($$parsedSource as Partial<DriverData>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
