// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as os$0 from "../../../../../../os/models.js";

/**
 * BindOptions defines options specific to mounts of type "bind".
 */
export class BindOptions {
    "Propagation"?: Propagation;
    "NonRecursive"?: boolean;
    "CreateMountpoint"?: boolean;

    /**
     * ReadOnlyNonRecursive makes the mount non-recursively read-only, but still leaves the mount recursive
     * (unless NonRecursive is set to true in conjunction).
     */
    "ReadOnlyNonRecursive"?: boolean;

    /**
     * ReadOnlyForceRecursive raises an error if the mount cannot be made recursively read-only.
     */
    "ReadOnlyForceRecursive"?: boolean;

    /** Creates a new BindOptions instance. */
    constructor($$source: Partial<BindOptions> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BindOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): BindOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BindOptions($$parsedSource as Partial<BindOptions>);
    }
}

/**
 * ClusterOptions specifies options for a Cluster volume.
 */
export class ClusterOptions {

    /** Creates a new ClusterOptions instance. */
    constructor($$source: Partial<ClusterOptions> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClusterOptions($$parsedSource as Partial<ClusterOptions>);
    }
}

/**
 * Consistency represents the consistency requirements of a mount.
 */
export enum Consistency {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ConsistencyFull guarantees bind mount-like consistency
     */
    ConsistencyFull = "consistent",

    /**
     * ConsistencyCached mounts can cache read data and FS structure
     */
    ConsistencyCached = "cached",

    /**
     * ConsistencyDelegated mounts can cache read and written data and structure
     */
    ConsistencyDelegated = "delegated",

    /**
     * ConsistencyDefault provides "consistent" behavior unless overridden
     */
    ConsistencyDefault = "default",
};

/**
 * Driver represents a volume driver.
 */
export class Driver {
    "Name"?: string;
    "Options"?: { [_: string]: string };

    /** Creates a new Driver instance. */
    constructor($$source: Partial<Driver> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Driver instance from a string or object.
     */
    static createFrom($$source: any = {}): Driver {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Options" in $$parsedSource) {
            $$parsedSource["Options"] = $$createField1_0($$parsedSource["Options"]);
        }
        return new Driver($$parsedSource as Partial<Driver>);
    }
}

export class ImageOptions {
    "Subpath"?: string;

    /** Creates a new ImageOptions instance. */
    constructor($$source: Partial<ImageOptions> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImageOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): ImageOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImageOptions($$parsedSource as Partial<ImageOptions>);
    }
}

/**
 * Mount represents a mount (volume).
 */
export class Mount {
    "Type"?: Type;

    /**
     * Source specifies the name of the mount. Depending on mount type, this
     * may be a volume name or a host path, or even ignored.
     * Source is not supported for tmpfs (must be an empty value)
     */
    "Source"?: string;
    "Target"?: string;

    /**
     * attempts recursive read-only if possible
     */
    "ReadOnly"?: boolean;
    "Consistency"?: Consistency;
    "BindOptions"?: BindOptions | null;
    "VolumeOptions"?: VolumeOptions | null;
    "ImageOptions"?: ImageOptions | null;
    "TmpfsOptions"?: TmpfsOptions | null;
    "ClusterOptions"?: ClusterOptions | null;

    /** Creates a new Mount instance. */
    constructor($$source: Partial<Mount> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Mount instance from a string or object.
     */
    static createFrom($$source: any = {}): Mount {
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType4;
        const $$createField7_0 = $$createType6;
        const $$createField8_0 = $$createType8;
        const $$createField9_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("BindOptions" in $$parsedSource) {
            $$parsedSource["BindOptions"] = $$createField5_0($$parsedSource["BindOptions"]);
        }
        if ("VolumeOptions" in $$parsedSource) {
            $$parsedSource["VolumeOptions"] = $$createField6_0($$parsedSource["VolumeOptions"]);
        }
        if ("ImageOptions" in $$parsedSource) {
            $$parsedSource["ImageOptions"] = $$createField7_0($$parsedSource["ImageOptions"]);
        }
        if ("TmpfsOptions" in $$parsedSource) {
            $$parsedSource["TmpfsOptions"] = $$createField8_0($$parsedSource["TmpfsOptions"]);
        }
        if ("ClusterOptions" in $$parsedSource) {
            $$parsedSource["ClusterOptions"] = $$createField9_0($$parsedSource["ClusterOptions"]);
        }
        return new Mount($$parsedSource as Partial<Mount>);
    }
}

/**
 * Propagation represents the propagation of a mount.
 */
export enum Propagation {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * PropagationRPrivate RPRIVATE
     */
    PropagationRPrivate = "rprivate",

    /**
     * PropagationPrivate PRIVATE
     */
    PropagationPrivate = "private",

    /**
     * PropagationRShared RSHARED
     */
    PropagationRShared = "rshared",

    /**
     * PropagationShared SHARED
     */
    PropagationShared = "shared",

    /**
     * PropagationRSlave RSLAVE
     */
    PropagationRSlave = "rslave",

    /**
     * PropagationSlave SLAVE
     */
    PropagationSlave = "slave",
};

/**
 * TmpfsOptions defines options specific to mounts of type "tmpfs".
 */
export class TmpfsOptions {
    /**
     * Size sets the size of the tmpfs, in bytes.
     * 
     * This will be converted to an operating system specific value
     * depending on the host. For example, on linux, it will be converted to
     * use a 'k', 'm' or 'g' syntax. BSD, though not widely supported with
     * docker, uses a straight byte value.
     * 
     * Percentages are not supported.
     */
    "SizeBytes"?: number;

    /**
     * Mode of the tmpfs upon creation
     */
    "Mode"?: os$0.FileMode;

    /**
     * Options to be passed to the tmpfs mount. An array of arrays. Flag
     * options should be provided as 1-length arrays. Other types should be
     * provided as 2-length arrays, where the first item is the key and the
     * second the value.
     */
    "Options"?: string[][];

    /** Creates a new TmpfsOptions instance. */
    constructor($$source: Partial<TmpfsOptions> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TmpfsOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): TmpfsOptions {
        const $$createField2_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Options" in $$parsedSource) {
            $$parsedSource["Options"] = $$createField2_0($$parsedSource["Options"]);
        }
        return new TmpfsOptions($$parsedSource as Partial<TmpfsOptions>);
    }
}

/**
 * Type represents the type of a mount.
 */
export enum Type {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Type constants
     *
     * TypeBind is the type for mounting host dir
     */
    TypeBind = "bind",

    /**
     * TypeVolume is the type for remote storage volumes
     */
    TypeVolume = "volume",

    /**
     * TypeTmpfs is the type for mounting tmpfs
     */
    TypeTmpfs = "tmpfs",

    /**
     * TypeNamedPipe is the type for mounting Windows named pipes
     */
    TypeNamedPipe = "npipe",

    /**
     * TypeCluster is the type for Swarm Cluster Volumes.
     */
    TypeCluster = "cluster",

    /**
     * TypeImage is the type for mounting another image's filesystem
     */
    TypeImage = "image",
};

/**
 * VolumeOptions represents the options for a mount of type volume.
 */
export class VolumeOptions {
    "NoCopy"?: boolean;
    "Labels"?: { [_: string]: string };
    "Subpath"?: string;
    "DriverConfig"?: Driver | null;

    /** Creates a new VolumeOptions instance. */
    constructor($$source: Partial<VolumeOptions> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VolumeOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): VolumeOptions {
        const $$createField1_0 = $$createType0;
        const $$createField3_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Labels" in $$parsedSource) {
            $$parsedSource["Labels"] = $$createField1_0($$parsedSource["Labels"]);
        }
        if ("DriverConfig" in $$parsedSource) {
            $$parsedSource["DriverConfig"] = $$createField3_0($$parsedSource["DriverConfig"]);
        }
        return new VolumeOptions($$parsedSource as Partial<VolumeOptions>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = BindOptions.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = VolumeOptions.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = ImageOptions.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = TmpfsOptions.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = ClusterOptions.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $Create.Array($Create.Any);
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = Driver.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
