// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Propagation represents the propagation of a mount.
 */
export enum Propagation {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * PropagationRPrivate RPRIVATE
     */
    PropagationRPrivate = "rprivate",

    /**
     * PropagationPrivate PRIVATE
     */
    PropagationPrivate = "private",

    /**
     * PropagationRShared RSHARED
     */
    PropagationRShared = "rshared",

    /**
     * PropagationShared SHARED
     */
    PropagationShared = "shared",

    /**
     * PropagationRSlave RSLAVE
     */
    PropagationRSlave = "rslave",

    /**
     * PropagationSlave SLAVE
     */
    PropagationSlave = "slave",
};

/**
 * Type represents the type of a mount.
 */
export enum Type {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Type constants
     *
     * TypeBind is the type for mounting host dir
     */
    TypeBind = "bind",

    /**
     * TypeVolume is the type for remote storage volumes
     */
    TypeVolume = "volume",

    /**
     * TypeTmpfs is the type for mounting tmpfs
     */
    TypeTmpfs = "tmpfs",

    /**
     * TypeNamedPipe is the type for mounting Windows named pipes
     */
    TypeNamedPipe = "npipe",

    /**
     * TypeCluster is the type for Swarm Cluster Volumes.
     */
    TypeCluster = "cluster",

    /**
     * TypeImage is the type for mounting another image's filesystem
     */
    TypeImage = "image",
};
