// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as swarm$0 from "../swarm/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

/**
 * AccessMode defines the access mode of a volume.
 */
export class AccessMode {
    /**
     * Scope defines the set of nodes this volume can be used on at one time.
     */
    "Scope"?: Scope;

    /**
     * Sharing defines the number and way that different tasks can use this
     * volume at one time.
     */
    "Sharing"?: SharingMode;

    /**
     * MountVolume defines options for using this volume as a Mount-type
     * volume.
     * 
     * Either BlockVolume or MountVolume, but not both, must be present.
     */
    "MountVolume"?: TypeMount | null;

    /**
     * BlockVolume defines options for using this volume as a Block-type
     * volume.
     * 
     * Either BlockVolume or MountVolume, but not both, must be present.
     */
    "BlockVolume"?: TypeBlock | null;

    /** Creates a new AccessMode instance. */
    constructor($$source: Partial<AccessMode> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccessMode instance from a string or object.
     */
    static createFrom($$source: any = {}): AccessMode {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("MountVolume" in $$parsedSource) {
            $$parsedSource["MountVolume"] = $$createField2_0($$parsedSource["MountVolume"]);
        }
        if ("BlockVolume" in $$parsedSource) {
            $$parsedSource["BlockVolume"] = $$createField3_0($$parsedSource["BlockVolume"]);
        }
        return new AccessMode($$parsedSource as Partial<AccessMode>);
    }
}

/**
 * Availability specifies the availability of the volume.
 */
export enum Availability {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * AvailabilityActive indicates that the volume is active and fully
     * schedulable on the cluster.
     */
    AvailabilityActive = "active",

    /**
     * AvailabilityPause indicates that no new workloads should use the
     * volume, but existing workloads can continue to use it.
     */
    AvailabilityPause = "pause",

    /**
     * AvailabilityDrain indicates that all workloads using this volume
     * should be rescheduled, and the volume unpublished from all nodes.
     */
    AvailabilityDrain = "drain",
};

/**
 * CapacityRange describes the minimum and maximum capacity a volume should be
 * created with
 */
export class CapacityRange {
    /**
     * RequiredBytes specifies that a volume must be at least this big. The
     * value of 0 indicates an unspecified minimum.
     */
    "RequiredBytes": number;

    /**
     * LimitBytes specifies that a volume must not be bigger than this. The
     * value of 0 indicates an unspecified maximum
     */
    "LimitBytes": number;

    /** Creates a new CapacityRange instance. */
    constructor($$source: Partial<CapacityRange> = {}) {
        if (!("RequiredBytes" in $$source)) {
            this["RequiredBytes"] = 0;
        }
        if (!("LimitBytes" in $$source)) {
            this["LimitBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CapacityRange instance from a string or object.
     */
    static createFrom($$source: any = {}): CapacityRange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CapacityRange($$parsedSource as Partial<CapacityRange>);
    }
}

/**
 * ClusterVolume contains options and information specific to, and only present
 * on, Swarm CSI cluster volumes.
 */
export class ClusterVolume {
    /**
     * ID is the Swarm ID of the volume. Because cluster volumes are Swarm
     * objects, they have an ID, unlike non-cluster volumes, which only have a
     * Name. This ID can be used to refer to the cluster volume.
     */
    "ID": string;
    "Version"?: swarm$0.Version;
    "CreatedAt"?: time$0.Time;
    "UpdatedAt"?: time$0.Time;

    /**
     * Spec is the cluster-specific options from which this volume is derived.
     */
    "Spec": ClusterVolumeSpec;

    /**
     * PublishStatus contains the status of the volume as it pertains to its
     * publishing on Nodes.
     */
    "PublishStatus"?: (PublishStatus | null)[];

    /**
     * Info is information about the global status of the volume.
     */
    "Info"?: Info | null;

    /** Creates a new ClusterVolume instance. */
    constructor($$source: Partial<ClusterVolume> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Spec" in $$source)) {
            this["Spec"] = (new ClusterVolumeSpec());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterVolume instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterVolume {
        const $$createField1_0 = $$createType4;
        const $$createField4_0 = $$createType5;
        const $$createField5_0 = $$createType8;
        const $$createField6_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Version" in $$parsedSource) {
            $$parsedSource["Version"] = $$createField1_0($$parsedSource["Version"]);
        }
        if ("Spec" in $$parsedSource) {
            $$parsedSource["Spec"] = $$createField4_0($$parsedSource["Spec"]);
        }
        if ("PublishStatus" in $$parsedSource) {
            $$parsedSource["PublishStatus"] = $$createField5_0($$parsedSource["PublishStatus"]);
        }
        if ("Info" in $$parsedSource) {
            $$parsedSource["Info"] = $$createField6_0($$parsedSource["Info"]);
        }
        return new ClusterVolume($$parsedSource as Partial<ClusterVolume>);
    }
}

/**
 * ClusterVolumeSpec contains the spec used to create this volume.
 */
export class ClusterVolumeSpec {
    /**
     * Group defines the volume group of this volume. Volumes belonging to the
     * same group can be referred to by group name when creating Services.
     * Referring to a volume by group instructs swarm to treat volumes in that
     * group interchangeably for the purpose of scheduling. Volumes with an
     * empty string for a group technically all belong to the same, emptystring
     * group.
     */
    "Group"?: string;

    /**
     * AccessMode defines how the volume is used by tasks.
     */
    "AccessMode"?: AccessMode | null;

    /**
     * AccessibilityRequirements specifies where in the cluster a volume must
     * be accessible from.
     * 
     * This field must be empty if the plugin does not support
     * VOLUME_ACCESSIBILITY_CONSTRAINTS capabilities. If it is present but the
     * plugin does not support it, volume will not be created.
     * 
     * If AccessibilityRequirements is empty, but the plugin does support
     * VOLUME_ACCESSIBILITY_CONSTRAINTS, then Swarmkit will assume the entire
     * cluster is a valid target for the volume.
     */
    "AccessibilityRequirements"?: TopologyRequirement | null;

    /**
     * CapacityRange defines the desired capacity that the volume should be
     * created with. If nil, the plugin will decide the capacity.
     */
    "CapacityRange"?: CapacityRange | null;

    /**
     * Secrets defines Swarm Secrets that are passed to the CSI storage plugin
     * when operating on this volume.
     */
    "Secrets"?: Secret[];

    /**
     * Availability is the Volume's desired availability. Analogous to Node
     * Availability, this allows the user to take volumes offline in order to
     * update or delete them.
     */
    "Availability"?: Availability;

    /** Creates a new ClusterVolumeSpec instance. */
    constructor($$source: Partial<ClusterVolumeSpec> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterVolumeSpec instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterVolumeSpec {
        const $$createField1_0 = $$createType12;
        const $$createField2_0 = $$createType14;
        const $$createField3_0 = $$createType16;
        const $$createField4_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("AccessMode" in $$parsedSource) {
            $$parsedSource["AccessMode"] = $$createField1_0($$parsedSource["AccessMode"]);
        }
        if ("AccessibilityRequirements" in $$parsedSource) {
            $$parsedSource["AccessibilityRequirements"] = $$createField2_0($$parsedSource["AccessibilityRequirements"]);
        }
        if ("CapacityRange" in $$parsedSource) {
            $$parsedSource["CapacityRange"] = $$createField3_0($$parsedSource["CapacityRange"]);
        }
        if ("Secrets" in $$parsedSource) {
            $$parsedSource["Secrets"] = $$createField4_0($$parsedSource["Secrets"]);
        }
        return new ClusterVolumeSpec($$parsedSource as Partial<ClusterVolumeSpec>);
    }
}

/**
 * Info contains information about the Volume as a whole as provided by
 * the CSI storage plugin.
 */
export class Info {
    /**
     * CapacityBytes is the capacity of the volume in bytes. A value of 0
     * indicates that the capacity is unknown.
     */
    "CapacityBytes"?: number;

    /**
     * VolumeContext is the context originating from the CSI storage plugin
     * when the Volume is created.
     */
    "VolumeContext"?: { [_: string]: string };

    /**
     * VolumeID is the ID of the Volume as seen by the CSI storage plugin. This
     * is distinct from the Volume's Swarm ID, which is the ID used by all of
     * the Docker Engine to refer to the Volume. If this field is blank, then
     * the Volume has not been successfully created yet.
     */
    "VolumeID"?: string;

    /**
     * AccessibleTopology is the topology this volume is actually accessible
     * from.
     */
    "AccessibleTopology"?: Topology[];

    /** Creates a new Info instance. */
    constructor($$source: Partial<Info> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     */
    static createFrom($$source: any = {}): Info {
        const $$createField1_0 = $$createType19;
        const $$createField3_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("VolumeContext" in $$parsedSource) {
            $$parsedSource["VolumeContext"] = $$createField1_0($$parsedSource["VolumeContext"]);
        }
        if ("AccessibleTopology" in $$parsedSource) {
            $$parsedSource["AccessibleTopology"] = $$createField3_0($$parsedSource["AccessibleTopology"]);
        }
        return new Info($$parsedSource as Partial<Info>);
    }
}

/**
 * PublishState represents the state of a Volume as it pertains to its
 * use on a particular Node.
 */
export enum PublishState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * StatePending indicates that the volume should be published on
     * this node, but the call to ControllerPublishVolume has not been
     * successfully completed yet and the result recorded by swarmkit.
     */
    StatePending = "pending-publish",

    /**
     * StatePublished means the volume is published successfully to the node.
     */
    StatePublished = "published",

    /**
     * StatePendingNodeUnpublish indicates that the Volume should be
     * unpublished on the Node, and we're waiting for confirmation that it has
     * done so.  After the Node has confirmed that the Volume has been
     * unpublished, the state will move to StatePendingUnpublish.
     */
    StatePendingNodeUnpublish = "pending-node-unpublish",

    /**
     * StatePendingUnpublish means the volume is still published to the node
     * by the controller, awaiting the operation to unpublish it.
     */
    StatePendingUnpublish = "pending-controller-unpublish",
};

/**
 * PublishStatus represents the status of the volume as published to an
 * individual node
 */
export class PublishStatus {
    /**
     * NodeID is the ID of the swarm node this Volume is published to.
     */
    "NodeID"?: string;

    /**
     * State is the publish state of the volume.
     */
    "State"?: PublishState;

    /**
     * PublishContext is the PublishContext returned by the CSI plugin when
     * a volume is published.
     */
    "PublishContext"?: { [_: string]: string };

    /** Creates a new PublishStatus instance. */
    constructor($$source: Partial<PublishStatus> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublishStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): PublishStatus {
        const $$createField2_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("PublishContext" in $$parsedSource) {
            $$parsedSource["PublishContext"] = $$createField2_0($$parsedSource["PublishContext"]);
        }
        return new PublishStatus($$parsedSource as Partial<PublishStatus>);
    }
}

/**
 * Scope defines the Scope of a Cluster Volume. This is how many nodes a
 * Volume can be accessed simultaneously on.
 */
export enum Scope {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ScopeSingleNode indicates the volume can be used on one node at a
     * time.
     */
    ScopeSingleNode = "single",

    /**
     * ScopeMultiNode indicates the volume can be used on many nodes at
     * the same time.
     */
    ScopeMultiNode = "multi",
};

/**
 * Secret represents a Swarm Secret value that must be passed to the CSI
 * storage plugin when operating on this Volume. It represents one key-value
 * pair of possibly many.
 */
export class Secret {
    /**
     * Key is the name of the key of the key-value pair passed to the plugin.
     */
    "Key": string;

    /**
     * Secret is the swarm Secret object from which to read data. This can be a
     * Secret name or ID. The Secret data is retrieved by Swarm and used as the
     * value of the key-value pair passed to the plugin.
     */
    "Secret": string;

    /** Creates a new Secret instance. */
    constructor($$source: Partial<Secret> = {}) {
        if (!("Key" in $$source)) {
            this["Key"] = "";
        }
        if (!("Secret" in $$source)) {
            this["Secret"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Secret instance from a string or object.
     */
    static createFrom($$source: any = {}): Secret {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Secret($$parsedSource as Partial<Secret>);
    }
}

/**
 * SharingMode defines the Sharing of a Cluster Volume. This is how Tasks using a
 * Volume at the same time can use it.
 */
export enum SharingMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * SharingNone indicates that only one Task may use the Volume at a
     * time.
     */
    SharingNone = "none",

    /**
     * SharingReadOnly indicates that the Volume may be shared by any
     * number of Tasks, but they must be read-only.
     */
    SharingReadOnly = "readonly",

    /**
     * SharingOneWriter indicates that the Volume may be shared by any
     * number of Tasks, but all after the first must be read-only.
     */
    SharingOneWriter = "onewriter",

    /**
     * SharingAll means that the Volume may be shared by any number of
     * Tasks, as readers or writers.
     */
    SharingAll = "all",
};

/**
 * Topology is a map of topological domains to topological segments.
 * 
 * This description is taken verbatim from the CSI Spec:
 * 
 * A topological domain is a sub-division of a cluster, like "region",
 * "zone", "rack", etc.
 * A topological segment is a specific instance of a topological domain,
 * like "zone3", "rack3", etc.
 * For example {"com.company/zone": "Z1", "com.company/rack": "R3"}
 * Valid keys have two segments: an OPTIONAL prefix and name, separated
 * by a slash (/), for example: "com.company.example/zone".
 * The key name segment is REQUIRED. The prefix is OPTIONAL.
 * The key name MUST be 63 characters or less, begin and end with an
 * alphanumeric character ([a-z0-9A-Z]), and contain only dashes (-),
 * underscores (_), dots (.), or alphanumerics in between, for example
 * "zone".
 * The key prefix MUST be 63 characters or less, begin and end with a
 * lower-case alphanumeric character ([a-z0-9]), contain only
 * dashes (-), dots (.), or lower-case alphanumerics in between, and
 * follow domain name notation format
 * (https://tools.ietf.org/html/rfc1035#section-2.3.1).
 * The key prefix SHOULD include the plugin's host company name and/or
 * the plugin name, to minimize the possibility of collisions with keys
 * from other plugins.
 * If a key prefix is specified, it MUST be identical across all
 * topology keys returned by the SP (across all RPCs).
 * Keys MUST be case-insensitive. Meaning the keys "Zone" and "zone"
 * MUST not both exist.
 * Each value (topological segment) MUST contain 1 or more strings.
 * Each string MUST be 63 characters or less and begin and end with an
 * alphanumeric character with '-', '_', '.', or alphanumerics in
 * between.
 */
export class Topology {
    "Segments"?: { [_: string]: string };

    /** Creates a new Topology instance. */
    constructor($$source: Partial<Topology> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Topology instance from a string or object.
     */
    static createFrom($$source: any = {}): Topology {
        const $$createField0_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Segments" in $$parsedSource) {
            $$parsedSource["Segments"] = $$createField0_0($$parsedSource["Segments"]);
        }
        return new Topology($$parsedSource as Partial<Topology>);
    }
}

/**
 * TopologyRequirement expresses the user's requirements for a volume's
 * accessible topology.
 */
export class TopologyRequirement {
    /**
     * Requisite specifies a list of Topologies, at least one of which the
     * volume must be accessible from.
     * 
     * Taken verbatim from the CSI Spec:
     * 
     * Specifies the list of topologies the provisioned volume MUST be
     * accessible from.
     * This field is OPTIONAL. If TopologyRequirement is specified either
     * requisite or preferred or both MUST be specified.
     * 
     * If requisite is specified, the provisioned volume MUST be
     * accessible from at least one of the requisite topologies.
     * 
     * Given
     *   x = number of topologies provisioned volume is accessible from
     *   n = number of requisite topologies
     * The CO MUST ensure n >= 1. The SP MUST ensure x >= 1
     * If x==n, then the SP MUST make the provisioned volume available to
     * all topologies from the list of requisite topologies. If it is
     * unable to do so, the SP MUST fail the CreateVolume call.
     * For example, if a volume should be accessible from a single zone,
     * and requisite =
     *   {"region": "R1", "zone": "Z2"}
     * then the provisioned volume MUST be accessible from the "region"
     * "R1" and the "zone" "Z2".
     * Similarly, if a volume should be accessible from two zones, and
     * requisite =
     *   {"region": "R1", "zone": "Z2"},
     *   {"region": "R1", "zone": "Z3"}
     * then the provisioned volume MUST be accessible from the "region"
     * "R1" and both "zone" "Z2" and "zone" "Z3".
     * 
     * If x<n, then the SP SHALL choose x unique topologies from the list
     * of requisite topologies. If it is unable to do so, the SP MUST fail
     * the CreateVolume call.
     * For example, if a volume should be accessible from a single zone,
     * and requisite =
     *   {"region": "R1", "zone": "Z2"},
     *   {"region": "R1", "zone": "Z3"}
     * then the SP may choose to make the provisioned volume available in
     * either the "zone" "Z2" or the "zone" "Z3" in the "region" "R1".
     * Similarly, if a volume should be accessible from two zones, and
     * requisite =
     *   {"region": "R1", "zone": "Z2"},
     *   {"region": "R1", "zone": "Z3"},
     *   {"region": "R1", "zone": "Z4"}
     * then the provisioned volume MUST be accessible from any combination
     * of two unique topologies: e.g. "R1/Z2" and "R1/Z3", or "R1/Z2" and
     *  "R1/Z4", or "R1/Z3" and "R1/Z4".
     * 
     * If x>n, then the SP MUST make the provisioned volume available from
     * all topologies from the list of requisite topologies and MAY choose
     * the remaining x-n unique topologies from the list of all possible
     * topologies. If it is unable to do so, the SP MUST fail the
     * CreateVolume call.
     * For example, if a volume should be accessible from two zones, and
     * requisite =
     *   {"region": "R1", "zone": "Z2"}
     * then the provisioned volume MUST be accessible from the "region"
     * "R1" and the "zone" "Z2" and the SP may select the second zone
     * independently, e.g. "R1/Z4".
     */
    "Requisite"?: Topology[];

    /**
     * Preferred is a list of Topologies that the volume should attempt to be
     * provisioned in.
     * 
     * Taken from the CSI spec:
     * 
     * Specifies the list of topologies the CO would prefer the volume to
     * be provisioned in.
     * 
     * This field is OPTIONAL. If TopologyRequirement is specified either
     * requisite or preferred or both MUST be specified.
     * 
     * An SP MUST attempt to make the provisioned volume available using
     * the preferred topologies in order from first to last.
     * 
     * If requisite is specified, all topologies in preferred list MUST
     * also be present in the list of requisite topologies.
     * 
     * If the SP is unable to make the provisioned volume available
     * from any of the preferred topologies, the SP MAY choose a topology
     * from the list of requisite topologies.
     * If the list of requisite topologies is not specified, then the SP
     * MAY choose from the list of all possible topologies.
     * If the list of requisite topologies is specified and the SP is
     * unable to make the provisioned volume available from any of the
     * requisite topologies it MUST fail the CreateVolume call.
     * 
     * Example 1:
     * Given a volume should be accessible from a single zone, and
     * requisite =
     *   {"region": "R1", "zone": "Z2"},
     *   {"region": "R1", "zone": "Z3"}
     * preferred =
     *   {"region": "R1", "zone": "Z3"}
     * then the SP SHOULD first attempt to make the provisioned volume
     * available from "zone" "Z3" in the "region" "R1" and fall back to
     * "zone" "Z2" in the "region" "R1" if that is not possible.
     * 
     * Example 2:
     * Given a volume should be accessible from a single zone, and
     * requisite =
     *   {"region": "R1", "zone": "Z2"},
     *   {"region": "R1", "zone": "Z3"},
     *   {"region": "R1", "zone": "Z4"},
     *   {"region": "R1", "zone": "Z5"}
     * preferred =
     *   {"region": "R1", "zone": "Z4"},
     *   {"region": "R1", "zone": "Z2"}
     * then the SP SHOULD first attempt to make the provisioned volume
     * accessible from "zone" "Z4" in the "region" "R1" and fall back to
     * "zone" "Z2" in the "region" "R1" if that is not possible. If that
     * is not possible, the SP may choose between either the "zone"
     * "Z3" or "Z5" in the "region" "R1".
     * 
     * Example 3:
     * Given a volume should be accessible from TWO zones (because an
     * opaque parameter in CreateVolumeRequest, for example, specifies
     * the volume is accessible from two zones, aka synchronously
     * replicated), and
     * requisite =
     *   {"region": "R1", "zone": "Z2"},
     *   {"region": "R1", "zone": "Z3"},
     *   {"region": "R1", "zone": "Z4"},
     *   {"region": "R1", "zone": "Z5"}
     * preferred =
     *   {"region": "R1", "zone": "Z5"},
     *   {"region": "R1", "zone": "Z3"}
     * then the SP SHOULD first attempt to make the provisioned volume
     * accessible from the combination of the two "zones" "Z5" and "Z3" in
     * the "region" "R1". If that's not possible, it should fall back to
     * a combination of "Z5" and other possibilities from the list of
     * requisite. If that's not possible, it should fall back  to a
     * combination of "Z3" and other possibilities from the list of
     * requisite. If that's not possible, it should fall back  to a
     * combination of other possibilities from the list of requisite.
     */
    "Preferred"?: Topology[];

    /** Creates a new TopologyRequirement instance. */
    constructor($$source: Partial<TopologyRequirement> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopologyRequirement instance from a string or object.
     */
    static createFrom($$source: any = {}): TopologyRequirement {
        const $$createField0_0 = $$createType21;
        const $$createField1_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Requisite" in $$parsedSource) {
            $$parsedSource["Requisite"] = $$createField0_0($$parsedSource["Requisite"]);
        }
        if ("Preferred" in $$parsedSource) {
            $$parsedSource["Preferred"] = $$createField1_0($$parsedSource["Preferred"]);
        }
        return new TopologyRequirement($$parsedSource as Partial<TopologyRequirement>);
    }
}

/**
 * TypeBlock defines options for using a volume as a block-type volume.
 * 
 * Intentionally empty.
 */
export class TypeBlock {

    /** Creates a new TypeBlock instance. */
    constructor($$source: Partial<TypeBlock> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TypeBlock instance from a string or object.
     */
    static createFrom($$source: any = {}): TypeBlock {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TypeBlock($$parsedSource as Partial<TypeBlock>);
    }
}

/**
 * TypeMount contains options for using a volume as a Mount-type
 * volume.
 */
export class TypeMount {
    /**
     * FsType specifies the filesystem type for the mount volume. Optional.
     */
    "FsType"?: string;

    /**
     * MountFlags defines flags to pass when mounting the volume. Optional.
     */
    "MountFlags"?: string[];

    /** Creates a new TypeMount instance. */
    constructor($$source: Partial<TypeMount> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TypeMount instance from a string or object.
     */
    static createFrom($$source: any = {}): TypeMount {
        const $$createField1_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("MountFlags" in $$parsedSource) {
            $$parsedSource["MountFlags"] = $$createField1_0($$parsedSource["MountFlags"]);
        }
        return new TypeMount($$parsedSource as Partial<TypeMount>);
    }
}

/**
 * UsageData Usage details about the volume. This information is used by the
 * `GET /system/df` endpoint, and omitted in other endpoints.
 * 
 * swagger:model UsageData
 */
export class UsageData {
    /**
     * The number of containers referencing this volume. This field
     * is set to `-1` if the reference-count is not available.
     * 
     * Required: true
     */
    "RefCount": number;

    /**
     * Amount of disk space used by the volume (in bytes). This information
     * is only available for volumes created with the `"local"` volume
     * driver. For volumes created with other volume drivers, this field
     * is set to `-1` ("not available")
     * 
     * Required: true
     */
    "Size": number;

    /** Creates a new UsageData instance. */
    constructor($$source: Partial<UsageData> = {}) {
        if (!("RefCount" in $$source)) {
            this["RefCount"] = 0;
        }
        if (!("Size" in $$source)) {
            this["Size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageData instance from a string or object.
     */
    static createFrom($$source: any = {}): UsageData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UsageData($$parsedSource as Partial<UsageData>);
    }
}

/**
 * Volume volume
 * 
 * swagger:model Volume
 */
export class Volume {
    /**
     * cluster volume
     */
    "ClusterVolume"?: ClusterVolume | null;

    /**
     * Date/Time the volume was created.
     * Example: 2016-06-07T20:31:11.853781916Z
     */
    "CreatedAt"?: string;

    /**
     * Name of the volume driver used by the volume.
     * Example: custom
     * Required: true
     */
    "Driver": string;

    /**
     * User-defined key/value metadata.
     * Example: {"com.example.some-label":"some-value","com.example.some-other-label":"some-other-value"}
     * Required: true
     */
    "Labels": { [_: string]: string };

    /**
     * Mount path of the volume on the host.
     * Example: /var/lib/docker/volumes/tardis
     * Required: true
     */
    "Mountpoint": string;

    /**
     * Name of the volume.
     * Example: tardis
     * Required: true
     */
    "Name": string;

    /**
     * The driver specific options used when creating the volume.
     * 
     * Example: {"device":"tmpfs","o":"size=100m,uid=1000","type":"tmpfs"}
     * Required: true
     */
    "Options": { [_: string]: string };

    /**
     * The level at which the volume exists. Either `global` for cluster-wide,
     * or `local` for machine level.
     * 
     * Example: local
     * Required: true
     * Enum: ["local","global"]
     */
    "Scope": string;

    /**
     * Low-level details about the volume, provided by the volume driver.
     * Details are returned as a map with key/value pairs:
     * `{"key":"value","key2":"value2"}`.
     * 
     * The `Status` field is optional, and is omitted if the volume driver
     * does not support this feature.
     * 
     * Example: {"hello":"world"}
     */
    "Status"?: { [_: string]: any };

    /**
     * usage data
     */
    "UsageData"?: UsageData | null;

    /** Creates a new Volume instance. */
    constructor($$source: Partial<Volume> = {}) {
        if (!("Driver" in $$source)) {
            this["Driver"] = "";
        }
        if (!("Labels" in $$source)) {
            this["Labels"] = {};
        }
        if (!("Mountpoint" in $$source)) {
            this["Mountpoint"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Options" in $$source)) {
            this["Options"] = {};
        }
        if (!("Scope" in $$source)) {
            this["Scope"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Volume instance from a string or object.
     */
    static createFrom($$source: any = {}): Volume {
        const $$createField0_0 = $$createType24;
        const $$createField3_0 = $$createType19;
        const $$createField6_0 = $$createType19;
        const $$createField8_0 = $$createType25;
        const $$createField9_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ClusterVolume" in $$parsedSource) {
            $$parsedSource["ClusterVolume"] = $$createField0_0($$parsedSource["ClusterVolume"]);
        }
        if ("Labels" in $$parsedSource) {
            $$parsedSource["Labels"] = $$createField3_0($$parsedSource["Labels"]);
        }
        if ("Options" in $$parsedSource) {
            $$parsedSource["Options"] = $$createField6_0($$parsedSource["Options"]);
        }
        if ("Status" in $$parsedSource) {
            $$parsedSource["Status"] = $$createField8_0($$parsedSource["Status"]);
        }
        if ("UsageData" in $$parsedSource) {
            $$parsedSource["UsageData"] = $$createField9_0($$parsedSource["UsageData"]);
        }
        return new Volume($$parsedSource as Partial<Volume>);
    }
}

// Private type creation functions
const $$createType0 = TypeMount.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = TypeBlock.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = swarm$0.Version.createFrom;
const $$createType5 = ClusterVolumeSpec.createFrom;
const $$createType6 = PublishStatus.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = Info.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = AccessMode.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = TopologyRequirement.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = CapacityRange.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = Secret.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $Create.Map($Create.Any, $Create.Any);
const $$createType20 = Topology.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = $Create.Array($Create.Any);
const $$createType23 = ClusterVolume.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = $Create.Map($Create.Any, $Create.Any);
const $$createType26 = UsageData.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
