// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Version represents the internal object version.
 */
export class Version {
    /**
     * Creates a new Version instance.
     * @param {Partial<Version>} [$$source = {}] - The source object to create the Version.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["Index"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Version instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Version}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Version(/** @type {Partial<Version>} */($$parsedSource));
    }
}
