// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Ulimit is a human friendly version of Rlimit.
 */
export class Ulimit {
    "Name": string;
    "Hard": number;
    "Soft": number;

    /** Creates a new Ulimit instance. */
    constructor($$source: Partial<Ulimit> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Hard" in $$source)) {
            this["Hard"] = 0;
        }
        if (!("Soft" in $$source)) {
            this["Soft"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Ulimit instance from a string or object.
     */
    static createFrom($$source: any = {}): Ulimit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Ulimit($$parsedSource as Partial<Ulimit>);
    }
}
