// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DiffType defines the comparison result between two FileNodes
 */
export enum DiffType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    Unmodified = 0,
    Modified = 1,
    Added = 2,
    Removed = 3,
};
