// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as units$0 from "../../../../../docker/go-units/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as v1$0 from "../../../../docker-image-spec/specs-go/v1/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as blkiodev$0 from "../blkiodev/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mount$0 from "../mount/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as network$0 from "../network/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as v1$1 from "../../../../../opencontainers/image-spec/specs-go/v1/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as netip$0 from "../../../../../../net/netip/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

/**
 * CgroupSpec represents the cgroup to use for the container.
 */
export type CgroupSpec = string;

/**
 * CgroupnsMode represents the cgroup namespace mode of the container
 */
export enum CgroupnsMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * cgroup namespace modes for containers
     */
    CgroupnsModeEmpty = "",
    CgroupnsModePrivate = "private",
    CgroupnsModeHost = "host",
};

/**
 * Config contains the configuration data about a container.
 * It should hold only portable information about the container.
 * Here, "portable" means "independent from the host we are running on".
 * Non-portable information *should* appear in HostConfig.
 * All fields added to this struct must be marked `omitempty` to keep getting
 * predictable hashes from the old `v1Compatibility` configuration.
 */
export class Config {
    /**
     * Hostname
     */
    "Hostname": string;

    /**
     * Domainname
     */
    "Domainname": string;

    /**
     * User that will run the command(s) inside the container, also support user:group
     */
    "User": string;

    /**
     * Attach the standard input, makes possible user interaction
     */
    "AttachStdin": boolean;

    /**
     * Attach the standard output
     */
    "AttachStdout": boolean;

    /**
     * Attach the standard error
     */
    "AttachStderr": boolean;

    /**
     * List of exposed ports
     */
    "ExposedPorts"?: network$0.PortSet;

    /**
     * Attach standard streams to a tty, including stdin if it is not closed.
     */
    "Tty": boolean;

    /**
     * Open stdin
     */
    "OpenStdin": boolean;

    /**
     * If true, close stdin after the 1 attached client disconnects.
     */
    "StdinOnce": boolean;

    /**
     * List of environment variable to set in the container
     */
    "Env": string[];

    /**
     * Command to run when starting the container
     */
    "Cmd": string[];

    /**
     * Healthcheck describes how to check the container is healthy
     */
    "Healthcheck"?: HealthConfig | null;

    /**
     * True if command is already escaped (meaning treat as a command line) (Windows specific).
     */
    "ArgsEscaped"?: boolean;

    /**
     * Name of the image as it was passed by the operator (e.g. could be symbolic)
     */
    "Image": string;

    /**
     * List of volumes (mounts) used for the container
     */
    "Volumes": { [_: string]: {} };

    /**
     * Current directory (PWD) in the command will be launched
     */
    "WorkingDir": string;

    /**
     * Entrypoint to run when starting the container
     */
    "Entrypoint": string[];

    /**
     * Is network disabled
     */
    "NetworkDisabled"?: boolean;

    /**
     * ONBUILD metadata that were defined on the image Dockerfile
     */
    "OnBuild"?: string[];

    /**
     * List of labels set to this container
     */
    "Labels": { [_: string]: string };

    /**
     * Signal to stop a container
     */
    "StopSignal"?: string;

    /**
     * Timeout (in seconds) to stop a container
     */
    "StopTimeout"?: number | null;

    /**
     * Shell for shell-form of RUN, CMD, ENTRYPOINT
     */
    "Shell"?: string[];

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("Hostname" in $$source)) {
            this["Hostname"] = "";
        }
        if (!("Domainname" in $$source)) {
            this["Domainname"] = "";
        }
        if (!("User" in $$source)) {
            this["User"] = "";
        }
        if (!("AttachStdin" in $$source)) {
            this["AttachStdin"] = false;
        }
        if (!("AttachStdout" in $$source)) {
            this["AttachStdout"] = false;
        }
        if (!("AttachStderr" in $$source)) {
            this["AttachStderr"] = false;
        }
        if (!("Tty" in $$source)) {
            this["Tty"] = false;
        }
        if (!("OpenStdin" in $$source)) {
            this["OpenStdin"] = false;
        }
        if (!("StdinOnce" in $$source)) {
            this["StdinOnce"] = false;
        }
        if (!("Env" in $$source)) {
            this["Env"] = [];
        }
        if (!("Cmd" in $$source)) {
            this["Cmd"] = [];
        }
        if (!("Image" in $$source)) {
            this["Image"] = "";
        }
        if (!("Volumes" in $$source)) {
            this["Volumes"] = {};
        }
        if (!("WorkingDir" in $$source)) {
            this["WorkingDir"] = "";
        }
        if (!("Entrypoint" in $$source)) {
            this["Entrypoint"] = [];
        }
        if (!("Labels" in $$source)) {
            this["Labels"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField6_0 = $$createType0;
        const $$createField10_0 = $$createType1;
        const $$createField11_0 = $$createType1;
        const $$createField12_0 = $$createType3;
        const $$createField15_0 = $$createType4;
        const $$createField17_0 = $$createType1;
        const $$createField19_0 = $$createType1;
        const $$createField20_0 = $$createType5;
        const $$createField23_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ExposedPorts" in $$parsedSource) {
            $$parsedSource["ExposedPorts"] = $$createField6_0($$parsedSource["ExposedPorts"]);
        }
        if ("Env" in $$parsedSource) {
            $$parsedSource["Env"] = $$createField10_0($$parsedSource["Env"]);
        }
        if ("Cmd" in $$parsedSource) {
            $$parsedSource["Cmd"] = $$createField11_0($$parsedSource["Cmd"]);
        }
        if ("Healthcheck" in $$parsedSource) {
            $$parsedSource["Healthcheck"] = $$createField12_0($$parsedSource["Healthcheck"]);
        }
        if ("Volumes" in $$parsedSource) {
            $$parsedSource["Volumes"] = $$createField15_0($$parsedSource["Volumes"]);
        }
        if ("Entrypoint" in $$parsedSource) {
            $$parsedSource["Entrypoint"] = $$createField17_0($$parsedSource["Entrypoint"]);
        }
        if ("OnBuild" in $$parsedSource) {
            $$parsedSource["OnBuild"] = $$createField19_0($$parsedSource["OnBuild"]);
        }
        if ("Labels" in $$parsedSource) {
            $$parsedSource["Labels"] = $$createField20_0($$parsedSource["Labels"]);
        }
        if ("Shell" in $$parsedSource) {
            $$parsedSource["Shell"] = $$createField23_0($$parsedSource["Shell"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * ContainerState is a string representation of the container's current state.
 */
export enum ContainerState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * StateCreated indicates the container is created, but not (yet) started.
     */
    StateCreated = "created",

    /**
     * StateRunning indicates that the container is running.
     */
    StateRunning = "running",

    /**
     * StatePaused indicates that the container's current state is paused.
     */
    StatePaused = "paused",

    /**
     * StateRestarting indicates that the container is currently restarting.
     */
    StateRestarting = "restarting",

    /**
     * StateRemoving indicates that the container is being removed.
     */
    StateRemoving = "removing",

    /**
     * StateExited indicates that the container exited.
     */
    StateExited = "exited",

    /**
     * StateDead indicates that the container failed to be deleted. Containers in this state are attempted to be cleaned up when the daemon restarts.
     */
    StateDead = "dead",
};

/**
 * DeviceMapping represents the device mapping between the host and the container.
 */
export class DeviceMapping {
    "PathOnHost": string;
    "PathInContainer": string;
    "CgroupPermissions": string;

    /** Creates a new DeviceMapping instance. */
    constructor($$source: Partial<DeviceMapping> = {}) {
        if (!("PathOnHost" in $$source)) {
            this["PathOnHost"] = "";
        }
        if (!("PathInContainer" in $$source)) {
            this["PathInContainer"] = "";
        }
        if (!("CgroupPermissions" in $$source)) {
            this["CgroupPermissions"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceMapping instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceMapping {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceMapping($$parsedSource as Partial<DeviceMapping>);
    }
}

/**
 * DeviceRequest represents a request for devices from a device driver.
 * Used by GPU device drivers.
 */
export class DeviceRequest {
    /**
     * Name of device driver
     */
    "Driver": string;

    /**
     * Number of devices to request (-1 = All)
     */
    "Count": number;

    /**
     * List of device IDs as recognizable by the device driver
     */
    "DeviceIDs": string[];

    /**
     * An OR list of AND lists of device capabilities (e.g. "gpu")
     */
    "Capabilities": string[][];

    /**
     * Options to pass onto the device driver
     */
    "Options": { [_: string]: string };

    /** Creates a new DeviceRequest instance. */
    constructor($$source: Partial<DeviceRequest> = {}) {
        if (!("Driver" in $$source)) {
            this["Driver"] = "";
        }
        if (!("Count" in $$source)) {
            this["Count"] = 0;
        }
        if (!("DeviceIDs" in $$source)) {
            this["DeviceIDs"] = [];
        }
        if (!("Capabilities" in $$source)) {
            this["Capabilities"] = [];
        }
        if (!("Options" in $$source)) {
            this["Options"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceRequest {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType6;
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("DeviceIDs" in $$parsedSource) {
            $$parsedSource["DeviceIDs"] = $$createField2_0($$parsedSource["DeviceIDs"]);
        }
        if ("Capabilities" in $$parsedSource) {
            $$parsedSource["Capabilities"] = $$createField3_0($$parsedSource["Capabilities"]);
        }
        if ("Options" in $$parsedSource) {
            $$parsedSource["Options"] = $$createField4_0($$parsedSource["Options"]);
        }
        return new DeviceRequest($$parsedSource as Partial<DeviceRequest>);
    }
}

/**
 * Health stores information about the container's healthcheck results
 */
export class Health {
    /**
     * Status is one of [Starting], [Healthy] or [Unhealthy].
     */
    "Status": HealthStatus;

    /**
     * FailingStreak is the number of consecutive failures
     */
    "FailingStreak": number;

    /**
     * Log contains the last few results (oldest first)
     */
    "Log": (HealthcheckResult | null)[];

    /** Creates a new Health instance. */
    constructor($$source: Partial<Health> = {}) {
        if (!("Status" in $$source)) {
            this["Status"] = HealthStatus.$zero;
        }
        if (!("FailingStreak" in $$source)) {
            this["FailingStreak"] = 0;
        }
        if (!("Log" in $$source)) {
            this["Log"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Health instance from a string or object.
     */
    static createFrom($$source: any = {}): Health {
        const $$createField2_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Log" in $$parsedSource) {
            $$parsedSource["Log"] = $$createField2_0($$parsedSource["Log"]);
        }
        return new Health($$parsedSource as Partial<Health>);
    }
}

/**
 * HealthConfig holds configuration settings for the HEALTHCHECK feature.
 */
export const HealthConfig = v1$0.HealthcheckConfig;

/**
 * HealthConfig holds configuration settings for the HEALTHCHECK feature.
 */
export type HealthConfig = v1$0.HealthcheckConfig;

/**
 * HealthStatus is a string representation of the container's health.
 */
export enum HealthStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Health states
     *
     * Indicates there is no healthcheck
     */
    NoHealthcheck = "none",

    /**
     * Starting indicates that the container is not yet ready
     */
    Starting = "starting",

    /**
     * Healthy indicates that the container is running correctly
     */
    Healthy = "healthy",

    /**
     * Unhealthy indicates that the container has a problem
     */
    Unhealthy = "unhealthy",
};

/**
 * HealthSummary stores a summary of the container's healthcheck results.
 */
export class HealthSummary {
    /**
     * Status is one of [NoHealthcheck], [Starting], [Healthy] or [Unhealthy].
     */
    "Status": HealthStatus;

    /**
     * FailingStreak is the number of consecutive failures
     */
    "FailingStreak": number;

    /** Creates a new HealthSummary instance. */
    constructor($$source: Partial<HealthSummary> = {}) {
        if (!("Status" in $$source)) {
            this["Status"] = HealthStatus.$zero;
        }
        if (!("FailingStreak" in $$source)) {
            this["FailingStreak"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HealthSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): HealthSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HealthSummary($$parsedSource as Partial<HealthSummary>);
    }
}

/**
 * HealthcheckResult stores information about a single run of a healthcheck probe
 */
export class HealthcheckResult {
    /**
     * Start is the time this check started
     */
    "Start": time$0.Time;

    /**
     * End is the time this check ended
     */
    "End": time$0.Time;

    /**
     * ExitCode meanings: 0=healthy, 1=unhealthy, 2=reserved (considered unhealthy), else=error running probe
     */
    "ExitCode": number;

    /**
     * Output from last check
     */
    "Output": string;

    /** Creates a new HealthcheckResult instance. */
    constructor($$source: Partial<HealthcheckResult> = {}) {
        if (!("Start" in $$source)) {
            this["Start"] = null;
        }
        if (!("End" in $$source)) {
            this["End"] = null;
        }
        if (!("ExitCode" in $$source)) {
            this["ExitCode"] = 0;
        }
        if (!("Output" in $$source)) {
            this["Output"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HealthcheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): HealthcheckResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HealthcheckResult($$parsedSource as Partial<HealthcheckResult>);
    }
}

/**
 * HostConfig the non-portable Config structure of a container.
 * Here, "non-portable" means "dependent of the host we are running on".
 * Portable information *should* appear in Config.
 */
export class HostConfig {
    /**
     * Applicable to all platforms
     * List of volume bindings for this container
     */
    "Binds": string[];

    /**
     * File (path) where the containerId is written
     */
    "ContainerIDFile": string;

    /**
     * Configuration of the logs for this container
     */
    "LogConfig": LogConfig;

    /**
     * Network mode to use for the container
     */
    "NetworkMode": NetworkMode;

    /**
     * Port mapping between the exposed port (container) and the host
     */
    "PortBindings": network$0.PortMap;

    /**
     * Restart policy to be used for the container
     */
    "RestartPolicy": RestartPolicy;

    /**
     * Automatically remove container when it exits
     */
    "AutoRemove": boolean;

    /**
     * Name of the volume driver used to mount volumes
     */
    "VolumeDriver": string;

    /**
     * List of volumes to take from other container
     */
    "VolumesFrom": string[];

    /**
     * Initial console size (height,width)
     */
    "ConsoleSize": number[];

    /**
     * Arbitrary non-identifying metadata attached to container and provided to the runtime
     */
    "Annotations"?: { [_: string]: string };

    /**
     * Applicable to UNIX platforms
     * List of kernel capabilities to add to the container
     */
    "CapAdd": string[];

    /**
     * List of kernel capabilities to remove from the container
     */
    "CapDrop": string[];

    /**
     * Cgroup namespace mode to use for the container
     */
    "CgroupnsMode": CgroupnsMode;

    /**
     * List of DNS server to lookup
     */
    "Dns": netip$0.Addr[];

    /**
     * List of DNSOption to look for
     */
    "DnsOptions": string[];

    /**
     * List of DNSSearch to look for
     */
    "DnsSearch": string[];

    /**
     * List of extra hosts
     */
    "ExtraHosts": string[];

    /**
     * List of additional groups that the container process will run as
     */
    "GroupAdd": string[];

    /**
     * IPC namespace to use for the container
     */
    "IpcMode": IpcMode;

    /**
     * Cgroup to use for the container
     */
    "Cgroup": CgroupSpec;

    /**
     * List of links (in the name:alias form)
     */
    "Links": string[];

    /**
     * Container preference for OOM-killing
     */
    "OomScoreAdj": number;

    /**
     * PID namespace to use for the container
     */
    "PidMode": PidMode;

    /**
     * Is the container in privileged mode
     */
    "Privileged": boolean;

    /**
     * Should docker publish all exposed port for the container
     */
    "PublishAllPorts": boolean;

    /**
     * Is the container root filesystem in read-only
     */
    "ReadonlyRootfs": boolean;

    /**
     * List of string values to customize labels for MLS systems, such as SELinux.
     */
    "SecurityOpt": string[];

    /**
     * Storage driver options per container.
     */
    "StorageOpt"?: { [_: string]: string };

    /**
     * List of tmpfs (mounts) used for the container
     */
    "Tmpfs"?: { [_: string]: string };

    /**
     * UTS namespace to use for the container
     */
    "UTSMode": UTSMode;

    /**
     * The user namespace to use for the container
     */
    "UsernsMode": UsernsMode;

    /**
     * Total shm memory usage
     */
    "ShmSize": number;

    /**
     * List of Namespaced sysctls used for the container
     */
    "Sysctls"?: { [_: string]: string };

    /**
     * Runtime to use with this container
     */
    "Runtime"?: string;

    /**
     * Applicable to Windows
     * Isolation technology of the container (e.g. default, hyperv)
     */
    "Isolation": Isolation;

    /**
     * Applicable to all platforms
     * CPU shares (relative weight vs. other containers)
     */
    "CpuShares": number;

    /**
     * Memory limit (in bytes)
     */
    "Memory": number;

    /**
     * CPU quota in units of 10<sup>-9</sup> CPUs.
     */
    "NanoCpus": number;

    /**
     * Applicable to UNIX platforms
     * Parent cgroup.
     */
    "CgroupParent": string;

    /**
     * Block IO weight (relative weight vs. other containers)
     */
    "BlkioWeight": number;
    "BlkioWeightDevice": (blkiodev$0.WeightDevice | null)[];
    "BlkioDeviceReadBps": (blkiodev$0.ThrottleDevice | null)[];
    "BlkioDeviceWriteBps": (blkiodev$0.ThrottleDevice | null)[];
    "BlkioDeviceReadIOps": (blkiodev$0.ThrottleDevice | null)[];
    "BlkioDeviceWriteIOps": (blkiodev$0.ThrottleDevice | null)[];

    /**
     * CPU CFS (Completely Fair Scheduler) period
     */
    "CpuPeriod": number;

    /**
     * CPU CFS (Completely Fair Scheduler) quota
     */
    "CpuQuota": number;

    /**
     * CPU real-time period
     */
    "CpuRealtimePeriod": number;

    /**
     * CPU real-time runtime
     */
    "CpuRealtimeRuntime": number;

    /**
     * CpusetCpus 0-2, 0,1
     */
    "CpusetCpus": string;

    /**
     * CpusetMems 0-2, 0,1
     */
    "CpusetMems": string;

    /**
     * List of devices to map inside the container
     */
    "Devices": DeviceMapping[];

    /**
     * List of rule to be added to the device cgroup
     */
    "DeviceCgroupRules": string[];

    /**
     * List of device requests for device drivers
     */
    "DeviceRequests": DeviceRequest[];

    /**
     * Memory soft limit (in bytes)
     */
    "MemoryReservation": number;

    /**
     * Total memory usage (memory + swap); set `-1` to enable unlimited swap
     */
    "MemorySwap": number;

    /**
     * Tuning container memory swappiness behaviour
     */
    "MemorySwappiness": number | null;

    /**
     * Whether to disable OOM Killer or not
     */
    "OomKillDisable": boolean | null;

    /**
     * Setting PIDs limit for a container; Set `0` or `-1` for unlimited, or `null` to not change.
     */
    "PidsLimit": number | null;

    /**
     * List of ulimits to be set in the container
     */
    "Ulimits": (Ulimit | null)[];

    /**
     * Applicable to Windows
     * CPU count
     */
    "CpuCount": number;

    /**
     * CPU percent
     */
    "CpuPercent": number;

    /**
     * Maximum IOps for the container system drive
     */
    "IOMaximumIOps": number;

    /**
     * Maximum IO in bytes per second for the container system drive
     */
    "IOMaximumBandwidth": number;

    /**
     * Mounts specs used by the container
     */
    "Mounts"?: mount$0.Mount[];

    /**
     * MaskedPaths is the list of paths to be masked inside the container (this overrides the default set of paths)
     */
    "MaskedPaths": string[];

    /**
     * ReadonlyPaths is the list of paths to be set as read-only inside the container (this overrides the default set of paths)
     */
    "ReadonlyPaths": string[];

    /**
     * Run a custom init inside the container, if null, use the daemon's configured settings
     */
    "Init"?: boolean | null;

    /** Creates a new HostConfig instance. */
    constructor($$source: Partial<HostConfig> = {}) {
        if (!("Binds" in $$source)) {
            this["Binds"] = [];
        }
        if (!("ContainerIDFile" in $$source)) {
            this["ContainerIDFile"] = "";
        }
        if (!("LogConfig" in $$source)) {
            this["LogConfig"] = (new LogConfig());
        }
        if (!("NetworkMode" in $$source)) {
            this["NetworkMode"] = "";
        }
        if (!("PortBindings" in $$source)) {
            this["PortBindings"] = {};
        }
        if (!("RestartPolicy" in $$source)) {
            this["RestartPolicy"] = (new RestartPolicy());
        }
        if (!("AutoRemove" in $$source)) {
            this["AutoRemove"] = false;
        }
        if (!("VolumeDriver" in $$source)) {
            this["VolumeDriver"] = "";
        }
        if (!("VolumesFrom" in $$source)) {
            this["VolumesFrom"] = [];
        }
        if (!("ConsoleSize" in $$source)) {
            this["ConsoleSize"] = Array.from({ length: 2 }, () => 0);
        }
        if (!("CapAdd" in $$source)) {
            this["CapAdd"] = [];
        }
        if (!("CapDrop" in $$source)) {
            this["CapDrop"] = [];
        }
        if (!("CgroupnsMode" in $$source)) {
            this["CgroupnsMode"] = CgroupnsMode.$zero;
        }
        if (!("Dns" in $$source)) {
            this["Dns"] = [];
        }
        if (!("DnsOptions" in $$source)) {
            this["DnsOptions"] = [];
        }
        if (!("DnsSearch" in $$source)) {
            this["DnsSearch"] = [];
        }
        if (!("ExtraHosts" in $$source)) {
            this["ExtraHosts"] = [];
        }
        if (!("GroupAdd" in $$source)) {
            this["GroupAdd"] = [];
        }
        if (!("IpcMode" in $$source)) {
            this["IpcMode"] = IpcMode.$zero;
        }
        if (!("Cgroup" in $$source)) {
            this["Cgroup"] = "";
        }
        if (!("Links" in $$source)) {
            this["Links"] = [];
        }
        if (!("OomScoreAdj" in $$source)) {
            this["OomScoreAdj"] = 0;
        }
        if (!("PidMode" in $$source)) {
            this["PidMode"] = "";
        }
        if (!("Privileged" in $$source)) {
            this["Privileged"] = false;
        }
        if (!("PublishAllPorts" in $$source)) {
            this["PublishAllPorts"] = false;
        }
        if (!("ReadonlyRootfs" in $$source)) {
            this["ReadonlyRootfs"] = false;
        }
        if (!("SecurityOpt" in $$source)) {
            this["SecurityOpt"] = [];
        }
        if (!("UTSMode" in $$source)) {
            this["UTSMode"] = "";
        }
        if (!("UsernsMode" in $$source)) {
            this["UsernsMode"] = "";
        }
        if (!("ShmSize" in $$source)) {
            this["ShmSize"] = 0;
        }
        if (!("Isolation" in $$source)) {
            this["Isolation"] = Isolation.$zero;
        }
        if (!("CpuShares" in $$source)) {
            this["CpuShares"] = 0;
        }
        if (!("Memory" in $$source)) {
            this["Memory"] = 0;
        }
        if (!("NanoCpus" in $$source)) {
            this["NanoCpus"] = 0;
        }
        if (!("CgroupParent" in $$source)) {
            this["CgroupParent"] = "";
        }
        if (!("BlkioWeight" in $$source)) {
            this["BlkioWeight"] = 0;
        }
        if (!("BlkioWeightDevice" in $$source)) {
            this["BlkioWeightDevice"] = [];
        }
        if (!("BlkioDeviceReadBps" in $$source)) {
            this["BlkioDeviceReadBps"] = [];
        }
        if (!("BlkioDeviceWriteBps" in $$source)) {
            this["BlkioDeviceWriteBps"] = [];
        }
        if (!("BlkioDeviceReadIOps" in $$source)) {
            this["BlkioDeviceReadIOps"] = [];
        }
        if (!("BlkioDeviceWriteIOps" in $$source)) {
            this["BlkioDeviceWriteIOps"] = [];
        }
        if (!("CpuPeriod" in $$source)) {
            this["CpuPeriod"] = 0;
        }
        if (!("CpuQuota" in $$source)) {
            this["CpuQuota"] = 0;
        }
        if (!("CpuRealtimePeriod" in $$source)) {
            this["CpuRealtimePeriod"] = 0;
        }
        if (!("CpuRealtimeRuntime" in $$source)) {
            this["CpuRealtimeRuntime"] = 0;
        }
        if (!("CpusetCpus" in $$source)) {
            this["CpusetCpus"] = "";
        }
        if (!("CpusetMems" in $$source)) {
            this["CpusetMems"] = "";
        }
        if (!("Devices" in $$source)) {
            this["Devices"] = [];
        }
        if (!("DeviceCgroupRules" in $$source)) {
            this["DeviceCgroupRules"] = [];
        }
        if (!("DeviceRequests" in $$source)) {
            this["DeviceRequests"] = [];
        }
        if (!("MemoryReservation" in $$source)) {
            this["MemoryReservation"] = 0;
        }
        if (!("MemorySwap" in $$source)) {
            this["MemorySwap"] = 0;
        }
        if (!("MemorySwappiness" in $$source)) {
            this["MemorySwappiness"] = null;
        }
        if (!("OomKillDisable" in $$source)) {
            this["OomKillDisable"] = null;
        }
        if (!("PidsLimit" in $$source)) {
            this["PidsLimit"] = null;
        }
        if (!("Ulimits" in $$source)) {
            this["Ulimits"] = [];
        }
        if (!("CpuCount" in $$source)) {
            this["CpuCount"] = 0;
        }
        if (!("CpuPercent" in $$source)) {
            this["CpuPercent"] = 0;
        }
        if (!("IOMaximumIOps" in $$source)) {
            this["IOMaximumIOps"] = 0;
        }
        if (!("IOMaximumBandwidth" in $$source)) {
            this["IOMaximumBandwidth"] = 0;
        }
        if (!("MaskedPaths" in $$source)) {
            this["MaskedPaths"] = [];
        }
        if (!("ReadonlyPaths" in $$source)) {
            this["ReadonlyPaths"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): HostConfig {
        const $$createField0_0 = $$createType1;
        const $$createField2_0 = $$createType10;
        const $$createField4_0 = $$createType13;
        const $$createField5_0 = $$createType14;
        const $$createField8_0 = $$createType1;
        const $$createField10_0 = $$createType5;
        const $$createField11_0 = $$createType1;
        const $$createField12_0 = $$createType1;
        const $$createField14_0 = $$createType15;
        const $$createField15_0 = $$createType1;
        const $$createField16_0 = $$createType1;
        const $$createField17_0 = $$createType1;
        const $$createField18_0 = $$createType1;
        const $$createField21_0 = $$createType1;
        const $$createField27_0 = $$createType1;
        const $$createField28_0 = $$createType5;
        const $$createField29_0 = $$createType5;
        const $$createField33_0 = $$createType5;
        const $$createField41_0 = $$createType18;
        const $$createField42_0 = $$createType21;
        const $$createField43_0 = $$createType21;
        const $$createField44_0 = $$createType21;
        const $$createField45_0 = $$createType21;
        const $$createField52_0 = $$createType23;
        const $$createField53_0 = $$createType1;
        const $$createField54_0 = $$createType25;
        const $$createField60_0 = $$createType28;
        const $$createField65_0 = $$createType30;
        const $$createField66_0 = $$createType1;
        const $$createField67_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Binds" in $$parsedSource) {
            $$parsedSource["Binds"] = $$createField0_0($$parsedSource["Binds"]);
        }
        if ("LogConfig" in $$parsedSource) {
            $$parsedSource["LogConfig"] = $$createField2_0($$parsedSource["LogConfig"]);
        }
        if ("PortBindings" in $$parsedSource) {
            $$parsedSource["PortBindings"] = $$createField4_0($$parsedSource["PortBindings"]);
        }
        if ("RestartPolicy" in $$parsedSource) {
            $$parsedSource["RestartPolicy"] = $$createField5_0($$parsedSource["RestartPolicy"]);
        }
        if ("VolumesFrom" in $$parsedSource) {
            $$parsedSource["VolumesFrom"] = $$createField8_0($$parsedSource["VolumesFrom"]);
        }
        if ("Annotations" in $$parsedSource) {
            $$parsedSource["Annotations"] = $$createField10_0($$parsedSource["Annotations"]);
        }
        if ("CapAdd" in $$parsedSource) {
            $$parsedSource["CapAdd"] = $$createField11_0($$parsedSource["CapAdd"]);
        }
        if ("CapDrop" in $$parsedSource) {
            $$parsedSource["CapDrop"] = $$createField12_0($$parsedSource["CapDrop"]);
        }
        if ("Dns" in $$parsedSource) {
            $$parsedSource["Dns"] = $$createField14_0($$parsedSource["Dns"]);
        }
        if ("DnsOptions" in $$parsedSource) {
            $$parsedSource["DnsOptions"] = $$createField15_0($$parsedSource["DnsOptions"]);
        }
        if ("DnsSearch" in $$parsedSource) {
            $$parsedSource["DnsSearch"] = $$createField16_0($$parsedSource["DnsSearch"]);
        }
        if ("ExtraHosts" in $$parsedSource) {
            $$parsedSource["ExtraHosts"] = $$createField17_0($$parsedSource["ExtraHosts"]);
        }
        if ("GroupAdd" in $$parsedSource) {
            $$parsedSource["GroupAdd"] = $$createField18_0($$parsedSource["GroupAdd"]);
        }
        if ("Links" in $$parsedSource) {
            $$parsedSource["Links"] = $$createField21_0($$parsedSource["Links"]);
        }
        if ("SecurityOpt" in $$parsedSource) {
            $$parsedSource["SecurityOpt"] = $$createField27_0($$parsedSource["SecurityOpt"]);
        }
        if ("StorageOpt" in $$parsedSource) {
            $$parsedSource["StorageOpt"] = $$createField28_0($$parsedSource["StorageOpt"]);
        }
        if ("Tmpfs" in $$parsedSource) {
            $$parsedSource["Tmpfs"] = $$createField29_0($$parsedSource["Tmpfs"]);
        }
        if ("Sysctls" in $$parsedSource) {
            $$parsedSource["Sysctls"] = $$createField33_0($$parsedSource["Sysctls"]);
        }
        if ("BlkioWeightDevice" in $$parsedSource) {
            $$parsedSource["BlkioWeightDevice"] = $$createField41_0($$parsedSource["BlkioWeightDevice"]);
        }
        if ("BlkioDeviceReadBps" in $$parsedSource) {
            $$parsedSource["BlkioDeviceReadBps"] = $$createField42_0($$parsedSource["BlkioDeviceReadBps"]);
        }
        if ("BlkioDeviceWriteBps" in $$parsedSource) {
            $$parsedSource["BlkioDeviceWriteBps"] = $$createField43_0($$parsedSource["BlkioDeviceWriteBps"]);
        }
        if ("BlkioDeviceReadIOps" in $$parsedSource) {
            $$parsedSource["BlkioDeviceReadIOps"] = $$createField44_0($$parsedSource["BlkioDeviceReadIOps"]);
        }
        if ("BlkioDeviceWriteIOps" in $$parsedSource) {
            $$parsedSource["BlkioDeviceWriteIOps"] = $$createField45_0($$parsedSource["BlkioDeviceWriteIOps"]);
        }
        if ("Devices" in $$parsedSource) {
            $$parsedSource["Devices"] = $$createField52_0($$parsedSource["Devices"]);
        }
        if ("DeviceCgroupRules" in $$parsedSource) {
            $$parsedSource["DeviceCgroupRules"] = $$createField53_0($$parsedSource["DeviceCgroupRules"]);
        }
        if ("DeviceRequests" in $$parsedSource) {
            $$parsedSource["DeviceRequests"] = $$createField54_0($$parsedSource["DeviceRequests"]);
        }
        if ("Ulimits" in $$parsedSource) {
            $$parsedSource["Ulimits"] = $$createField60_0($$parsedSource["Ulimits"]);
        }
        if ("Mounts" in $$parsedSource) {
            $$parsedSource["Mounts"] = $$createField65_0($$parsedSource["Mounts"]);
        }
        if ("MaskedPaths" in $$parsedSource) {
            $$parsedSource["MaskedPaths"] = $$createField66_0($$parsedSource["MaskedPaths"]);
        }
        if ("ReadonlyPaths" in $$parsedSource) {
            $$parsedSource["ReadonlyPaths"] = $$createField67_0($$parsedSource["ReadonlyPaths"]);
        }
        return new HostConfig($$parsedSource as Partial<HostConfig>);
    }
}

/**
 * InspectResponse is the response for the GET "/containers/{name:.*}/json"
 * endpoint.
 */
export class InspectResponse {
    "Id": string;
    "Created": string;
    "Path": string;
    "Args": string[];
    "State": State | null;
    "Image": string;
    "ResolvConfPath": string;
    "HostnamePath": string;
    "HostsPath": string;
    "LogPath": string;
    "Name": string;
    "RestartCount": number;
    "Driver": string;
    "Platform": string;
    "MountLabel": string;
    "ProcessLabel": string;
    "AppArmorProfile": string;
    "ExecIDs": string[];
    "HostConfig": HostConfig | null;

    /**
     * GraphDriver contains information about the container's graph driver.
     */
    "GraphDriver"?: storage$0.DriverData | null;

    /**
     * Storage contains information about the storage used for the container's filesystem.
     */
    "Storage"?: storage$0.Storage | null;
    "SizeRw"?: number | null;
    "SizeRootFs"?: number | null;
    "Mounts": MountPoint[];
    "Config": Config | null;
    "NetworkSettings": NetworkSettings | null;

    /**
     * ImageManifestDescriptor is the descriptor of a platform-specific manifest of the image used to create the container.
     */
    "ImageManifestDescriptor"?: v1$1.Descriptor | null;

    /** Creates a new InspectResponse instance. */
    constructor($$source: Partial<InspectResponse> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Created" in $$source)) {
            this["Created"] = "";
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Args" in $$source)) {
            this["Args"] = [];
        }
        if (!("State" in $$source)) {
            this["State"] = null;
        }
        if (!("Image" in $$source)) {
            this["Image"] = "";
        }
        if (!("ResolvConfPath" in $$source)) {
            this["ResolvConfPath"] = "";
        }
        if (!("HostnamePath" in $$source)) {
            this["HostnamePath"] = "";
        }
        if (!("HostsPath" in $$source)) {
            this["HostsPath"] = "";
        }
        if (!("LogPath" in $$source)) {
            this["LogPath"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("RestartCount" in $$source)) {
            this["RestartCount"] = 0;
        }
        if (!("Driver" in $$source)) {
            this["Driver"] = "";
        }
        if (!("Platform" in $$source)) {
            this["Platform"] = "";
        }
        if (!("MountLabel" in $$source)) {
            this["MountLabel"] = "";
        }
        if (!("ProcessLabel" in $$source)) {
            this["ProcessLabel"] = "";
        }
        if (!("AppArmorProfile" in $$source)) {
            this["AppArmorProfile"] = "";
        }
        if (!("ExecIDs" in $$source)) {
            this["ExecIDs"] = [];
        }
        if (!("HostConfig" in $$source)) {
            this["HostConfig"] = null;
        }
        if (!("Mounts" in $$source)) {
            this["Mounts"] = [];
        }
        if (!("Config" in $$source)) {
            this["Config"] = null;
        }
        if (!("NetworkSettings" in $$source)) {
            this["NetworkSettings"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InspectResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): InspectResponse {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType32;
        const $$createField17_0 = $$createType1;
        const $$createField18_0 = $$createType34;
        const $$createField19_0 = $$createType36;
        const $$createField20_0 = $$createType38;
        const $$createField23_0 = $$createType40;
        const $$createField24_0 = $$createType42;
        const $$createField25_0 = $$createType44;
        const $$createField26_0 = $$createType46;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Args" in $$parsedSource) {
            $$parsedSource["Args"] = $$createField3_0($$parsedSource["Args"]);
        }
        if ("State" in $$parsedSource) {
            $$parsedSource["State"] = $$createField4_0($$parsedSource["State"]);
        }
        if ("ExecIDs" in $$parsedSource) {
            $$parsedSource["ExecIDs"] = $$createField17_0($$parsedSource["ExecIDs"]);
        }
        if ("HostConfig" in $$parsedSource) {
            $$parsedSource["HostConfig"] = $$createField18_0($$parsedSource["HostConfig"]);
        }
        if ("GraphDriver" in $$parsedSource) {
            $$parsedSource["GraphDriver"] = $$createField19_0($$parsedSource["GraphDriver"]);
        }
        if ("Storage" in $$parsedSource) {
            $$parsedSource["Storage"] = $$createField20_0($$parsedSource["Storage"]);
        }
        if ("Mounts" in $$parsedSource) {
            $$parsedSource["Mounts"] = $$createField23_0($$parsedSource["Mounts"]);
        }
        if ("Config" in $$parsedSource) {
            $$parsedSource["Config"] = $$createField24_0($$parsedSource["Config"]);
        }
        if ("NetworkSettings" in $$parsedSource) {
            $$parsedSource["NetworkSettings"] = $$createField25_0($$parsedSource["NetworkSettings"]);
        }
        if ("ImageManifestDescriptor" in $$parsedSource) {
            $$parsedSource["ImageManifestDescriptor"] = $$createField26_0($$parsedSource["ImageManifestDescriptor"]);
        }
        return new InspectResponse($$parsedSource as Partial<InspectResponse>);
    }
}

/**
 * IpcMode represents the container ipc stack.
 */
export enum IpcMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * IpcMode constants
     */
    IPCModeNone = "none",
    IPCModeHost = "host",
    IPCModeContainer = "container",
    IPCModePrivate = "private",
    IPCModeShareable = "shareable",
};

/**
 * Isolation represents the isolation technology of a container. The supported
 * values are platform specific
 */
export enum Isolation {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Isolation modes for containers
     *
     * IsolationEmpty is unspecified (same behavior as default)
     */
    IsolationEmpty = "",

    /**
     * IsolationDefault is the default isolation mode on current daemon
     */
    IsolationDefault = "default",

    /**
     * IsolationProcess is process isolation mode
     */
    IsolationProcess = "process",

    /**
     * IsolationHyperV is HyperV isolation mode
     */
    IsolationHyperV = "hyperv",
};

/**
 * LogConfig represents the logging configuration of the container.
 */
export class LogConfig {
    "Type": string;
    "Config": { [_: string]: string };

    /** Creates a new LogConfig instance. */
    constructor($$source: Partial<LogConfig> = {}) {
        if (!("Type" in $$source)) {
            this["Type"] = "";
        }
        if (!("Config" in $$source)) {
            this["Config"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): LogConfig {
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Config" in $$parsedSource) {
            $$parsedSource["Config"] = $$createField1_0($$parsedSource["Config"]);
        }
        return new LogConfig($$parsedSource as Partial<LogConfig>);
    }
}

/**
 * MountPoint represents a mount point configuration inside the container.
 * This is used for reporting the mountpoints in use by a container.
 */
export class MountPoint {
    /**
     * Type is the type of mount, see [mount.Type] definitions for details.
     */
    "Type"?: mount$0.Type;

    /**
     * Name is the name reference to the underlying data defined by `Source`
     * e.g., the volume name.
     */
    "Name"?: string;

    /**
     * Source is the source location of the mount.
     * 
     * For volumes, this contains the storage location of the volume (within
     * `/var/lib/docker/volumes/`). For bind-mounts, and `npipe`, this contains
     * the source (host) part of the bind-mount. For `tmpfs` mount points, this
     * field is empty.
     */
    "Source": string;

    /**
     * Destination is the path relative to the container root (`/`) where the
     * Source is mounted inside the container.
     */
    "Destination": string;

    /**
     * Driver is the volume driver used to create the volume (if it is a volume).
     */
    "Driver"?: string;

    /**
     * Mode is a comma separated list of options supplied by the user when
     * creating the bind/volume mount.
     * 
     * The default is platform-specific (`"z"` on Linux, empty on Windows).
     */
    "Mode": string;

    /**
     * RW indicates whether the mount is mounted writable (read-write).
     */
    "RW": boolean;

    /**
     * Propagation describes how mounts are propagated from the host into the
     * mount point, and vice-versa. Refer to the Linux kernel documentation
     * for details:
     * https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt
     * 
     * This field is not used on Windows.
     */
    "Propagation": mount$0.Propagation;

    /** Creates a new MountPoint instance. */
    constructor($$source: Partial<MountPoint> = {}) {
        if (!("Source" in $$source)) {
            this["Source"] = "";
        }
        if (!("Destination" in $$source)) {
            this["Destination"] = "";
        }
        if (!("Mode" in $$source)) {
            this["Mode"] = "";
        }
        if (!("RW" in $$source)) {
            this["RW"] = false;
        }
        if (!("Propagation" in $$source)) {
            this["Propagation"] = mount$0.Propagation.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MountPoint instance from a string or object.
     */
    static createFrom($$source: any = {}): MountPoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MountPoint($$parsedSource as Partial<MountPoint>);
    }
}

/**
 * NetworkMode represents the container network stack.
 */
export type NetworkMode = string;

/**
 * NetworkSettings exposes the network settings in the api
 */
export class NetworkSettings {
    /**
     * SandboxID uniquely represents a container's network stack
     */
    "SandboxID": string;

    /**
     * SandboxKey identifies the sandbox
     */
    "SandboxKey": string;

    /**
     * Ports is a collection of [network.PortBinding] indexed by [network.Port]
     */
    "Ports": network$0.PortMap;
    "Networks": { [_: string]: network$0.EndpointSettings | null };

    /** Creates a new NetworkSettings instance. */
    constructor($$source: Partial<NetworkSettings> = {}) {
        if (!("SandboxID" in $$source)) {
            this["SandboxID"] = "";
        }
        if (!("SandboxKey" in $$source)) {
            this["SandboxKey"] = "";
        }
        if (!("Ports" in $$source)) {
            this["Ports"] = {};
        }
        if (!("Networks" in $$source)) {
            this["Networks"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): NetworkSettings {
        const $$createField2_0 = $$createType13;
        const $$createField3_0 = $$createType49;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Ports" in $$parsedSource) {
            $$parsedSource["Ports"] = $$createField2_0($$parsedSource["Ports"]);
        }
        if ("Networks" in $$parsedSource) {
            $$parsedSource["Networks"] = $$createField3_0($$parsedSource["Networks"]);
        }
        return new NetworkSettings($$parsedSource as Partial<NetworkSettings>);
    }
}

/**
 * NetworkSettingsSummary provides a summary of container's networks
 * in /containers/json
 */
export class NetworkSettingsSummary {
    "Networks": { [_: string]: network$0.EndpointSettings | null };

    /** Creates a new NetworkSettingsSummary instance. */
    constructor($$source: Partial<NetworkSettingsSummary> = {}) {
        if (!("Networks" in $$source)) {
            this["Networks"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkSettingsSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): NetworkSettingsSummary {
        const $$createField0_0 = $$createType49;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Networks" in $$parsedSource) {
            $$parsedSource["Networks"] = $$createField0_0($$parsedSource["Networks"]);
        }
        return new NetworkSettingsSummary($$parsedSource as Partial<NetworkSettingsSummary>);
    }
}

/**
 * PidMode represents the pid namespace of the container.
 */
export type PidMode = string;

/**
 * PortSummary Describes a port-mapping between the container and the host.
 * 
 * Example: {"PrivatePort":8080,"PublicPort":80,"Type":"tcp"}
 * 
 * swagger:model PortSummary
 */
export class PortSummary {
    /**
     * Host IP address that the container's port is mapped to
     */
    "IP"?: netip$0.Addr;

    /**
     * Port on the container
     * Required: true
     */
    "PrivatePort": number;

    /**
     * Port exposed on the host
     */
    "PublicPort"?: number;

    /**
     * type
     * Required: true
     * Enum: ["tcp","udp","sctp"]
     */
    "Type": string;

    /** Creates a new PortSummary instance. */
    constructor($$source: Partial<PortSummary> = {}) {
        if (!("PrivatePort" in $$source)) {
            this["PrivatePort"] = 0;
        }
        if (!("Type" in $$source)) {
            this["Type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): PortSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortSummary($$parsedSource as Partial<PortSummary>);
    }
}

/**
 * RestartPolicy represents the restart policies of the container.
 */
export class RestartPolicy {
    "Name": RestartPolicyMode;
    "MaximumRetryCount": number;

    /** Creates a new RestartPolicy instance. */
    constructor($$source: Partial<RestartPolicy> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = RestartPolicyMode.$zero;
        }
        if (!("MaximumRetryCount" in $$source)) {
            this["MaximumRetryCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RestartPolicy instance from a string or object.
     */
    static createFrom($$source: any = {}): RestartPolicy {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RestartPolicy($$parsedSource as Partial<RestartPolicy>);
    }
}

export enum RestartPolicyMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RestartPolicyDisabled = "no",
    RestartPolicyAlways = "always",
    RestartPolicyOnFailure = "on-failure",
    RestartPolicyUnlessStopped = "unless-stopped",
};

/**
 * State stores container's running state
 * it's part of ContainerJSONBase and returned by "inspect" command
 */
export class State {
    /**
     * String representation of the container state. Can be one of "created", "running", "paused", "restarting", "removing", "exited", or "dead"
     */
    "Status": ContainerState;
    "Running": boolean;
    "Paused": boolean;
    "Restarting": boolean;
    "OOMKilled": boolean;
    "Dead": boolean;
    "Pid": number;
    "ExitCode": number;
    "Error": string;
    "StartedAt": string;
    "FinishedAt": string;
    "Health"?: Health | null;

    /** Creates a new State instance. */
    constructor($$source: Partial<State> = {}) {
        if (!("Status" in $$source)) {
            this["Status"] = ContainerState.$zero;
        }
        if (!("Running" in $$source)) {
            this["Running"] = false;
        }
        if (!("Paused" in $$source)) {
            this["Paused"] = false;
        }
        if (!("Restarting" in $$source)) {
            this["Restarting"] = false;
        }
        if (!("OOMKilled" in $$source)) {
            this["OOMKilled"] = false;
        }
        if (!("Dead" in $$source)) {
            this["Dead"] = false;
        }
        if (!("Pid" in $$source)) {
            this["Pid"] = 0;
        }
        if (!("ExitCode" in $$source)) {
            this["ExitCode"] = 0;
        }
        if (!("Error" in $$source)) {
            this["Error"] = "";
        }
        if (!("StartedAt" in $$source)) {
            this["StartedAt"] = "";
        }
        if (!("FinishedAt" in $$source)) {
            this["FinishedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     */
    static createFrom($$source: any = {}): State {
        const $$createField11_0 = $$createType51;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Health" in $$parsedSource) {
            $$parsedSource["Health"] = $$createField11_0($$parsedSource["Health"]);
        }
        return new State($$parsedSource as Partial<State>);
    }
}

/**
 * Summary contains response of Engine API:
 * GET "/containers/json"
 */
export class Summary {
    "Id": string;
    "Names": string[];
    "Image": string;
    "ImageID": string;
    "ImageManifestDescriptor"?: v1$1.Descriptor | null;
    "Command": string;
    "Created": number;
    "Ports": PortSummary[];
    "SizeRw"?: number;
    "SizeRootFs"?: number;
    "Labels": { [_: string]: string };
    "State": ContainerState;
    "Status": string;
    "HostConfig": {"NetworkMode"?: string, "Annotations"?: { [_: string]: string }};
    "Health"?: HealthSummary | null;
    "NetworkSettings": NetworkSettingsSummary | null;
    "Mounts": MountPoint[];

    /** Creates a new Summary instance. */
    constructor($$source: Partial<Summary> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Names" in $$source)) {
            this["Names"] = [];
        }
        if (!("Image" in $$source)) {
            this["Image"] = "";
        }
        if (!("ImageID" in $$source)) {
            this["ImageID"] = "";
        }
        if (!("Command" in $$source)) {
            this["Command"] = "";
        }
        if (!("Created" in $$source)) {
            this["Created"] = 0;
        }
        if (!("Ports" in $$source)) {
            this["Ports"] = [];
        }
        if (!("Labels" in $$source)) {
            this["Labels"] = {};
        }
        if (!("State" in $$source)) {
            this["State"] = ContainerState.$zero;
        }
        if (!("Status" in $$source)) {
            this["Status"] = "";
        }
        if (!("HostConfig" in $$source)) {
            this["HostConfig"] = {};
        }
        if (!("NetworkSettings" in $$source)) {
            this["NetworkSettings"] = null;
        }
        if (!("Mounts" in $$source)) {
            this["Mounts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     */
    static createFrom($$source: any = {}): Summary {
        const $$createField1_0 = $$createType1;
        const $$createField4_0 = $$createType46;
        const $$createField7_0 = $$createType53;
        const $$createField10_0 = $$createType5;
        const $$createField13_0 = $$createType54;
        const $$createField14_0 = $$createType56;
        const $$createField15_0 = $$createType58;
        const $$createField16_0 = $$createType40;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Names" in $$parsedSource) {
            $$parsedSource["Names"] = $$createField1_0($$parsedSource["Names"]);
        }
        if ("ImageManifestDescriptor" in $$parsedSource) {
            $$parsedSource["ImageManifestDescriptor"] = $$createField4_0($$parsedSource["ImageManifestDescriptor"]);
        }
        if ("Ports" in $$parsedSource) {
            $$parsedSource["Ports"] = $$createField7_0($$parsedSource["Ports"]);
        }
        if ("Labels" in $$parsedSource) {
            $$parsedSource["Labels"] = $$createField10_0($$parsedSource["Labels"]);
        }
        if ("HostConfig" in $$parsedSource) {
            $$parsedSource["HostConfig"] = $$createField13_0($$parsedSource["HostConfig"]);
        }
        if ("Health" in $$parsedSource) {
            $$parsedSource["Health"] = $$createField14_0($$parsedSource["Health"]);
        }
        if ("NetworkSettings" in $$parsedSource) {
            $$parsedSource["NetworkSettings"] = $$createField15_0($$parsedSource["NetworkSettings"]);
        }
        if ("Mounts" in $$parsedSource) {
            $$parsedSource["Mounts"] = $$createField16_0($$parsedSource["Mounts"]);
        }
        return new Summary($$parsedSource as Partial<Summary>);
    }
}

/**
 * UTSMode represents the UTS namespace of the container.
 */
export type UTSMode = string;

/**
 * Ulimit is an alias for [units.Ulimit], which may be moving to a different
 * location or become a local type. This alias is to help transitioning.
 * 
 * Users are recommended to use this alias instead of using [units.Ulimit] directly.
 */
export const Ulimit = units$0.Ulimit;

/**
 * Ulimit is an alias for [units.Ulimit], which may be moving to a different
 * location or become a local type. This alias is to help transitioning.
 * 
 * Users are recommended to use this alias instead of using [units.Ulimit] directly.
 */
export type Ulimit = units$0.Ulimit;

/**
 * UsernsMode represents userns mode in the container.
 */
export type UsernsMode = string;

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = v1$0.HealthcheckConfig.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = $Create.Array($$createType1);
const $$createType7 = HealthcheckResult.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = LogConfig.createFrom;
const $$createType11 = network$0.PortBinding.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $Create.Map($Create.Any, $$createType12);
const $$createType14 = RestartPolicy.createFrom;
const $$createType15 = $Create.Array($Create.Any);
const $$createType16 = blkiodev$0.WeightDevice.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = blkiodev$0.ThrottleDevice.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = DeviceMapping.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = DeviceRequest.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = units$0.Ulimit.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = mount$0.Mount.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = State.createFrom;
const $$createType32 = $Create.Nullable($$createType31);
const $$createType33 = HostConfig.createFrom;
const $$createType34 = $Create.Nullable($$createType33);
const $$createType35 = storage$0.DriverData.createFrom;
const $$createType36 = $Create.Nullable($$createType35);
const $$createType37 = storage$0.Storage.createFrom;
const $$createType38 = $Create.Nullable($$createType37);
const $$createType39 = MountPoint.createFrom;
const $$createType40 = $Create.Array($$createType39);
const $$createType41 = Config.createFrom;
const $$createType42 = $Create.Nullable($$createType41);
const $$createType43 = NetworkSettings.createFrom;
const $$createType44 = $Create.Nullable($$createType43);
const $$createType45 = v1$1.Descriptor.createFrom;
const $$createType46 = $Create.Nullable($$createType45);
const $$createType47 = network$0.EndpointSettings.createFrom;
const $$createType48 = $Create.Nullable($$createType47);
const $$createType49 = $Create.Map($Create.Any, $$createType48);
const $$createType50 = Health.createFrom;
const $$createType51 = $Create.Nullable($$createType50);
const $$createType52 = PortSummary.createFrom;
const $$createType53 = $Create.Array($$createType52);
const $$createType54 = $Create.Struct({
    "Annotations": $$createType5,
});
const $$createType55 = HealthSummary.createFrom;
const $$createType56 = $Create.Nullable($$createType55);
const $$createType57 = NetworkSettingsSummary.createFrom;
const $$createType58 = $Create.Nullable($$createType57);
