// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mount$0 from "../mount/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as network$0 from "../network/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as v1$0 from "../../../../../opencontainers/image-spec/specs-go/v1/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as netip$0 from "../../../../../../net/netip/models.js";

/**
 * ContainerState is a string representation of the container's current state.
 */
export enum ContainerState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * StateCreated indicates the container is created, but not (yet) started.
     */
    StateCreated = "created",

    /**
     * StateRunning indicates that the container is running.
     */
    StateRunning = "running",

    /**
     * StatePaused indicates that the container's current state is paused.
     */
    StatePaused = "paused",

    /**
     * StateRestarting indicates that the container is currently restarting.
     */
    StateRestarting = "restarting",

    /**
     * StateRemoving indicates that the container is being removed.
     */
    StateRemoving = "removing",

    /**
     * StateExited indicates that the container exited.
     */
    StateExited = "exited",

    /**
     * StateDead indicates that the container failed to be deleted. Containers in this state are attempted to be cleaned up when the daemon restarts.
     */
    StateDead = "dead",
};

/**
 * HealthStatus is a string representation of the container's health.
 */
export enum HealthStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Health states
     *
     * Indicates there is no healthcheck
     */
    NoHealthcheck = "none",

    /**
     * Starting indicates that the container is not yet ready
     */
    Starting = "starting",

    /**
     * Healthy indicates that the container is running correctly
     */
    Healthy = "healthy",

    /**
     * Unhealthy indicates that the container has a problem
     */
    Unhealthy = "unhealthy",
};

/**
 * HealthSummary stores a summary of the container's healthcheck results.
 */
export class HealthSummary {
    /**
     * Status is one of [NoHealthcheck], [Starting], [Healthy] or [Unhealthy].
     */
    "Status": HealthStatus;

    /**
     * FailingStreak is the number of consecutive failures
     */
    "FailingStreak": number;

    /** Creates a new HealthSummary instance. */
    constructor($$source: Partial<HealthSummary> = {}) {
        if (!("Status" in $$source)) {
            this["Status"] = HealthStatus.$zero;
        }
        if (!("FailingStreak" in $$source)) {
            this["FailingStreak"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HealthSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): HealthSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HealthSummary($$parsedSource as Partial<HealthSummary>);
    }
}

/**
 * MountPoint represents a mount point configuration inside the container.
 * This is used for reporting the mountpoints in use by a container.
 */
export class MountPoint {
    /**
     * Type is the type of mount, see [mount.Type] definitions for details.
     */
    "Type"?: mount$0.Type;

    /**
     * Name is the name reference to the underlying data defined by `Source`
     * e.g., the volume name.
     */
    "Name"?: string;

    /**
     * Source is the source location of the mount.
     * 
     * For volumes, this contains the storage location of the volume (within
     * `/var/lib/docker/volumes/`). For bind-mounts, and `npipe`, this contains
     * the source (host) part of the bind-mount. For `tmpfs` mount points, this
     * field is empty.
     */
    "Source": string;

    /**
     * Destination is the path relative to the container root (`/`) where the
     * Source is mounted inside the container.
     */
    "Destination": string;

    /**
     * Driver is the volume driver used to create the volume (if it is a volume).
     */
    "Driver"?: string;

    /**
     * Mode is a comma separated list of options supplied by the user when
     * creating the bind/volume mount.
     * 
     * The default is platform-specific (`"z"` on Linux, empty on Windows).
     */
    "Mode": string;

    /**
     * RW indicates whether the mount is mounted writable (read-write).
     */
    "RW": boolean;

    /**
     * Propagation describes how mounts are propagated from the host into the
     * mount point, and vice-versa. Refer to the Linux kernel documentation
     * for details:
     * https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt
     * 
     * This field is not used on Windows.
     */
    "Propagation": mount$0.Propagation;

    /** Creates a new MountPoint instance. */
    constructor($$source: Partial<MountPoint> = {}) {
        if (!("Source" in $$source)) {
            this["Source"] = "";
        }
        if (!("Destination" in $$source)) {
            this["Destination"] = "";
        }
        if (!("Mode" in $$source)) {
            this["Mode"] = "";
        }
        if (!("RW" in $$source)) {
            this["RW"] = false;
        }
        if (!("Propagation" in $$source)) {
            this["Propagation"] = mount$0.Propagation.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MountPoint instance from a string or object.
     */
    static createFrom($$source: any = {}): MountPoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MountPoint($$parsedSource as Partial<MountPoint>);
    }
}

/**
 * NetworkSettingsSummary provides a summary of container's networks
 * in /containers/json
 */
export class NetworkSettingsSummary {
    "Networks": { [_: string]: network$0.EndpointSettings | null };

    /** Creates a new NetworkSettingsSummary instance. */
    constructor($$source: Partial<NetworkSettingsSummary> = {}) {
        if (!("Networks" in $$source)) {
            this["Networks"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkSettingsSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): NetworkSettingsSummary {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Networks" in $$parsedSource) {
            $$parsedSource["Networks"] = $$createField0_0($$parsedSource["Networks"]);
        }
        return new NetworkSettingsSummary($$parsedSource as Partial<NetworkSettingsSummary>);
    }
}

/**
 * PortSummary Describes a port-mapping between the container and the host.
 * 
 * Example: {"PrivatePort":8080,"PublicPort":80,"Type":"tcp"}
 * 
 * swagger:model PortSummary
 */
export class PortSummary {
    /**
     * Host IP address that the container's port is mapped to
     */
    "IP"?: netip$0.Addr;

    /**
     * Port on the container
     * Required: true
     */
    "PrivatePort": number;

    /**
     * Port exposed on the host
     */
    "PublicPort"?: number;

    /**
     * type
     * Required: true
     * Enum: ["tcp","udp","sctp"]
     */
    "Type": string;

    /** Creates a new PortSummary instance. */
    constructor($$source: Partial<PortSummary> = {}) {
        if (!("PrivatePort" in $$source)) {
            this["PrivatePort"] = 0;
        }
        if (!("Type" in $$source)) {
            this["Type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): PortSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortSummary($$parsedSource as Partial<PortSummary>);
    }
}

/**
 * Summary contains response of Engine API:
 * GET "/containers/json"
 */
export class Summary {
    "Id": string;
    "Names": string[];
    "Image": string;
    "ImageID": string;
    "ImageManifestDescriptor"?: v1$0.Descriptor | null;
    "Command": string;
    "Created": number;
    "Ports": PortSummary[];
    "SizeRw"?: number;
    "SizeRootFs"?: number;
    "Labels": { [_: string]: string };
    "State": ContainerState;
    "Status": string;
    "HostConfig": {"NetworkMode"?: string, "Annotations"?: { [_: string]: string }};
    "Health"?: HealthSummary | null;
    "NetworkSettings": NetworkSettingsSummary | null;
    "Mounts": MountPoint[];

    /** Creates a new Summary instance. */
    constructor($$source: Partial<Summary> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Names" in $$source)) {
            this["Names"] = [];
        }
        if (!("Image" in $$source)) {
            this["Image"] = "";
        }
        if (!("ImageID" in $$source)) {
            this["ImageID"] = "";
        }
        if (!("Command" in $$source)) {
            this["Command"] = "";
        }
        if (!("Created" in $$source)) {
            this["Created"] = 0;
        }
        if (!("Ports" in $$source)) {
            this["Ports"] = [];
        }
        if (!("Labels" in $$source)) {
            this["Labels"] = {};
        }
        if (!("State" in $$source)) {
            this["State"] = ContainerState.$zero;
        }
        if (!("Status" in $$source)) {
            this["Status"] = "";
        }
        if (!("HostConfig" in $$source)) {
            this["HostConfig"] = {};
        }
        if (!("NetworkSettings" in $$source)) {
            this["NetworkSettings"] = null;
        }
        if (!("Mounts" in $$source)) {
            this["Mounts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     */
    static createFrom($$source: any = {}): Summary {
        const $$createField1_0 = $$createType3;
        const $$createField4_0 = $$createType5;
        const $$createField7_0 = $$createType7;
        const $$createField10_0 = $$createType8;
        const $$createField13_0 = $$createType9;
        const $$createField14_0 = $$createType11;
        const $$createField15_0 = $$createType13;
        const $$createField16_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Names" in $$parsedSource) {
            $$parsedSource["Names"] = $$createField1_0($$parsedSource["Names"]);
        }
        if ("ImageManifestDescriptor" in $$parsedSource) {
            $$parsedSource["ImageManifestDescriptor"] = $$createField4_0($$parsedSource["ImageManifestDescriptor"]);
        }
        if ("Ports" in $$parsedSource) {
            $$parsedSource["Ports"] = $$createField7_0($$parsedSource["Ports"]);
        }
        if ("Labels" in $$parsedSource) {
            $$parsedSource["Labels"] = $$createField10_0($$parsedSource["Labels"]);
        }
        if ("HostConfig" in $$parsedSource) {
            $$parsedSource["HostConfig"] = $$createField13_0($$parsedSource["HostConfig"]);
        }
        if ("Health" in $$parsedSource) {
            $$parsedSource["Health"] = $$createField14_0($$parsedSource["Health"]);
        }
        if ("NetworkSettings" in $$parsedSource) {
            $$parsedSource["NetworkSettings"] = $$createField15_0($$parsedSource["NetworkSettings"]);
        }
        if ("Mounts" in $$parsedSource) {
            $$parsedSource["Mounts"] = $$createField16_0($$parsedSource["Mounts"]);
        }
        return new Summary($$parsedSource as Partial<Summary>);
    }
}

// Private type creation functions
const $$createType0 = network$0.EndpointSettings.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = v1$0.Descriptor.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = PortSummary.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Map($Create.Any, $Create.Any);
const $$createType9 = $Create.Struct({
    "Annotations": $$createType8,
});
const $$createType10 = HealthSummary.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = NetworkSettingsSummary.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = MountPoint.createFrom;
const $$createType15 = $Create.Array($$createType14);
