// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mount$0 from "../mount/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as network$0 from "../network/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as v1$0 from "../../../../../opencontainers/image-spec/specs-go/v1/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as netip$0 from "../../../../../../net/netip/models.js";

/**
 * ContainerState is a string representation of the container's current state.
 * @readonly
 * @enum {string}
 */
export const ContainerState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * StateCreated indicates the container is created, but not (yet) started.
     */
    StateCreated: "created",

    /**
     * StateRunning indicates that the container is running.
     */
    StateRunning: "running",

    /**
     * StatePaused indicates that the container's current state is paused.
     */
    StatePaused: "paused",

    /**
     * StateRestarting indicates that the container is currently restarting.
     */
    StateRestarting: "restarting",

    /**
     * StateRemoving indicates that the container is being removed.
     */
    StateRemoving: "removing",

    /**
     * StateExited indicates that the container exited.
     */
    StateExited: "exited",

    /**
     * StateDead indicates that the container failed to be deleted. Containers in this state are attempted to be cleaned up when the daemon restarts.
     */
    StateDead: "dead",
};

/**
 * HealthStatus is a string representation of the container's health.
 * @readonly
 * @enum {string}
 */
export const HealthStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * Health states
     *
     * Indicates there is no healthcheck
     */
    NoHealthcheck: "none",

    /**
     * Starting indicates that the container is not yet ready
     */
    Starting: "starting",

    /**
     * Healthy indicates that the container is running correctly
     */
    Healthy: "healthy",

    /**
     * Unhealthy indicates that the container has a problem
     */
    Unhealthy: "unhealthy",
};

/**
 * HealthSummary stores a summary of the container's healthcheck results.
 */
export class HealthSummary {
    /**
     * Creates a new HealthSummary instance.
     * @param {Partial<HealthSummary>} [$$source = {}] - The source object to create the HealthSummary.
     */
    constructor($$source = {}) {
        if (!("Status" in $$source)) {
            /**
             * Status is one of [NoHealthcheck], [Starting], [Healthy] or [Unhealthy].
             * @member
             * @type {HealthStatus}
             */
            this["Status"] = HealthStatus.$zero;
        }
        if (!("FailingStreak" in $$source)) {
            /**
             * FailingStreak is the number of consecutive failures
             * @member
             * @type {number}
             */
            this["FailingStreak"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HealthSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HealthSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HealthSummary(/** @type {Partial<HealthSummary>} */($$parsedSource));
    }
}

/**
 * MountPoint represents a mount point configuration inside the container.
 * This is used for reporting the mountpoints in use by a container.
 */
export class MountPoint {
    /**
     * Creates a new MountPoint instance.
     * @param {Partial<MountPoint>} [$$source = {}] - The source object to create the MountPoint.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * Type is the type of mount, see [mount.Type] definitions for details.
             * @member
             * @type {mount$0.Type | undefined}
             */
            this["Type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Name is the name reference to the underlying data defined by `Source`
             * e.g., the volume name.
             * @member
             * @type {string | undefined}
             */
            this["Name"] = undefined;
        }
        if (!("Source" in $$source)) {
            /**
             * Source is the source location of the mount.
             * 
             * For volumes, this contains the storage location of the volume (within
             * `/var/lib/docker/volumes/`). For bind-mounts, and `npipe`, this contains
             * the source (host) part of the bind-mount. For `tmpfs` mount points, this
             * field is empty.
             * @member
             * @type {string}
             */
            this["Source"] = "";
        }
        if (!("Destination" in $$source)) {
            /**
             * Destination is the path relative to the container root (`/`) where the
             * Source is mounted inside the container.
             * @member
             * @type {string}
             */
            this["Destination"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Driver is the volume driver used to create the volume (if it is a volume).
             * @member
             * @type {string | undefined}
             */
            this["Driver"] = undefined;
        }
        if (!("Mode" in $$source)) {
            /**
             * Mode is a comma separated list of options supplied by the user when
             * creating the bind/volume mount.
             * 
             * The default is platform-specific (`"z"` on Linux, empty on Windows).
             * @member
             * @type {string}
             */
            this["Mode"] = "";
        }
        if (!("RW" in $$source)) {
            /**
             * RW indicates whether the mount is mounted writable (read-write).
             * @member
             * @type {boolean}
             */
            this["RW"] = false;
        }
        if (!("Propagation" in $$source)) {
            /**
             * Propagation describes how mounts are propagated from the host into the
             * mount point, and vice-versa. Refer to the Linux kernel documentation
             * for details:
             * https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt
             * 
             * This field is not used on Windows.
             * @member
             * @type {mount$0.Propagation}
             */
            this["Propagation"] = mount$0.Propagation.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MountPoint instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MountPoint}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MountPoint(/** @type {Partial<MountPoint>} */($$parsedSource));
    }
}

/**
 * NetworkSettingsSummary provides a summary of container's networks
 * in /containers/json
 */
export class NetworkSettingsSummary {
    /**
     * Creates a new NetworkSettingsSummary instance.
     * @param {Partial<NetworkSettingsSummary>} [$$source = {}] - The source object to create the NetworkSettingsSummary.
     */
    constructor($$source = {}) {
        if (!("Networks" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: network$0.EndpointSettings | null }}
             */
            this["Networks"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkSettingsSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NetworkSettingsSummary}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Networks" in $$parsedSource) {
            $$parsedSource["Networks"] = $$createField0_0($$parsedSource["Networks"]);
        }
        return new NetworkSettingsSummary(/** @type {Partial<NetworkSettingsSummary>} */($$parsedSource));
    }
}

/**
 * PortSummary Describes a port-mapping between the container and the host.
 * 
 * Example: {"PrivatePort":8080,"PublicPort":80,"Type":"tcp"}
 * 
 * swagger:model PortSummary
 */
export class PortSummary {
    /**
     * Creates a new PortSummary instance.
     * @param {Partial<PortSummary>} [$$source = {}] - The source object to create the PortSummary.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * Host IP address that the container's port is mapped to
             * @member
             * @type {netip$0.Addr | undefined}
             */
            this["IP"] = undefined;
        }
        if (!("PrivatePort" in $$source)) {
            /**
             * Port on the container
             * Required: true
             * @member
             * @type {number}
             */
            this["PrivatePort"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * Port exposed on the host
             * @member
             * @type {number | undefined}
             */
            this["PublicPort"] = undefined;
        }
        if (!("Type" in $$source)) {
            /**
             * type
             * Required: true
             * Enum: ["tcp","udp","sctp"]
             * @member
             * @type {string}
             */
            this["Type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PortSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortSummary(/** @type {Partial<PortSummary>} */($$parsedSource));
    }
}

/**
 * Summary contains response of Engine API:
 * GET "/containers/json"
 */
export class Summary {
    /**
     * Creates a new Summary instance.
     * @param {Partial<Summary>} [$$source = {}] - The source object to create the Summary.
     */
    constructor($$source = {}) {
        if (!("Id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Id"] = "";
        }
        if (!("Names" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["Names"] = [];
        }
        if (!("Image" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Image"] = "";
        }
        if (!("ImageID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ImageID"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {v1$0.Descriptor | null | undefined}
             */
            this["ImageManifestDescriptor"] = undefined;
        }
        if (!("Command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Command"] = "";
        }
        if (!("Created" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Created"] = 0;
        }
        if (!("Ports" in $$source)) {
            /**
             * @member
             * @type {PortSummary[]}
             */
            this["Ports"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["SizeRw"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["SizeRootFs"] = undefined;
        }
        if (!("Labels" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: string }}
             */
            this["Labels"] = {};
        }
        if (!("State" in $$source)) {
            /**
             * @member
             * @type {ContainerState}
             */
            this["State"] = ContainerState.$zero;
        }
        if (!("Status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Status"] = "";
        }
        if (!("HostConfig" in $$source)) {
            /**
             * @member
             * @type {{"NetworkMode"?: string, "Annotations"?: { [_: string]: string }}}
             */
            this["HostConfig"] = {};
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {HealthSummary | null | undefined}
             */
            this["Health"] = undefined;
        }
        if (!("NetworkSettings" in $$source)) {
            /**
             * @member
             * @type {NetworkSettingsSummary | null}
             */
            this["NetworkSettings"] = null;
        }
        if (!("Mounts" in $$source)) {
            /**
             * @member
             * @type {MountPoint[]}
             */
            this["Mounts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Summary}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType3;
        const $$createField4_0 = $$createType5;
        const $$createField7_0 = $$createType7;
        const $$createField10_0 = $$createType8;
        const $$createField13_0 = $$createType9;
        const $$createField14_0 = $$createType11;
        const $$createField15_0 = $$createType13;
        const $$createField16_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Names" in $$parsedSource) {
            $$parsedSource["Names"] = $$createField1_0($$parsedSource["Names"]);
        }
        if ("ImageManifestDescriptor" in $$parsedSource) {
            $$parsedSource["ImageManifestDescriptor"] = $$createField4_0($$parsedSource["ImageManifestDescriptor"]);
        }
        if ("Ports" in $$parsedSource) {
            $$parsedSource["Ports"] = $$createField7_0($$parsedSource["Ports"]);
        }
        if ("Labels" in $$parsedSource) {
            $$parsedSource["Labels"] = $$createField10_0($$parsedSource["Labels"]);
        }
        if ("HostConfig" in $$parsedSource) {
            $$parsedSource["HostConfig"] = $$createField13_0($$parsedSource["HostConfig"]);
        }
        if ("Health" in $$parsedSource) {
            $$parsedSource["Health"] = $$createField14_0($$parsedSource["Health"]);
        }
        if ("NetworkSettings" in $$parsedSource) {
            $$parsedSource["NetworkSettings"] = $$createField15_0($$parsedSource["NetworkSettings"]);
        }
        if ("Mounts" in $$parsedSource) {
            $$parsedSource["Mounts"] = $$createField16_0($$parsedSource["Mounts"]);
        }
        return new Summary(/** @type {Partial<Summary>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = network$0.EndpointSettings.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = v1$0.Descriptor.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = PortSummary.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Map($Create.Any, $Create.Any);
const $$createType9 = $Create.Struct({
    "Annotations": $$createType8,
});
const $$createType10 = HealthSummary.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = NetworkSettingsSummary.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = MountPoint.createFrom;
const $$createType15 = $Create.Array($$createType14);
