// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as digest$0 from "../../../../../opencontainers/go-digest/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as v1$0 from "../../../../../opencontainers/image-spec/specs-go/v1/models.js";

export class AttestationProperties {
    /**
     * For is the digest of the image manifest that this attestation is for.
     */
    "For": digest$0.Digest;

    /** Creates a new AttestationProperties instance. */
    constructor($$source: Partial<AttestationProperties> = {}) {
        if (!("For" in $$source)) {
            this["For"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AttestationProperties instance from a string or object.
     */
    static createFrom($$source: any = {}): AttestationProperties {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AttestationProperties($$parsedSource as Partial<AttestationProperties>);
    }
}

export class ImageProperties {
    /**
     * Platform is the OCI platform object describing the platform of the image.
     * 
     * Required: true
     */
    "Platform": v1$0.Platform;
    "Size": {"Unpacked": number};

    /**
     * Containers is an array containing the IDs of the containers that are
     * using this image.
     * 
     * Required: true
     */
    "Containers": string[];

    /** Creates a new ImageProperties instance. */
    constructor($$source: Partial<ImageProperties> = {}) {
        if (!("Platform" in $$source)) {
            this["Platform"] = (new v1$0.Platform());
        }
        if (!("Size" in $$source)) {
            this["Size"] = {"Unpacked": 0};
        }
        if (!("Containers" in $$source)) {
            this["Containers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImageProperties instance from a string or object.
     */
    static createFrom($$source: any = {}): ImageProperties {
        const $$createField0_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Platform" in $$parsedSource) {
            $$parsedSource["Platform"] = $$createField0_0($$parsedSource["Platform"]);
        }
        if ("Containers" in $$parsedSource) {
            $$parsedSource["Containers"] = $$createField2_0($$parsedSource["Containers"]);
        }
        return new ImageProperties($$parsedSource as Partial<ImageProperties>);
    }
}

export enum ManifestKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ManifestKindImage = "image",
    ManifestKindAttestation = "attestation",
    ManifestKindUnknown = "unknown",
};

export class ManifestSummary {
    /**
     * ID is the content-addressable ID of an image and is the same as the
     * digest of the image manifest.
     * 
     * Required: true
     */
    "ID": string;

    /**
     * Descriptor is the OCI descriptor of the image.
     * 
     * Required: true
     */
    "Descriptor": v1$0.Descriptor;

    /**
     * Indicates whether all the child content (image config, layers) is
     * fully available locally
     * 
     * Required: true
     */
    "Available": boolean;

    /**
     * Size is the size information of the content related to this manifest.
     * Note: These sizes only take the locally available content into account.
     * 
     * Required: true
     */
    "Size": {"Content": number, "Total": number};

    /**
     * Kind is the kind of the image manifest.
     * 
     * Required: true
     */
    "Kind": ManifestKind;

    /**
     * Present only if Kind == ManifestKindImage.
     */
    "ImageData"?: ImageProperties | null;

    /**
     * Present only if Kind == ManifestKindAttestation.
     */
    "AttestationData"?: AttestationProperties | null;

    /** Creates a new ManifestSummary instance. */
    constructor($$source: Partial<ManifestSummary> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Descriptor" in $$source)) {
            this["Descriptor"] = (new v1$0.Descriptor());
        }
        if (!("Available" in $$source)) {
            this["Available"] = false;
        }
        if (!("Size" in $$source)) {
            this["Size"] = {"Content": 0, "Total": 0};
        }
        if (!("Kind" in $$source)) {
            this["Kind"] = ManifestKind.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManifestSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ManifestSummary {
        const $$createField1_0 = $$createType2;
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Descriptor" in $$parsedSource) {
            $$parsedSource["Descriptor"] = $$createField1_0($$parsedSource["Descriptor"]);
        }
        if ("ImageData" in $$parsedSource) {
            $$parsedSource["ImageData"] = $$createField5_0($$parsedSource["ImageData"]);
        }
        if ("AttestationData" in $$parsedSource) {
            $$parsedSource["AttestationData"] = $$createField6_0($$parsedSource["AttestationData"]);
        }
        return new ManifestSummary($$parsedSource as Partial<ManifestSummary>);
    }
}

export class Summary {
    /**
     * Number of containers using this image. Includes both stopped and running
     * containers.
     * 
     * This size is not calculated by default, and depends on which API endpoint
     * is used. `-1` indicates that the value has not been set / calculated.
     * 
     * Required: true
     */
    "Containers": number;

    /**
     * Date and time at which the image was created as a Unix timestamp
     * (number of seconds since EPOCH).
     * 
     * Required: true
     */
    "Created": number;

    /**
     * ID is the content-addressable ID of an image.
     * 
     * This identifier is a content-addressable digest calculated from the
     * image's configuration (which includes the digests of layers used by
     * the image).
     * 
     * Note that this digest differs from the `RepoDigests` below, which
     * holds digests of image manifests that reference the image.
     * 
     * Required: true
     */
    "Id": string;

    /**
     * User-defined key/value metadata.
     * Required: true
     */
    "Labels": { [_: string]: string };

    /**
     * ID of the parent image.
     * 
     * Depending on how the image was created, this field may be empty and
     * is only set for images that were built/created locally. This field
     * is empty if the image was pulled from an image registry.
     * 
     * Required: true
     */
    "ParentId": string;

    /**
     * Descriptor is the OCI descriptor of the image target.
     * It's only set if the daemon provides a multi-platform image store.
     * 
     * WARNING: This is experimental and may change at any time without any backward
     * compatibility.
     */
    "Descriptor"?: v1$0.Descriptor | null;

    /**
     * Manifests is a list of image manifests available in this image.  It
     * provides a more detailed view of the platform-specific image manifests or
     * other image-attached data like build attestations.
     * 
     * WARNING: This is experimental and may change at any time without any backward
     * compatibility.
     */
    "Manifests"?: ManifestSummary[];

    /**
     * List of content-addressable digests of locally available image manifests
     * that the image is referenced from. Multiple manifests can refer to the
     * same image.
     * 
     * These digests are usually only available if the image was either pulled
     * from a registry, or if the image was pushed to a registry, which is when
     * the manifest is generated and its digest calculated.
     * 
     * Required: true
     */
    "RepoDigests": string[];

    /**
     * List of image names/tags in the local image cache that reference this
     * image.
     * 
     * Multiple image tags can refer to the same image, and this list may be
     * empty if no tags reference the image, in which case the image is
     * "untagged", in which case it can still be referenced by its ID.
     * 
     * Required: true
     */
    "RepoTags": string[];

    /**
     * Total size of image layers that are shared between this image and other
     * images.
     * 
     * This size is not calculated by default. `-1` indicates that the value
     * has not been set / calculated.
     * 
     * Required: true
     */
    "SharedSize": number;

    /**
     * Total size of the image including all layers it is composed of.
     * 
     * Required: true
     */
    "Size": number;

    /** Creates a new Summary instance. */
    constructor($$source: Partial<Summary> = {}) {
        if (!("Containers" in $$source)) {
            this["Containers"] = 0;
        }
        if (!("Created" in $$source)) {
            this["Created"] = 0;
        }
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Labels" in $$source)) {
            this["Labels"] = {};
        }
        if (!("ParentId" in $$source)) {
            this["ParentId"] = "";
        }
        if (!("RepoDigests" in $$source)) {
            this["RepoDigests"] = [];
        }
        if (!("RepoTags" in $$source)) {
            this["RepoTags"] = [];
        }
        if (!("SharedSize" in $$source)) {
            this["SharedSize"] = 0;
        }
        if (!("Size" in $$source)) {
            this["Size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     */
    static createFrom($$source: any = {}): Summary {
        const $$createField3_0 = $$createType7;
        const $$createField5_0 = $$createType8;
        const $$createField6_0 = $$createType10;
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Labels" in $$parsedSource) {
            $$parsedSource["Labels"] = $$createField3_0($$parsedSource["Labels"]);
        }
        if ("Descriptor" in $$parsedSource) {
            $$parsedSource["Descriptor"] = $$createField5_0($$parsedSource["Descriptor"]);
        }
        if ("Manifests" in $$parsedSource) {
            $$parsedSource["Manifests"] = $$createField6_0($$parsedSource["Manifests"]);
        }
        if ("RepoDigests" in $$parsedSource) {
            $$parsedSource["RepoDigests"] = $$createField7_0($$parsedSource["RepoDigests"]);
        }
        if ("RepoTags" in $$parsedSource) {
            $$parsedSource["RepoTags"] = $$createField8_0($$parsedSource["RepoTags"]);
        }
        return new Summary($$parsedSource as Partial<Summary>);
    }
}

// Private type creation functions
const $$createType0 = v1$0.Platform.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = v1$0.Descriptor.createFrom;
const $$createType3 = ImageProperties.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = AttestationProperties.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
const $$createType8 = $Create.Nullable($$createType2);
const $$createType9 = ManifestSummary.createFrom;
const $$createType10 = $Create.Array($$createType9);
