// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as v1$1 from "../../../../docker-image-spec/specs-go/v1/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as digest$0 from "../../../../../opencontainers/go-digest/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as v1$0 from "../../../../../opencontainers/image-spec/specs-go/v1/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

export class AttestationProperties {
    /**
     * For is the digest of the image manifest that this attestation is for.
     */
    "For": digest$0.Digest;

    /** Creates a new AttestationProperties instance. */
    constructor($$source: Partial<AttestationProperties> = {}) {
        if (!("For" in $$source)) {
            this["For"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AttestationProperties instance from a string or object.
     */
    static createFrom($$source: any = {}): AttestationProperties {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AttestationProperties($$parsedSource as Partial<AttestationProperties>);
    }
}

export class ImageProperties {
    /**
     * Platform is the OCI platform object describing the platform of the image.
     * 
     * Required: true
     */
    "Platform": v1$0.Platform;
    "Size": {"Unpacked": number};

    /**
     * Containers is an array containing the IDs of the containers that are
     * using this image.
     * 
     * Required: true
     */
    "Containers": string[];

    /** Creates a new ImageProperties instance. */
    constructor($$source: Partial<ImageProperties> = {}) {
        if (!("Platform" in $$source)) {
            this["Platform"] = (new v1$0.Platform());
        }
        if (!("Size" in $$source)) {
            this["Size"] = {"Unpacked": 0};
        }
        if (!("Containers" in $$source)) {
            this["Containers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImageProperties instance from a string or object.
     */
    static createFrom($$source: any = {}): ImageProperties {
        const $$createField0_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Platform" in $$parsedSource) {
            $$parsedSource["Platform"] = $$createField0_0($$parsedSource["Platform"]);
        }
        if ("Containers" in $$parsedSource) {
            $$parsedSource["Containers"] = $$createField2_0($$parsedSource["Containers"]);
        }
        return new ImageProperties($$parsedSource as Partial<ImageProperties>);
    }
}

/**
 * InspectResponse contains response of Engine API:
 * GET "/images/{name:.*}/json"
 */
export class InspectResponse {
    /**
     * ID is the content-addressable ID of an image.
     * 
     * This identifier is a content-addressable digest calculated from the
     * image's configuration (which includes the digests of layers used by
     * the image).
     * 
     * Note that this digest differs from the `RepoDigests` below, which
     * holds digests of image manifests that reference the image.
     */
    "Id": string;

    /**
     * RepoTags is a list of image names/tags in the local image cache that
     * reference this image.
     * 
     * Multiple image tags can refer to the same image, and this list may be
     * empty if no tags reference the image, in which case the image is
     * "untagged", in which case it can still be referenced by its ID.
     */
    "RepoTags": string[];

    /**
     * RepoDigests is a list of content-addressable digests of locally available
     * image manifests that the image is referenced from. Multiple manifests can
     * refer to the same image.
     * 
     * These digests are usually only available if the image was either pulled
     * from a registry, or if the image was pushed to a registry, which is when
     * the manifest is generated and its digest calculated.
     */
    "RepoDigests": string[];

    /**
     * Comment is an optional message that can be set when committing or
     * importing the image. This field is omitted if not set.
     */
    "Comment"?: string;

    /**
     * Created is the date and time at which the image was created, formatted in
     * RFC 3339 nano-seconds (time.RFC3339Nano).
     * 
     * This information is only available if present in the image,
     * and omitted otherwise.
     */
    "Created"?: string;

    /**
     * Author is the name of the author that was specified when committing the
     * image, or as specified through MAINTAINER (deprecated) in the Dockerfile.
     * This field is omitted if not set.
     */
    "Author"?: string;
    "Config": v1$1.DockerOCIImageConfig | null;

    /**
     * Architecture is the hardware CPU architecture that the image runs on.
     */
    "Architecture": string;

    /**
     * Variant is the CPU architecture variant (presently ARM-only).
     */
    "Variant"?: string;

    /**
     * OS is the Operating System the image is built to run on.
     */
    "Os": string;

    /**
     * OsVersion is the version of the Operating System the image is built to
     * run on (especially for Windows).
     */
    "OsVersion"?: string;

    /**
     * Size is the total size of the image including all layers it is composed of.
     */
    "Size": number;

    /**
     * GraphDriver holds information about the storage driver used to store the
     * container's and image's filesystem.
     */
    "GraphDriver"?: storage$0.DriverData | null;

    /**
     * RootFS contains information about the image's RootFS, including the
     * layer IDs.
     */
    "RootFS": RootFS;

    /**
     * Metadata of the image in the local cache.
     * 
     * This information is local to the daemon, and not part of the image itself.
     */
    "Metadata": Metadata;

    /**
     * Descriptor is the OCI descriptor of the image target.
     * It's only set if the daemon provides a multi-platform image store.
     * 
     * WARNING: This is experimental and may change at any time without any backward
     * compatibility.
     */
    "Descriptor"?: v1$0.Descriptor | null;

    /**
     * Manifests is a list of image manifests available in this image. It
     * provides a more detailed view of the platform-specific image manifests or
     * other image-attached data like build attestations.
     * 
     * Only available if the daemon provides a multi-platform image store, the client
     * requests manifests AND does not request a specific platform.
     * 
     * WARNING: This is experimental and may change at any time without any backward
     * compatibility.
     */
    "Manifests"?: ManifestSummary[];

    /** Creates a new InspectResponse instance. */
    constructor($$source: Partial<InspectResponse> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("RepoTags" in $$source)) {
            this["RepoTags"] = [];
        }
        if (!("RepoDigests" in $$source)) {
            this["RepoDigests"] = [];
        }
        if (!("Config" in $$source)) {
            this["Config"] = null;
        }
        if (!("Architecture" in $$source)) {
            this["Architecture"] = "";
        }
        if (!("Os" in $$source)) {
            this["Os"] = "";
        }
        if (!("Size" in $$source)) {
            this["Size"] = 0;
        }
        if (!("RootFS" in $$source)) {
            this["RootFS"] = (new RootFS());
        }
        if (!("Metadata" in $$source)) {
            this["Metadata"] = (new Metadata());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InspectResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): InspectResponse {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        const $$createField6_0 = $$createType3;
        const $$createField12_0 = $$createType5;
        const $$createField13_0 = $$createType6;
        const $$createField14_0 = $$createType7;
        const $$createField15_0 = $$createType9;
        const $$createField16_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("RepoTags" in $$parsedSource) {
            $$parsedSource["RepoTags"] = $$createField1_0($$parsedSource["RepoTags"]);
        }
        if ("RepoDigests" in $$parsedSource) {
            $$parsedSource["RepoDigests"] = $$createField2_0($$parsedSource["RepoDigests"]);
        }
        if ("Config" in $$parsedSource) {
            $$parsedSource["Config"] = $$createField6_0($$parsedSource["Config"]);
        }
        if ("GraphDriver" in $$parsedSource) {
            $$parsedSource["GraphDriver"] = $$createField12_0($$parsedSource["GraphDriver"]);
        }
        if ("RootFS" in $$parsedSource) {
            $$parsedSource["RootFS"] = $$createField13_0($$parsedSource["RootFS"]);
        }
        if ("Metadata" in $$parsedSource) {
            $$parsedSource["Metadata"] = $$createField14_0($$parsedSource["Metadata"]);
        }
        if ("Descriptor" in $$parsedSource) {
            $$parsedSource["Descriptor"] = $$createField15_0($$parsedSource["Descriptor"]);
        }
        if ("Manifests" in $$parsedSource) {
            $$parsedSource["Manifests"] = $$createField16_0($$parsedSource["Manifests"]);
        }
        return new InspectResponse($$parsedSource as Partial<InspectResponse>);
    }
}

export enum ManifestKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ManifestKindImage = "image",
    ManifestKindAttestation = "attestation",
    ManifestKindUnknown = "unknown",
};

export class ManifestSummary {
    /**
     * ID is the content-addressable ID of an image and is the same as the
     * digest of the image manifest.
     * 
     * Required: true
     */
    "ID": string;

    /**
     * Descriptor is the OCI descriptor of the image.
     * 
     * Required: true
     */
    "Descriptor": v1$0.Descriptor;

    /**
     * Indicates whether all the child content (image config, layers) is
     * fully available locally
     * 
     * Required: true
     */
    "Available": boolean;

    /**
     * Size is the size information of the content related to this manifest.
     * Note: These sizes only take the locally available content into account.
     * 
     * Required: true
     */
    "Size": {"Content": number, "Total": number};

    /**
     * Kind is the kind of the image manifest.
     * 
     * Required: true
     */
    "Kind": ManifestKind;

    /**
     * Present only if Kind == ManifestKindImage.
     */
    "ImageData"?: ImageProperties | null;

    /**
     * Present only if Kind == ManifestKindAttestation.
     */
    "AttestationData"?: AttestationProperties | null;

    /** Creates a new ManifestSummary instance. */
    constructor($$source: Partial<ManifestSummary> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Descriptor" in $$source)) {
            this["Descriptor"] = (new v1$0.Descriptor());
        }
        if (!("Available" in $$source)) {
            this["Available"] = false;
        }
        if (!("Size" in $$source)) {
            this["Size"] = {"Content": 0, "Total": 0};
        }
        if (!("Kind" in $$source)) {
            this["Kind"] = ManifestKind.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManifestSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ManifestSummary {
        const $$createField1_0 = $$createType8;
        const $$createField5_0 = $$createType13;
        const $$createField6_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Descriptor" in $$parsedSource) {
            $$parsedSource["Descriptor"] = $$createField1_0($$parsedSource["Descriptor"]);
        }
        if ("ImageData" in $$parsedSource) {
            $$parsedSource["ImageData"] = $$createField5_0($$parsedSource["ImageData"]);
        }
        if ("AttestationData" in $$parsedSource) {
            $$parsedSource["AttestationData"] = $$createField6_0($$parsedSource["AttestationData"]);
        }
        return new ManifestSummary($$parsedSource as Partial<ManifestSummary>);
    }
}

/**
 * Metadata contains engine-local data about the image.
 */
export class Metadata {
    /**
     * LastTagTime is the date and time at which the image was last tagged.
     */
    "LastTagTime"?: time$0.Time;

    /** Creates a new Metadata instance. */
    constructor($$source: Partial<Metadata> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Metadata instance from a string or object.
     */
    static createFrom($$source: any = {}): Metadata {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Metadata($$parsedSource as Partial<Metadata>);
    }
}

/**
 * RootFS returns Image's RootFS description including the layer IDs.
 */
export class RootFS {
    "Type"?: string;
    "Layers"?: string[];

    /** Creates a new RootFS instance. */
    constructor($$source: Partial<RootFS> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RootFS instance from a string or object.
     */
    static createFrom($$source: any = {}): RootFS {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Layers" in $$parsedSource) {
            $$parsedSource["Layers"] = $$createField1_0($$parsedSource["Layers"]);
        }
        return new RootFS($$parsedSource as Partial<RootFS>);
    }
}

export class Summary {
    /**
     * Number of containers using this image. Includes both stopped and running
     * containers.
     * 
     * This size is not calculated by default, and depends on which API endpoint
     * is used. `-1` indicates that the value has not been set / calculated.
     * 
     * Required: true
     */
    "Containers": number;

    /**
     * Date and time at which the image was created as a Unix timestamp
     * (number of seconds since EPOCH).
     * 
     * Required: true
     */
    "Created": number;

    /**
     * ID is the content-addressable ID of an image.
     * 
     * This identifier is a content-addressable digest calculated from the
     * image's configuration (which includes the digests of layers used by
     * the image).
     * 
     * Note that this digest differs from the `RepoDigests` below, which
     * holds digests of image manifests that reference the image.
     * 
     * Required: true
     */
    "Id": string;

    /**
     * User-defined key/value metadata.
     * Required: true
     */
    "Labels": { [_: string]: string };

    /**
     * ID of the parent image.
     * 
     * Depending on how the image was created, this field may be empty and
     * is only set for images that were built/created locally. This field
     * is empty if the image was pulled from an image registry.
     * 
     * Required: true
     */
    "ParentId": string;

    /**
     * Descriptor is the OCI descriptor of the image target.
     * It's only set if the daemon provides a multi-platform image store.
     * 
     * WARNING: This is experimental and may change at any time without any backward
     * compatibility.
     */
    "Descriptor"?: v1$0.Descriptor | null;

    /**
     * Manifests is a list of image manifests available in this image.  It
     * provides a more detailed view of the platform-specific image manifests or
     * other image-attached data like build attestations.
     * 
     * WARNING: This is experimental and may change at any time without any backward
     * compatibility.
     */
    "Manifests"?: ManifestSummary[];

    /**
     * List of content-addressable digests of locally available image manifests
     * that the image is referenced from. Multiple manifests can refer to the
     * same image.
     * 
     * These digests are usually only available if the image was either pulled
     * from a registry, or if the image was pushed to a registry, which is when
     * the manifest is generated and its digest calculated.
     * 
     * Required: true
     */
    "RepoDigests": string[];

    /**
     * List of image names/tags in the local image cache that reference this
     * image.
     * 
     * Multiple image tags can refer to the same image, and this list may be
     * empty if no tags reference the image, in which case the image is
     * "untagged", in which case it can still be referenced by its ID.
     * 
     * Required: true
     */
    "RepoTags": string[];

    /**
     * Total size of image layers that are shared between this image and other
     * images.
     * 
     * This size is not calculated by default. `-1` indicates that the value
     * has not been set / calculated.
     * 
     * Required: true
     */
    "SharedSize": number;

    /**
     * Total size of the image including all layers it is composed of.
     * 
     * Required: true
     */
    "Size": number;

    /** Creates a new Summary instance. */
    constructor($$source: Partial<Summary> = {}) {
        if (!("Containers" in $$source)) {
            this["Containers"] = 0;
        }
        if (!("Created" in $$source)) {
            this["Created"] = 0;
        }
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Labels" in $$source)) {
            this["Labels"] = {};
        }
        if (!("ParentId" in $$source)) {
            this["ParentId"] = "";
        }
        if (!("RepoDigests" in $$source)) {
            this["RepoDigests"] = [];
        }
        if (!("RepoTags" in $$source)) {
            this["RepoTags"] = [];
        }
        if (!("SharedSize" in $$source)) {
            this["SharedSize"] = 0;
        }
        if (!("Size" in $$source)) {
            this["Size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     */
    static createFrom($$source: any = {}): Summary {
        const $$createField3_0 = $$createType16;
        const $$createField5_0 = $$createType9;
        const $$createField6_0 = $$createType11;
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Labels" in $$parsedSource) {
            $$parsedSource["Labels"] = $$createField3_0($$parsedSource["Labels"]);
        }
        if ("Descriptor" in $$parsedSource) {
            $$parsedSource["Descriptor"] = $$createField5_0($$parsedSource["Descriptor"]);
        }
        if ("Manifests" in $$parsedSource) {
            $$parsedSource["Manifests"] = $$createField6_0($$parsedSource["Manifests"]);
        }
        if ("RepoDigests" in $$parsedSource) {
            $$parsedSource["RepoDigests"] = $$createField7_0($$parsedSource["RepoDigests"]);
        }
        if ("RepoTags" in $$parsedSource) {
            $$parsedSource["RepoTags"] = $$createField8_0($$parsedSource["RepoTags"]);
        }
        return new Summary($$parsedSource as Partial<Summary>);
    }
}

// Private type creation functions
const $$createType0 = v1$0.Platform.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = v1$1.DockerOCIImageConfig.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = storage$0.DriverData.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = RootFS.createFrom;
const $$createType7 = Metadata.createFrom;
const $$createType8 = v1$0.Descriptor.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = ManifestSummary.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = ImageProperties.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = AttestationProperties.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $Create.Map($Create.Any, $Create.Any);
