// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as digest$0 from "../../../../../opencontainers/go-digest/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as v1$0 from "../../../../../opencontainers/image-spec/specs-go/v1/models.js";

export class AttestationProperties {
    /**
     * Creates a new AttestationProperties instance.
     * @param {Partial<AttestationProperties>} [$$source = {}] - The source object to create the AttestationProperties.
     */
    constructor($$source = {}) {
        if (!("For" in $$source)) {
            /**
             * For is the digest of the image manifest that this attestation is for.
             * @member
             * @type {digest$0.Digest}
             */
            this["For"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AttestationProperties instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AttestationProperties}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AttestationProperties(/** @type {Partial<AttestationProperties>} */($$parsedSource));
    }
}

export class ImageProperties {
    /**
     * Creates a new ImageProperties instance.
     * @param {Partial<ImageProperties>} [$$source = {}] - The source object to create the ImageProperties.
     */
    constructor($$source = {}) {
        if (!("Platform" in $$source)) {
            /**
             * Platform is the OCI platform object describing the platform of the image.
             * 
             * Required: true
             * @member
             * @type {v1$0.Platform}
             */
            this["Platform"] = (new v1$0.Platform());
        }
        if (!("Size" in $$source)) {
            /**
             * @member
             * @type {{"Unpacked": number}}
             */
            this["Size"] = {"Unpacked": 0};
        }
        if (!("Containers" in $$source)) {
            /**
             * Containers is an array containing the IDs of the containers that are
             * using this image.
             * 
             * Required: true
             * @member
             * @type {string[]}
             */
            this["Containers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImageProperties instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImageProperties}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Platform" in $$parsedSource) {
            $$parsedSource["Platform"] = $$createField0_0($$parsedSource["Platform"]);
        }
        if ("Containers" in $$parsedSource) {
            $$parsedSource["Containers"] = $$createField2_0($$parsedSource["Containers"]);
        }
        return new ImageProperties(/** @type {Partial<ImageProperties>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const ManifestKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ManifestKindImage: "image",
    ManifestKindAttestation: "attestation",
    ManifestKindUnknown: "unknown",
};

export class ManifestSummary {
    /**
     * Creates a new ManifestSummary instance.
     * @param {Partial<ManifestSummary>} [$$source = {}] - The source object to create the ManifestSummary.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * ID is the content-addressable ID of an image and is the same as the
             * digest of the image manifest.
             * 
             * Required: true
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("Descriptor" in $$source)) {
            /**
             * Descriptor is the OCI descriptor of the image.
             * 
             * Required: true
             * @member
             * @type {v1$0.Descriptor}
             */
            this["Descriptor"] = (new v1$0.Descriptor());
        }
        if (!("Available" in $$source)) {
            /**
             * Indicates whether all the child content (image config, layers) is
             * fully available locally
             * 
             * Required: true
             * @member
             * @type {boolean}
             */
            this["Available"] = false;
        }
        if (!("Size" in $$source)) {
            /**
             * Size is the size information of the content related to this manifest.
             * Note: These sizes only take the locally available content into account.
             * 
             * Required: true
             * @member
             * @type {{"Content": number, "Total": number}}
             */
            this["Size"] = {"Content": 0, "Total": 0};
        }
        if (!("Kind" in $$source)) {
            /**
             * Kind is the kind of the image manifest.
             * 
             * Required: true
             * @member
             * @type {ManifestKind}
             */
            this["Kind"] = ManifestKind.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * Present only if Kind == ManifestKindImage.
             * @member
             * @type {ImageProperties | null | undefined}
             */
            this["ImageData"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Present only if Kind == ManifestKindAttestation.
             * @member
             * @type {AttestationProperties | null | undefined}
             */
            this["AttestationData"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManifestSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ManifestSummary}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Descriptor" in $$parsedSource) {
            $$parsedSource["Descriptor"] = $$createField1_0($$parsedSource["Descriptor"]);
        }
        if ("ImageData" in $$parsedSource) {
            $$parsedSource["ImageData"] = $$createField5_0($$parsedSource["ImageData"]);
        }
        if ("AttestationData" in $$parsedSource) {
            $$parsedSource["AttestationData"] = $$createField6_0($$parsedSource["AttestationData"]);
        }
        return new ManifestSummary(/** @type {Partial<ManifestSummary>} */($$parsedSource));
    }
}

export class Summary {
    /**
     * Creates a new Summary instance.
     * @param {Partial<Summary>} [$$source = {}] - The source object to create the Summary.
     */
    constructor($$source = {}) {
        if (!("Containers" in $$source)) {
            /**
             * Number of containers using this image. Includes both stopped and running
             * containers.
             * 
             * This size is not calculated by default, and depends on which API endpoint
             * is used. `-1` indicates that the value has not been set / calculated.
             * 
             * Required: true
             * @member
             * @type {number}
             */
            this["Containers"] = 0;
        }
        if (!("Created" in $$source)) {
            /**
             * Date and time at which the image was created as a Unix timestamp
             * (number of seconds since EPOCH).
             * 
             * Required: true
             * @member
             * @type {number}
             */
            this["Created"] = 0;
        }
        if (!("Id" in $$source)) {
            /**
             * ID is the content-addressable ID of an image.
             * 
             * This identifier is a content-addressable digest calculated from the
             * image's configuration (which includes the digests of layers used by
             * the image).
             * 
             * Note that this digest differs from the `RepoDigests` below, which
             * holds digests of image manifests that reference the image.
             * 
             * Required: true
             * @member
             * @type {string}
             */
            this["Id"] = "";
        }
        if (!("Labels" in $$source)) {
            /**
             * User-defined key/value metadata.
             * Required: true
             * @member
             * @type {{ [_: string]: string }}
             */
            this["Labels"] = {};
        }
        if (!("ParentId" in $$source)) {
            /**
             * ID of the parent image.
             * 
             * Depending on how the image was created, this field may be empty and
             * is only set for images that were built/created locally. This field
             * is empty if the image was pulled from an image registry.
             * 
             * Required: true
             * @member
             * @type {string}
             */
            this["ParentId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Descriptor is the OCI descriptor of the image target.
             * It's only set if the daemon provides a multi-platform image store.
             * 
             * WARNING: This is experimental and may change at any time without any backward
             * compatibility.
             * @member
             * @type {v1$0.Descriptor | null | undefined}
             */
            this["Descriptor"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Manifests is a list of image manifests available in this image.  It
             * provides a more detailed view of the platform-specific image manifests or
             * other image-attached data like build attestations.
             * 
             * WARNING: This is experimental and may change at any time without any backward
             * compatibility.
             * @member
             * @type {ManifestSummary[] | undefined}
             */
            this["Manifests"] = undefined;
        }
        if (!("RepoDigests" in $$source)) {
            /**
             * List of content-addressable digests of locally available image manifests
             * that the image is referenced from. Multiple manifests can refer to the
             * same image.
             * 
             * These digests are usually only available if the image was either pulled
             * from a registry, or if the image was pushed to a registry, which is when
             * the manifest is generated and its digest calculated.
             * 
             * Required: true
             * @member
             * @type {string[]}
             */
            this["RepoDigests"] = [];
        }
        if (!("RepoTags" in $$source)) {
            /**
             * List of image names/tags in the local image cache that reference this
             * image.
             * 
             * Multiple image tags can refer to the same image, and this list may be
             * empty if no tags reference the image, in which case the image is
             * "untagged", in which case it can still be referenced by its ID.
             * 
             * Required: true
             * @member
             * @type {string[]}
             */
            this["RepoTags"] = [];
        }
        if (!("SharedSize" in $$source)) {
            /**
             * Total size of image layers that are shared between this image and other
             * images.
             * 
             * This size is not calculated by default. `-1` indicates that the value
             * has not been set / calculated.
             * 
             * Required: true
             * @member
             * @type {number}
             */
            this["SharedSize"] = 0;
        }
        if (!("Size" in $$source)) {
            /**
             * Total size of the image including all layers it is composed of.
             * 
             * Required: true
             * @member
             * @type {number}
             */
            this["Size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Summary}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType7;
        const $$createField5_0 = $$createType8;
        const $$createField6_0 = $$createType10;
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Labels" in $$parsedSource) {
            $$parsedSource["Labels"] = $$createField3_0($$parsedSource["Labels"]);
        }
        if ("Descriptor" in $$parsedSource) {
            $$parsedSource["Descriptor"] = $$createField5_0($$parsedSource["Descriptor"]);
        }
        if ("Manifests" in $$parsedSource) {
            $$parsedSource["Manifests"] = $$createField6_0($$parsedSource["Manifests"]);
        }
        if ("RepoDigests" in $$parsedSource) {
            $$parsedSource["RepoDigests"] = $$createField7_0($$parsedSource["RepoDigests"]);
        }
        if ("RepoTags" in $$parsedSource) {
            $$parsedSource["RepoTags"] = $$createField8_0($$parsedSource["RepoTags"]);
        }
        return new Summary(/** @type {Partial<Summary>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = v1$0.Platform.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = v1$0.Descriptor.createFrom;
const $$createType3 = ImageProperties.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = AttestationProperties.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
const $$createType8 = $Create.Nullable($$createType2);
const $$createType9 = ManifestSummary.createFrom;
const $$createType10 = $Create.Array($$createType9);
