// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    EndpointIPAMConfig,
    EndpointSettings
} from "./models.js";

import * as $models from "./models.js";

/**
 * A HardwareAddr represents a physical hardware address.
 * It implements [encoding.TextMarshaler] and [encoding.TextUnmarshaler]
 * in the absence of go.dev/issue/29678.
 * @typedef {$models.HardwareAddr} HardwareAddr
 */
