// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as netip$0 from "../../../../../../net/netip/models.js";

/**
 * EndpointIPAMConfig represents IPAM configurations for the endpoint
 */
export class EndpointIPAMConfig {
    /**
     * Creates a new EndpointIPAMConfig instance.
     * @param {Partial<EndpointIPAMConfig>} [$$source = {}] - The source object to create the EndpointIPAMConfig.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {netip$0.Addr | undefined}
             */
            this["IPv4Address"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {netip$0.Addr | undefined}
             */
            this["IPv6Address"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {netip$0.Addr[] | undefined}
             */
            this["LinkLocalIPs"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EndpointIPAMConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EndpointIPAMConfig}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("LinkLocalIPs" in $$parsedSource) {
            $$parsedSource["LinkLocalIPs"] = $$createField2_0($$parsedSource["LinkLocalIPs"]);
        }
        return new EndpointIPAMConfig(/** @type {Partial<EndpointIPAMConfig>} */($$parsedSource));
    }
}

/**
 * EndpointSettings stores the network endpoint details
 */
export class EndpointSettings {
    /**
     * Creates a new EndpointSettings instance.
     * @param {Partial<EndpointSettings>} [$$source = {}] - The source object to create the EndpointSettings.
     */
    constructor($$source = {}) {
        if (!("IPAMConfig" in $$source)) {
            /**
             * Configuration data
             * @member
             * @type {EndpointIPAMConfig | null}
             */
            this["IPAMConfig"] = null;
        }
        if (!("Links" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["Links"] = [];
        }
        if (!("Aliases" in $$source)) {
            /**
             * Aliases holds the list of extra, user-specified DNS names for this endpoint.
             * @member
             * @type {string[]}
             */
            this["Aliases"] = [];
        }
        if (!("DriverOpts" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: string }}
             */
            this["DriverOpts"] = {};
        }
        if (!("GwPriority" in $$source)) {
            /**
             * GwPriority determines which endpoint will provide the default gateway
             * for the container. The endpoint with the highest priority will be used.
             * If multiple endpoints have the same priority, they are lexicographically
             * sorted based on their network name, and the one that sorts first is picked.
             * @member
             * @type {number}
             */
            this["GwPriority"] = 0;
        }
        if (!("NetworkID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["NetworkID"] = "";
        }
        if (!("EndpointID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["EndpointID"] = "";
        }
        if (!("Gateway" in $$source)) {
            /**
             * @member
             * @type {netip$0.Addr}
             */
            this["Gateway"] = "";
        }
        if (!("IPAddress" in $$source)) {
            /**
             * @member
             * @type {netip$0.Addr}
             */
            this["IPAddress"] = "";
        }
        if (!("MacAddress" in $$source)) {
            /**
             * MacAddress may be used to specify a MAC address when the container is created.
             * Once the container is running, it becomes operational data (it may contain a
             * generated address).
             * @member
             * @type {HardwareAddr}
             */
            this["MacAddress"] = "";
        }
        if (!("IPPrefixLen" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["IPPrefixLen"] = 0;
        }
        if (!("IPv6Gateway" in $$source)) {
            /**
             * @member
             * @type {netip$0.Addr}
             */
            this["IPv6Gateway"] = "";
        }
        if (!("GlobalIPv6Address" in $$source)) {
            /**
             * @member
             * @type {netip$0.Addr}
             */
            this["GlobalIPv6Address"] = "";
        }
        if (!("GlobalIPv6PrefixLen" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["GlobalIPv6PrefixLen"] = 0;
        }
        if (!("DNSNames" in $$source)) {
            /**
             * DNSNames holds all the (non fully qualified) DNS names associated to this
             * endpoint. The first entry is used to generate PTR records.
             * @member
             * @type {string[]}
             */
            this["DNSNames"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EndpointSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EndpointSettings}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType4;
        const $$createField14_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("IPAMConfig" in $$parsedSource) {
            $$parsedSource["IPAMConfig"] = $$createField0_0($$parsedSource["IPAMConfig"]);
        }
        if ("Links" in $$parsedSource) {
            $$parsedSource["Links"] = $$createField1_0($$parsedSource["Links"]);
        }
        if ("Aliases" in $$parsedSource) {
            $$parsedSource["Aliases"] = $$createField2_0($$parsedSource["Aliases"]);
        }
        if ("DriverOpts" in $$parsedSource) {
            $$parsedSource["DriverOpts"] = $$createField3_0($$parsedSource["DriverOpts"]);
        }
        if ("DNSNames" in $$parsedSource) {
            $$parsedSource["DNSNames"] = $$createField14_0($$parsedSource["DNSNames"]);
        }
        return new EndpointSettings(/** @type {Partial<EndpointSettings>} */($$parsedSource));
    }
}

/**
 * A HardwareAddr represents a physical hardware address.
 * It implements [encoding.TextMarshaler] and [encoding.TextUnmarshaler]
 * in the absence of go.dev/issue/29678.
 * @typedef {string} HardwareAddr
 */

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = EndpointIPAMConfig.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
