// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as netip$0 from "../../../../../../net/netip/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

/**
 * ConfigReference The config-only network source to provide the configuration for
 * this network.
 * 
 * swagger:model ConfigReference
 */
export class ConfigReference {
    /**
     * The name of the config-only network that provides the network's
     * configuration. The specified network must be an existing config-only
     * network. Only network names are allowed, not network IDs.
     * 
     * Example: config_only_network_01
     */
    "Network": string;

    /** Creates a new ConfigReference instance. */
    constructor($$source: Partial<ConfigReference> = {}) {
        if (!("Network" in $$source)) {
            this["Network"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigReference instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigReference {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigReference($$parsedSource as Partial<ConfigReference>);
    }
}

/**
 * EndpointIPAMConfig represents IPAM configurations for the endpoint
 */
export class EndpointIPAMConfig {
    "IPv4Address"?: netip$0.Addr;
    "IPv6Address"?: netip$0.Addr;
    "LinkLocalIPs"?: netip$0.Addr[];

    /** Creates a new EndpointIPAMConfig instance. */
    constructor($$source: Partial<EndpointIPAMConfig> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EndpointIPAMConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): EndpointIPAMConfig {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("LinkLocalIPs" in $$parsedSource) {
            $$parsedSource["LinkLocalIPs"] = $$createField2_0($$parsedSource["LinkLocalIPs"]);
        }
        return new EndpointIPAMConfig($$parsedSource as Partial<EndpointIPAMConfig>);
    }
}

/**
 * EndpointSettings stores the network endpoint details
 */
export class EndpointSettings {
    /**
     * Configuration data
     */
    "IPAMConfig": EndpointIPAMConfig | null;
    "Links": string[];

    /**
     * Aliases holds the list of extra, user-specified DNS names for this endpoint.
     */
    "Aliases": string[];
    "DriverOpts": { [_: string]: string };

    /**
     * GwPriority determines which endpoint will provide the default gateway
     * for the container. The endpoint with the highest priority will be used.
     * If multiple endpoints have the same priority, they are lexicographically
     * sorted based on their network name, and the one that sorts first is picked.
     */
    "GwPriority": number;
    "NetworkID": string;
    "EndpointID": string;
    "Gateway": netip$0.Addr;
    "IPAddress": netip$0.Addr;

    /**
     * MacAddress may be used to specify a MAC address when the container is created.
     * Once the container is running, it becomes operational data (it may contain a
     * generated address).
     */
    "MacAddress": HardwareAddr;
    "IPPrefixLen": number;
    "IPv6Gateway": netip$0.Addr;
    "GlobalIPv6Address": netip$0.Addr;
    "GlobalIPv6PrefixLen": number;

    /**
     * DNSNames holds all the (non fully qualified) DNS names associated to this
     * endpoint. The first entry is used to generate PTR records.
     */
    "DNSNames": string[];

    /** Creates a new EndpointSettings instance. */
    constructor($$source: Partial<EndpointSettings> = {}) {
        if (!("IPAMConfig" in $$source)) {
            this["IPAMConfig"] = null;
        }
        if (!("Links" in $$source)) {
            this["Links"] = [];
        }
        if (!("Aliases" in $$source)) {
            this["Aliases"] = [];
        }
        if (!("DriverOpts" in $$source)) {
            this["DriverOpts"] = {};
        }
        if (!("GwPriority" in $$source)) {
            this["GwPriority"] = 0;
        }
        if (!("NetworkID" in $$source)) {
            this["NetworkID"] = "";
        }
        if (!("EndpointID" in $$source)) {
            this["EndpointID"] = "";
        }
        if (!("Gateway" in $$source)) {
            this["Gateway"] = "";
        }
        if (!("IPAddress" in $$source)) {
            this["IPAddress"] = "";
        }
        if (!("MacAddress" in $$source)) {
            this["MacAddress"] = "";
        }
        if (!("IPPrefixLen" in $$source)) {
            this["IPPrefixLen"] = 0;
        }
        if (!("IPv6Gateway" in $$source)) {
            this["IPv6Gateway"] = "";
        }
        if (!("GlobalIPv6Address" in $$source)) {
            this["GlobalIPv6Address"] = "";
        }
        if (!("GlobalIPv6PrefixLen" in $$source)) {
            this["GlobalIPv6PrefixLen"] = 0;
        }
        if (!("DNSNames" in $$source)) {
            this["DNSNames"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EndpointSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): EndpointSettings {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType4;
        const $$createField14_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("IPAMConfig" in $$parsedSource) {
            $$parsedSource["IPAMConfig"] = $$createField0_0($$parsedSource["IPAMConfig"]);
        }
        if ("Links" in $$parsedSource) {
            $$parsedSource["Links"] = $$createField1_0($$parsedSource["Links"]);
        }
        if ("Aliases" in $$parsedSource) {
            $$parsedSource["Aliases"] = $$createField2_0($$parsedSource["Aliases"]);
        }
        if ("DriverOpts" in $$parsedSource) {
            $$parsedSource["DriverOpts"] = $$createField3_0($$parsedSource["DriverOpts"]);
        }
        if ("DNSNames" in $$parsedSource) {
            $$parsedSource["DNSNames"] = $$createField14_0($$parsedSource["DNSNames"]);
        }
        return new EndpointSettings($$parsedSource as Partial<EndpointSettings>);
    }
}

/**
 * A HardwareAddr represents a physical hardware address.
 * It implements [encoding.TextMarshaler] and [encoding.TextUnmarshaler]
 * in the absence of go.dev/issue/29678.
 */
export type HardwareAddr = string;

/**
 * IPAM represents IP Address Management
 */
export class IPAM {
    "Driver": string;

    /**
     * Per network IPAM driver options
     */
    "Options": { [_: string]: string };
    "Config": IPAMConfig[];

    /** Creates a new IPAM instance. */
    constructor($$source: Partial<IPAM> = {}) {
        if (!("Driver" in $$source)) {
            this["Driver"] = "";
        }
        if (!("Options" in $$source)) {
            this["Options"] = {};
        }
        if (!("Config" in $$source)) {
            this["Config"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPAM instance from a string or object.
     */
    static createFrom($$source: any = {}): IPAM {
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Options" in $$parsedSource) {
            $$parsedSource["Options"] = $$createField1_0($$parsedSource["Options"]);
        }
        if ("Config" in $$parsedSource) {
            $$parsedSource["Config"] = $$createField2_0($$parsedSource["Config"]);
        }
        return new IPAM($$parsedSource as Partial<IPAM>);
    }
}

/**
 * IPAMConfig represents IPAM configurations
 */
export class IPAMConfig {
    "Subnet"?: netip$0.Prefix;
    "IPRange"?: netip$0.Prefix;
    "Gateway"?: netip$0.Addr;
    "AuxiliaryAddresses"?: { [_: string]: netip$0.Addr };

    /** Creates a new IPAMConfig instance. */
    constructor($$source: Partial<IPAMConfig> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPAMConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): IPAMConfig {
        const $$createField3_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("AuxiliaryAddresses" in $$parsedSource) {
            $$parsedSource["AuxiliaryAddresses"] = $$createField3_0($$parsedSource["AuxiliaryAddresses"]);
        }
        return new IPAMConfig($$parsedSource as Partial<IPAMConfig>);
    }
}

/**
 * PeerInfo represents one peer of an overlay network.
 * 
 * swagger:model PeerInfo
 */
export class PeerInfo {
    /**
     * ID of the peer-node in the Swarm cluster.
     * Example: 6869d7c1732b
     */
    "Name": string;

    /**
     * IP-address of the peer-node in the Swarm cluster.
     * Example: 10.133.77.91
     */
    "IP": netip$0.Addr;

    /** Creates a new PeerInfo instance. */
    constructor($$source: Partial<PeerInfo> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("IP" in $$source)) {
            this["IP"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PeerInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PeerInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PeerInfo($$parsedSource as Partial<PeerInfo>);
    }
}

/**
 * Port is a type representing a single port number and protocol in the format "<portnum>/[<proto>]".
 * 
 * The zero port value, i.e. Port{}, is invalid; use [ParsePort] to create a valid Port value.
 */
export type Port = string;

/**
 * PortBinding represents a binding between a Host IP address and a Host Port.
 */
export class PortBinding {
    /**
     * HostIP is the host IP Address
     */
    "HostIp": netip$0.Addr;

    /**
     * HostPort is the host port number
     */
    "HostPort": string;

    /** Creates a new PortBinding instance. */
    constructor($$source: Partial<PortBinding> = {}) {
        if (!("HostIp" in $$source)) {
            this["HostIp"] = "";
        }
        if (!("HostPort" in $$source)) {
            this["HostPort"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortBinding instance from a string or object.
     */
    static createFrom($$source: any = {}): PortBinding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortBinding($$parsedSource as Partial<PortBinding>);
    }
}

/**
 * PortMap is a collection of [PortBinding] indexed by [Port].
 */
export type PortMap = { [_: Port]: PortBinding[] };

/**
 * PortSet is a collection of structs indexed by [Port].
 */
export type PortSet = { [_: Port]: {} };

/**
 * Summary Network list response item
 * 
 * swagger:model Summary
 */
export class Summary {
    /**
     * Name of the network.
     * 
     * Example: my_network
     */
    "Name": string;

    /**
     * ID that uniquely identifies a network on a single machine.
     * 
     * Example: 7d86d31b1478e7cca9ebed7e73aa0fdeec46c5ca29497431d3007d2d9e15ed99
     */
    "Id": string;

    /**
     * Date and time at which the network was created in
     * [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.
     * 
     * Example: 2016-10-19T04:33:30.360899459Z
     */
    "Created": time$0.Time;

    /**
     * The level at which the network exists (e.g. `swarm` for cluster-wide
     * or `local` for machine level)
     * 
     * Example: local
     */
    "Scope": string;

    /**
     * The name of the driver used to create the network (e.g. `bridge`,
     * `overlay`).
     * 
     * Example: overlay
     */
    "Driver": string;

    /**
     * Whether the network was created with IPv4 enabled.
     * 
     * Example: true
     */
    "EnableIPv4": boolean;

    /**
     * Whether the network was created with IPv6 enabled.
     * 
     * Example: false
     */
    "EnableIPv6": boolean;

    /**
     * The network's IP Address Management.
     */
    "IPAM": IPAM;

    /**
     * Whether the network is created to only allow internal networking
     * connectivity.
     * 
     * Example: false
     */
    "Internal": boolean;

    /**
     * Whether a global / swarm scope network is manually attachable by regular
     * containers from workers in swarm mode.
     * 
     * Example: false
     */
    "Attachable": boolean;

    /**
     * Whether the network is providing the routing-mesh for the swarm cluster.
     * 
     * Example: false
     */
    "Ingress": boolean;

    /**
     * config from
     */
    "ConfigFrom": ConfigReference;

    /**
     * Whether the network is a config-only network. Config-only networks are
     * placeholder networks for network configurations to be used by other
     * networks. Config-only networks cannot be used directly to run containers
     * or services.
     */
    "ConfigOnly": boolean;

    /**
     * Network-specific options uses when creating the network.
     * 
     * Example: {"com.docker.network.bridge.default_bridge":"true","com.docker.network.bridge.enable_icc":"true","com.docker.network.bridge.enable_ip_masquerade":"true","com.docker.network.bridge.host_binding_ipv4":"0.0.0.0","com.docker.network.bridge.name":"docker0","com.docker.network.driver.mtu":"1500"}
     */
    "Options": { [_: string]: string };

    /**
     * Metadata specific to the network being created.
     * 
     * Example: {"com.example.some-label":"some-value","com.example.some-other-label":"some-other-value"}
     */
    "Labels": { [_: string]: string };

    /**
     * List of peer nodes for an overlay network. This field is only present
     * for overlay networks, and omitted for other network types.
     */
    "Peers"?: PeerInfo[];

    /** Creates a new Summary instance. */
    constructor($$source: Partial<Summary> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Created" in $$source)) {
            this["Created"] = null;
        }
        if (!("Scope" in $$source)) {
            this["Scope"] = "";
        }
        if (!("Driver" in $$source)) {
            this["Driver"] = "";
        }
        if (!("EnableIPv4" in $$source)) {
            this["EnableIPv4"] = false;
        }
        if (!("EnableIPv6" in $$source)) {
            this["EnableIPv6"] = false;
        }
        if (!("IPAM" in $$source)) {
            this["IPAM"] = (new IPAM());
        }
        if (!("Internal" in $$source)) {
            this["Internal"] = false;
        }
        if (!("Attachable" in $$source)) {
            this["Attachable"] = false;
        }
        if (!("Ingress" in $$source)) {
            this["Ingress"] = false;
        }
        if (!("ConfigFrom" in $$source)) {
            this["ConfigFrom"] = (new ConfigReference());
        }
        if (!("ConfigOnly" in $$source)) {
            this["ConfigOnly"] = false;
        }
        if (!("Options" in $$source)) {
            this["Options"] = {};
        }
        if (!("Labels" in $$source)) {
            this["Labels"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     */
    static createFrom($$source: any = {}): Summary {
        const $$createField7_0 = $$createType8;
        const $$createField11_0 = $$createType9;
        const $$createField13_0 = $$createType4;
        const $$createField14_0 = $$createType4;
        const $$createField15_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("IPAM" in $$parsedSource) {
            $$parsedSource["IPAM"] = $$createField7_0($$parsedSource["IPAM"]);
        }
        if ("ConfigFrom" in $$parsedSource) {
            $$parsedSource["ConfigFrom"] = $$createField11_0($$parsedSource["ConfigFrom"]);
        }
        if ("Options" in $$parsedSource) {
            $$parsedSource["Options"] = $$createField13_0($$parsedSource["Options"]);
        }
        if ("Labels" in $$parsedSource) {
            $$parsedSource["Labels"] = $$createField14_0($$parsedSource["Labels"]);
        }
        if ("Peers" in $$parsedSource) {
            $$parsedSource["Peers"] = $$createField15_0($$parsedSource["Peers"]);
        }
        return new Summary($$parsedSource as Partial<Summary>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = EndpointIPAMConfig.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = IPAMConfig.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
const $$createType8 = IPAM.createFrom;
const $$createType9 = ConfigReference.createFrom;
const $$createType10 = PeerInfo.createFrom;
const $$createType11 = $Create.Array($$createType10);
