// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as netip$0 from "../../../../../../net/netip/models.js";

/**
 * EndpointIPAMConfig represents IPAM configurations for the endpoint
 */
export class EndpointIPAMConfig {
    "IPv4Address"?: netip$0.Addr;
    "IPv6Address"?: netip$0.Addr;
    "LinkLocalIPs"?: netip$0.Addr[];

    /** Creates a new EndpointIPAMConfig instance. */
    constructor($$source: Partial<EndpointIPAMConfig> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EndpointIPAMConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): EndpointIPAMConfig {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("LinkLocalIPs" in $$parsedSource) {
            $$parsedSource["LinkLocalIPs"] = $$createField2_0($$parsedSource["LinkLocalIPs"]);
        }
        return new EndpointIPAMConfig($$parsedSource as Partial<EndpointIPAMConfig>);
    }
}

/**
 * EndpointSettings stores the network endpoint details
 */
export class EndpointSettings {
    /**
     * Configuration data
     */
    "IPAMConfig": EndpointIPAMConfig | null;
    "Links": string[];

    /**
     * Aliases holds the list of extra, user-specified DNS names for this endpoint.
     */
    "Aliases": string[];
    "DriverOpts": { [_: string]: string };

    /**
     * GwPriority determines which endpoint will provide the default gateway
     * for the container. The endpoint with the highest priority will be used.
     * If multiple endpoints have the same priority, they are lexicographically
     * sorted based on their network name, and the one that sorts first is picked.
     */
    "GwPriority": number;
    "NetworkID": string;
    "EndpointID": string;
    "Gateway": netip$0.Addr;
    "IPAddress": netip$0.Addr;

    /**
     * MacAddress may be used to specify a MAC address when the container is created.
     * Once the container is running, it becomes operational data (it may contain a
     * generated address).
     */
    "MacAddress": HardwareAddr;
    "IPPrefixLen": number;
    "IPv6Gateway": netip$0.Addr;
    "GlobalIPv6Address": netip$0.Addr;
    "GlobalIPv6PrefixLen": number;

    /**
     * DNSNames holds all the (non fully qualified) DNS names associated to this
     * endpoint. The first entry is used to generate PTR records.
     */
    "DNSNames": string[];

    /** Creates a new EndpointSettings instance. */
    constructor($$source: Partial<EndpointSettings> = {}) {
        if (!("IPAMConfig" in $$source)) {
            this["IPAMConfig"] = null;
        }
        if (!("Links" in $$source)) {
            this["Links"] = [];
        }
        if (!("Aliases" in $$source)) {
            this["Aliases"] = [];
        }
        if (!("DriverOpts" in $$source)) {
            this["DriverOpts"] = {};
        }
        if (!("GwPriority" in $$source)) {
            this["GwPriority"] = 0;
        }
        if (!("NetworkID" in $$source)) {
            this["NetworkID"] = "";
        }
        if (!("EndpointID" in $$source)) {
            this["EndpointID"] = "";
        }
        if (!("Gateway" in $$source)) {
            this["Gateway"] = "";
        }
        if (!("IPAddress" in $$source)) {
            this["IPAddress"] = "";
        }
        if (!("MacAddress" in $$source)) {
            this["MacAddress"] = "";
        }
        if (!("IPPrefixLen" in $$source)) {
            this["IPPrefixLen"] = 0;
        }
        if (!("IPv6Gateway" in $$source)) {
            this["IPv6Gateway"] = "";
        }
        if (!("GlobalIPv6Address" in $$source)) {
            this["GlobalIPv6Address"] = "";
        }
        if (!("GlobalIPv6PrefixLen" in $$source)) {
            this["GlobalIPv6PrefixLen"] = 0;
        }
        if (!("DNSNames" in $$source)) {
            this["DNSNames"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EndpointSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): EndpointSettings {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType4;
        const $$createField14_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("IPAMConfig" in $$parsedSource) {
            $$parsedSource["IPAMConfig"] = $$createField0_0($$parsedSource["IPAMConfig"]);
        }
        if ("Links" in $$parsedSource) {
            $$parsedSource["Links"] = $$createField1_0($$parsedSource["Links"]);
        }
        if ("Aliases" in $$parsedSource) {
            $$parsedSource["Aliases"] = $$createField2_0($$parsedSource["Aliases"]);
        }
        if ("DriverOpts" in $$parsedSource) {
            $$parsedSource["DriverOpts"] = $$createField3_0($$parsedSource["DriverOpts"]);
        }
        if ("DNSNames" in $$parsedSource) {
            $$parsedSource["DNSNames"] = $$createField14_0($$parsedSource["DNSNames"]);
        }
        return new EndpointSettings($$parsedSource as Partial<EndpointSettings>);
    }
}

/**
 * A HardwareAddr represents a physical hardware address.
 * It implements [encoding.TextMarshaler] and [encoding.TextUnmarshaler]
 * in the absence of go.dev/issue/29678.
 */
export type HardwareAddr = string;

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = EndpointIPAMConfig.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
