// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as volume$0 from "../api/types/volume/models.js";

/**
 * VolumesDiskUsage contains disk usage information for volumes.
 */
export class VolumesDiskUsage {
    /**
     * ActiveCount is the number of active volumes.
     */
    "ActiveCount": number;

    /**
     * TotalCount is the total number of volumes.
     */
    "TotalCount": number;

    /**
     * Reclaimable is the amount of disk space that can be reclaimed.
     */
    "Reclaimable": number;

    /**
     * TotalSize is the total disk space used by all volumes.
     */
    "TotalSize": number;

    /**
     * Items holds detailed information about each volume.
     */
    "Items": volume$0.Volume[];

    /** Creates a new VolumesDiskUsage instance. */
    constructor($$source: Partial<VolumesDiskUsage> = {}) {
        if (!("ActiveCount" in $$source)) {
            this["ActiveCount"] = 0;
        }
        if (!("TotalCount" in $$source)) {
            this["TotalCount"] = 0;
        }
        if (!("Reclaimable" in $$source)) {
            this["Reclaimable"] = 0;
        }
        if (!("TotalSize" in $$source)) {
            this["TotalSize"] = 0;
        }
        if (!("Items" in $$source)) {
            this["Items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VolumesDiskUsage instance from a string or object.
     */
    static createFrom($$source: any = {}): VolumesDiskUsage {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Items" in $$parsedSource) {
            $$parsedSource["Items"] = $$createField4_0($$parsedSource["Items"]);
        }
        return new VolumesDiskUsage($$parsedSource as Partial<VolumesDiskUsage>);
    }
}

// Private type creation functions
const $$createType0 = volume$0.Volume.createFrom;
const $$createType1 = $Create.Array($$createType0);
