// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as container$0 from "../api/types/container/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as image$0 from "../api/types/image/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as volume$0 from "../api/types/volume/models.js";

/**
 * ContainerCreateResult is the result from creating a container.
 */
export class ContainerCreateResult {
    "ID": string;
    "Warnings": string[];

    /** Creates a new ContainerCreateResult instance. */
    constructor($$source: Partial<ContainerCreateResult> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Warnings" in $$source)) {
            this["Warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContainerCreateResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ContainerCreateResult {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Warnings" in $$parsedSource) {
            $$parsedSource["Warnings"] = $$createField1_0($$parsedSource["Warnings"]);
        }
        return new ContainerCreateResult($$parsedSource as Partial<ContainerCreateResult>);
    }
}

/**
 * ContainerInspectResult holds the result from the [Client.ConfigInspect] method.
 */
export class ContainerInspectResult {
    "Container": container$0.InspectResponse;
    "Raw": json$0.RawMessage;

    /** Creates a new ContainerInspectResult instance. */
    constructor($$source: Partial<ContainerInspectResult> = {}) {
        if (!("Container" in $$source)) {
            this["Container"] = (new container$0.InspectResponse());
        }
        if (!("Raw" in $$source)) {
            this["Raw"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContainerInspectResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ContainerInspectResult {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Container" in $$parsedSource) {
            $$parsedSource["Container"] = $$createField0_0($$parsedSource["Container"]);
        }
        return new ContainerInspectResult($$parsedSource as Partial<ContainerInspectResult>);
    }
}

/**
 * ImagesDiskUsage contains disk usage information for images.
 */
export class ImagesDiskUsage {
    /**
     * ActiveCount is the number of active images.
     */
    "ActiveCount": number;

    /**
     * TotalCount is the total number of images.
     */
    "TotalCount": number;

    /**
     * Reclaimable is the amount of disk space that can be reclaimed.
     */
    "Reclaimable": number;

    /**
     * TotalSize is the total disk space used by all images.
     */
    "TotalSize": number;

    /**
     * Items holds detailed information about each image.
     */
    "Items": image$0.Summary[];

    /** Creates a new ImagesDiskUsage instance. */
    constructor($$source: Partial<ImagesDiskUsage> = {}) {
        if (!("ActiveCount" in $$source)) {
            this["ActiveCount"] = 0;
        }
        if (!("TotalCount" in $$source)) {
            this["TotalCount"] = 0;
        }
        if (!("Reclaimable" in $$source)) {
            this["Reclaimable"] = 0;
        }
        if (!("TotalSize" in $$source)) {
            this["TotalSize"] = 0;
        }
        if (!("Items" in $$source)) {
            this["Items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImagesDiskUsage instance from a string or object.
     */
    static createFrom($$source: any = {}): ImagesDiskUsage {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Items" in $$parsedSource) {
            $$parsedSource["Items"] = $$createField4_0($$parsedSource["Items"]);
        }
        return new ImagesDiskUsage($$parsedSource as Partial<ImagesDiskUsage>);
    }
}

/**
 * VolumesDiskUsage contains disk usage information for volumes.
 */
export class VolumesDiskUsage {
    /**
     * ActiveCount is the number of active volumes.
     */
    "ActiveCount": number;

    /**
     * TotalCount is the total number of volumes.
     */
    "TotalCount": number;

    /**
     * Reclaimable is the amount of disk space that can be reclaimed.
     */
    "Reclaimable": number;

    /**
     * TotalSize is the total disk space used by all volumes.
     */
    "TotalSize": number;

    /**
     * Items holds detailed information about each volume.
     */
    "Items": volume$0.Volume[];

    /** Creates a new VolumesDiskUsage instance. */
    constructor($$source: Partial<VolumesDiskUsage> = {}) {
        if (!("ActiveCount" in $$source)) {
            this["ActiveCount"] = 0;
        }
        if (!("TotalCount" in $$source)) {
            this["TotalCount"] = 0;
        }
        if (!("Reclaimable" in $$source)) {
            this["Reclaimable"] = 0;
        }
        if (!("TotalSize" in $$source)) {
            this["TotalSize"] = 0;
        }
        if (!("Items" in $$source)) {
            this["Items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VolumesDiskUsage instance from a string or object.
     */
    static createFrom($$source: any = {}): VolumesDiskUsage {
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Items" in $$parsedSource) {
            $$parsedSource["Items"] = $$createField4_0($$parsedSource["Items"]);
        }
        return new VolumesDiskUsage($$parsedSource as Partial<VolumesDiskUsage>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = container$0.InspectResponse.createFrom;
const $$createType2 = image$0.Summary.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = volume$0.Volume.createFrom;
const $$createType5 = $Create.Array($$createType4);
