// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as digest$0 from "../../../go-digest/models.js";

/**
 * Descriptor describes the disposition of targeted content.
 * This structure provides `application/vnd.oci.descriptor.v1+json` mediatype
 * when marshalled to JSON.
 */
export class Descriptor {
    /**
     * MediaType is the media type of the object this schema refers to.
     */
    "mediaType": string;

    /**
     * Digest is the digest of the targeted content.
     */
    "digest": digest$0.Digest;

    /**
     * Size specifies the size in bytes of the blob.
     */
    "size": number;

    /**
     * URLs specifies a list of URLs from which this object MAY be downloaded
     */
    "urls"?: string[];

    /**
     * Annotations contains arbitrary metadata relating to the targeted content.
     */
    "annotations"?: { [_: string]: string };

    /**
     * Data is an embedding of the targeted content. This is encoded as a base64
     * string when marshalled to JSON (automatically, by encoding/json). If
     * present, Data can be used directly to avoid fetching the targeted content.
     */
    "data"?: string;

    /**
     * Platform describes the platform which the image in the manifest runs on.
     * 
     * This should only be used when referring to a manifest.
     */
    "platform"?: Platform | null;

    /**
     * ArtifactType is the IANA media type of this artifact.
     */
    "artifactType"?: string;

    /** Creates a new Descriptor instance. */
    constructor($$source: Partial<Descriptor> = {}) {
        if (!("mediaType" in $$source)) {
            this["mediaType"] = "";
        }
        if (!("digest" in $$source)) {
            this["digest"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Descriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): Descriptor {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $Create.ByteSlice;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("urls" in $$parsedSource) {
            $$parsedSource["urls"] = $$createField3_0($$parsedSource["urls"]);
        }
        if ("annotations" in $$parsedSource) {
            $$parsedSource["annotations"] = $$createField4_0($$parsedSource["annotations"]);
        }
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField5_0($$parsedSource["data"]);
        }
        if ("platform" in $$parsedSource) {
            $$parsedSource["platform"] = $$createField6_0($$parsedSource["platform"]);
        }
        return new Descriptor($$parsedSource as Partial<Descriptor>);
    }
}

/**
 * Platform describes the platform which the image in the manifest runs on.
 */
export class Platform {
    /**
     * Architecture field specifies the CPU architecture, for example
     * `amd64` or `ppc64le`.
     */
    "architecture": string;

    /**
     * OS specifies the operating system, for example `linux` or `windows`.
     */
    "os": string;

    /**
     * OSVersion is an optional field specifying the operating system
     * version, for example on Windows `10.0.14393.1066`.
     */
    "os.version"?: string;

    /**
     * OSFeatures is an optional field specifying an array of strings,
     * each listing a required OS feature (for example on Windows `win32k`).
     */
    "os.features"?: string[];

    /**
     * Variant is an optional field specifying a variant of the CPU, for
     * example `v7` to specify ARMv7 when architecture is `arm`.
     */
    "variant"?: string;

    /** Creates a new Platform instance. */
    constructor($$source: Partial<Platform> = {}) {
        if (!("architecture" in $$source)) {
            this["architecture"] = "";
        }
        if (!("os" in $$source)) {
            this["os"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Platform instance from a string or object.
     */
    static createFrom($$source: any = {}): Platform {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("os.features" in $$parsedSource) {
            $$parsedSource["os.features"] = $$createField3_0($$parsedSource["os.features"]);
        }
        return new Platform($$parsedSource as Partial<Platform>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = Platform.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
