// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as digest$0 from "../../../go-digest/models.js";

/**
 * Descriptor describes the disposition of targeted content.
 * This structure provides `application/vnd.oci.descriptor.v1+json` mediatype
 * when marshalled to JSON.
 */
export class Descriptor {
    /**
     * Creates a new Descriptor instance.
     * @param {Partial<Descriptor>} [$$source = {}] - The source object to create the Descriptor.
     */
    constructor($$source = {}) {
        if (!("mediaType" in $$source)) {
            /**
             * MediaType is the media type of the object this schema refers to.
             * @member
             * @type {string}
             */
            this["mediaType"] = "";
        }
        if (!("digest" in $$source)) {
            /**
             * Digest is the digest of the targeted content.
             * @member
             * @type {digest$0.Digest}
             */
            this["digest"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * Size specifies the size in bytes of the blob.
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * URLs specifies a list of URLs from which this object MAY be downloaded
             * @member
             * @type {string[] | undefined}
             */
            this["urls"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Annotations contains arbitrary metadata relating to the targeted content.
             * @member
             * @type {{ [_: string]: string } | undefined}
             */
            this["annotations"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Data is an embedding of the targeted content. This is encoded as a base64
             * string when marshalled to JSON (automatically, by encoding/json). If
             * present, Data can be used directly to avoid fetching the targeted content.
             * @member
             * @type {string | undefined}
             */
            this["data"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Platform describes the platform which the image in the manifest runs on.
             * 
             * This should only be used when referring to a manifest.
             * @member
             * @type {Platform | null | undefined}
             */
            this["platform"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ArtifactType is the IANA media type of this artifact.
             * @member
             * @type {string | undefined}
             */
            this["artifactType"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Descriptor instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Descriptor}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $Create.ByteSlice;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("urls" in $$parsedSource) {
            $$parsedSource["urls"] = $$createField3_0($$parsedSource["urls"]);
        }
        if ("annotations" in $$parsedSource) {
            $$parsedSource["annotations"] = $$createField4_0($$parsedSource["annotations"]);
        }
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField5_0($$parsedSource["data"]);
        }
        if ("platform" in $$parsedSource) {
            $$parsedSource["platform"] = $$createField6_0($$parsedSource["platform"]);
        }
        return new Descriptor(/** @type {Partial<Descriptor>} */($$parsedSource));
    }
}

/**
 * Platform describes the platform which the image in the manifest runs on.
 */
export class Platform {
    /**
     * Creates a new Platform instance.
     * @param {Partial<Platform>} [$$source = {}] - The source object to create the Platform.
     */
    constructor($$source = {}) {
        if (!("architecture" in $$source)) {
            /**
             * Architecture field specifies the CPU architecture, for example
             * `amd64` or `ppc64le`.
             * @member
             * @type {string}
             */
            this["architecture"] = "";
        }
        if (!("os" in $$source)) {
            /**
             * OS specifies the operating system, for example `linux` or `windows`.
             * @member
             * @type {string}
             */
            this["os"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * OSVersion is an optional field specifying the operating system
             * version, for example on Windows `10.0.14393.1066`.
             * @member
             * @type {string | undefined}
             */
            this["os.version"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * OSFeatures is an optional field specifying an array of strings,
             * each listing a required OS feature (for example on Windows `win32k`).
             * @member
             * @type {string[] | undefined}
             */
            this["os.features"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Variant is an optional field specifying a variant of the CPU, for
             * example `v7` to specify ARMv7 when architecture is `arm`.
             * @member
             * @type {string | undefined}
             */
            this["variant"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Platform instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Platform}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("os.features" in $$parsedSource) {
            $$parsedSource["os.features"] = $$createField3_0($$parsedSource["os.features"]);
        }
        return new Platform(/** @type {Partial<Platform>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = Platform.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
