// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as container$0 from "../github.com/moby/moby/api/types/container/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as events$0 from "../github.com/moby/moby/api/types/events/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ContainerById 容器
 * @param {string} Id
 * @returns {$CancellablePromise<container$0.Summary | null>}
 */
export function ContainerById(Id) {
    return $Call.ByID(4065231144, Id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ContainerList 容器列表
 * @returns {$CancellablePromise<container$0.Summary[]>}
 */
export function ContainerList() {
    return $Call.ByID(1783859960).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ContainerLogs 容器日志
 * @param {string} containerId
 * @returns {$CancellablePromise<void>}
 */
export function ContainerLogs(containerId) {
    return $Call.ByID(2148619475, containerId);
}

/**
 * Greet returns a greeting for the given name
 * @param {string} name
 * @returns {$CancellablePromise<events$0.Message | null>}
 */
export function Greet(name) {
    return $Call.ByID(2659711170, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Image[]>}
 */
export function ImageList() {
    return $Call.ByID(3060495310).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenFolder(path) {
    return $Call.ByID(3894305329, path);
}

/**
 * @param {string[]} containerIds
 * @returns {$CancellablePromise<void>}
 */
export function StartContainer(containerIds) {
    return $Call.ByID(420389474, containerIds);
}

/**
 * @param {string[]} containerIds
 * @returns {$CancellablePromise<void>}
 */
export function StopContainer(containerIds) {
    return $Call.ByID(2591150016, containerIds);
}

/**
 * @returns {$CancellablePromise<$models.Volume[]>}
 */
export function VolumeList() {
    return $Call.ByID(162536207).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

// Private type creation functions
const $$createType0 = container$0.Summary.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = events$0.Message.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $0.Summary.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $0.Volume.createFrom;
const $$createType8 = $Create.Array($$createType7);
