// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as container$0 from "../github.com/moby/moby/api/types/container/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as events$0 from "../github.com/moby/moby/api/types/events/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as image$0 from "../github.com/moby/moby/api/types/image/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as network$0 from "../github.com/moby/moby/api/types/network/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as client$0 from "../github.com/moby/moby/client/models.js";

/**
 * ContainerById 容器
 */
export function ContainerById(Id: string): $CancellablePromise<container$0.Summary | null> {
    return $Call.ByID(4065231144, Id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ContainerList 容器列表
 */
export function ContainerList(): $CancellablePromise<container$0.Summary[]> {
    return $Call.ByID(1783859960).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ContainerLogs 容器日志
 */
export function ContainerLogs(containerId: string): $CancellablePromise<void> {
    return $Call.ByID(2148619475, containerId);
}

/**
 * Greet returns a greeting for the given name
 */
export function Greet(name: string): $CancellablePromise<events$0.Message | null> {
    return $Call.ByID(2659711170, name).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ImageFiles(id: string): $CancellablePromise<void> {
    return $Call.ByID(1653876261, id);
}

export function ImageList(): $CancellablePromise<client$0.ImagesDiskUsage | null> {
    return $Call.ByID(3060495310).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ImageOne(id: string): $CancellablePromise<image$0.InspectResponse | null> {
    return $Call.ByID(3196724138, id).then(($result: any) => {
        return $$createType8($result);
    });
}

export function NetworkList(): $CancellablePromise<network$0.Summary[]> {
    return $Call.ByID(1026609385).then(($result: any) => {
        return $$createType10($result);
    });
}

export function OpenFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(3894305329, path);
}

export function StartContainer(containerIds: string[]): $CancellablePromise<void> {
    return $Call.ByID(420389474, containerIds);
}

export function StopContainer(containerIds: string[]): $CancellablePromise<void> {
    return $Call.ByID(2591150016, containerIds);
}

export function VolumeList(): $CancellablePromise<client$0.VolumesDiskUsage | null> {
    return $Call.ByID(162536207).then(($result: any) => {
        return $$createType12($result);
    });
}

// Private type creation functions
const $$createType0 = container$0.Summary.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = events$0.Message.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = client$0.ImagesDiskUsage.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = image$0.InspectResponse.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = network$0.Summary.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = client$0.VolumesDiskUsage.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
