// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as container$0 from "../github.com/moby/moby/api/types/container/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as events$0 from "../github.com/moby/moby/api/types/events/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as image$0 from "../github.com/moby/moby/api/types/image/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as network$0 from "../github.com/moby/moby/api/types/network/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as client$0 from "../github.com/moby/moby/client/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ContainerById 容器
 */
export function ContainerById(Id: string): $CancellablePromise<container$0.Summary | null> {
    return $Call.ByID(4065231144, Id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ContainerFiles(cont: string): $CancellablePromise<$models.FileNode | null> {
    return $Call.ByID(2216763055, cont).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ContainerList 容器列表
 */
export function ContainerList(): $CancellablePromise<container$0.Summary[]> {
    return $Call.ByID(1783859960).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ContainerLogs 容器日志
 */
export function ContainerLogs(cont: string): $CancellablePromise<string[]> {
    return $Call.ByID(2148619475, cont).then(($result: any) => {
        return $$createType5($result);
    });
}

export function CreateContainer(params: $models.CreateContainerParams): $CancellablePromise<client$0.ContainerCreateResult> {
    return $Call.ByID(2559263320, params).then(($result: any) => {
        return $$createType6($result);
    });
}

export function CreateContainerDialog(actionId: string): $CancellablePromise<boolean> {
    return $Call.ByID(2521581528, actionId);
}

export function ExportType(): $CancellablePromise<events$0.Message | null> {
    return $Call.ByID(916175267).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ImageFilesDive(image: string): $CancellablePromise<($models.Layer | null)[]> {
    return $Call.ByID(545419287, image).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ImageList(): $CancellablePromise<client$0.ImagesDiskUsage | null> {
    return $Call.ByID(3060495310).then(($result: any) => {
        return $$createType13($result);
    });
}

export function ImageOne(id: string): $CancellablePromise<image$0.InspectResponse | null> {
    return $Call.ByID(3196724138, id).then(($result: any) => {
        return $$createType15($result);
    });
}

export function Mount(cont: string): $CancellablePromise<client$0.ContainerInspectResult | null> {
    return $Call.ByID(310251842, cont).then(($result: any) => {
        return $$createType17($result);
    });
}

export function NetworkList(): $CancellablePromise<network$0.Summary[]> {
    return $Call.ByID(1026609385).then(($result: any) => {
        return $$createType19($result);
    });
}

export function OpenFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(3894305329, path);
}

export function RemoveContainer(cont: string): $CancellablePromise<void> {
    return $Call.ByID(3139333464, cont);
}

export function StartContainer(containerIds: string[]): $CancellablePromise<void> {
    return $Call.ByID(420389474, containerIds);
}

export function StopContainer(containerIds: string[]): $CancellablePromise<void> {
    return $Call.ByID(2591150016, containerIds);
}

export function VolumeList(): $CancellablePromise<client$0.VolumesDiskUsage | null> {
    return $Call.ByID(162536207).then(($result: any) => {
        return $$createType21($result);
    });
}

// Private type creation functions
const $$createType0 = container$0.Summary.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.FileNode.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = client$0.ContainerCreateResult.createFrom;
const $$createType7 = events$0.Message.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $models.Layer.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = client$0.ImagesDiskUsage.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = image$0.InspectResponse.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = client$0.ContainerInspectResult.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = network$0.Summary.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = client$0.VolumesDiskUsage.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
