// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as container$0 from "../github.com/moby/moby/api/types/container/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as events$0 from "../github.com/moby/moby/api/types/events/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as image$0 from "../github.com/moby/moby/api/types/image/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as network$0 from "../github.com/moby/moby/api/types/network/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as client$0 from "../github.com/moby/moby/client/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ContainerById 容器
 */
export function ContainerById(Id: string): $CancellablePromise<container$0.Summary | null> {
    return $Call.ByID(4065231144, Id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ContainerFiles(cont: string): $CancellablePromise<$models.FileNode | null> {
    return $Call.ByID(2216763055, cont).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ContainerList 容器列表
 */
export function ContainerList(): $CancellablePromise<container$0.Summary[]> {
    return $Call.ByID(1783859960).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ContainerLogs 容器日志
 */
export function ContainerLogs(cont: string): $CancellablePromise<string[]> {
    return $Call.ByID(2148619475, cont).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Greet returns a greeting for the given name
 */
export function Greet(name: string): $CancellablePromise<events$0.Message | null> {
    return $Call.ByID(2659711170, name).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ImageFilesDive(image: string): $CancellablePromise<($models.Layer | null)[]> {
    return $Call.ByID(545419287, image).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ImageList(): $CancellablePromise<client$0.ImagesDiskUsage | null> {
    return $Call.ByID(3060495310).then(($result: any) => {
        return $$createType12($result);
    });
}

export function ImageOne(id: string): $CancellablePromise<image$0.InspectResponse | null> {
    return $Call.ByID(3196724138, id).then(($result: any) => {
        return $$createType14($result);
    });
}

export function Mount(cont: string): $CancellablePromise<client$0.ContainerInspectResult | null> {
    return $Call.ByID(310251842, cont).then(($result: any) => {
        return $$createType16($result);
    });
}

export function NetworkList(): $CancellablePromise<network$0.Summary[]> {
    return $Call.ByID(1026609385).then(($result: any) => {
        return $$createType18($result);
    });
}

export function OpenFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(3894305329, path);
}

export function StartContainer(containerIds: string[]): $CancellablePromise<void> {
    return $Call.ByID(420389474, containerIds);
}

export function StopContainer(containerIds: string[]): $CancellablePromise<void> {
    return $Call.ByID(2591150016, containerIds);
}

export function VolumeList(): $CancellablePromise<client$0.VolumesDiskUsage | null> {
    return $Call.ByID(162536207).then(($result: any) => {
        return $$createType20($result);
    });
}

// Private type creation functions
const $$createType0 = container$0.Summary.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.FileNode.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = events$0.Message.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.Layer.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = client$0.ImagesDiskUsage.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = image$0.InspectResponse.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = client$0.ContainerInspectResult.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = network$0.Summary.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = client$0.VolumesDiskUsage.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
