// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as image$0 from "../github.com/moby/moby/api/types/image/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as volume$0 from "../github.com/moby/moby/api/types/volume/models.js";

export const Image = image$0.Summary;

/**
 * @typedef {image$0.Summary} Image
 */

export const Volume = volume$0.Volume;

/**
 * @typedef {volume$0.Volume} Volume
 */
