// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as filetree$0 from "../github.com/wagoodman/dive/dive/filetree/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as fs$0 from "../io/fs/models.js";

/**
 * FileNode filetree.FileNode 有循环嵌套结构，不利于传输。
 */
export class FileNode {
    "n": string;
    "p": string;
    "s": number;
    "t": number;
    "l": string;
    "m": fs$0.FileMode;
    "mod": number;
    "dir": boolean;
    "diff": filetree$0.DiffType;
    "child": (FileNode | null)[];

    /** Creates a new FileNode instance. */
    constructor($$source: Partial<FileNode> = {}) {
        if (!("n" in $$source)) {
            this["n"] = "";
        }
        if (!("p" in $$source)) {
            this["p"] = "";
        }
        if (!("s" in $$source)) {
            this["s"] = 0;
        }
        if (!("t" in $$source)) {
            this["t"] = 0;
        }
        if (!("l" in $$source)) {
            this["l"] = "";
        }
        if (!("m" in $$source)) {
            this["m"] = fs$0.FileMode.$zero;
        }
        if (!("mod" in $$source)) {
            this["mod"] = 0;
        }
        if (!("dir" in $$source)) {
            this["dir"] = false;
        }
        if (!("diff" in $$source)) {
            this["diff"] = filetree$0.DiffType.$zero;
        }
        if (!("child" in $$source)) {
            this["child"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileNode instance from a string or object.
     */
    static createFrom($$source: any = {}): FileNode {
        const $$createField9_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("child" in $$parsedSource) {
            $$parsedSource["child"] = $$createField9_0($$parsedSource["child"]);
        }
        return new FileNode($$parsedSource as Partial<FileNode>);
    }
}

export class Layer {
    "Id": string;
    "Index": number;
    "Command": string;
    "Size": number;
    "Tree": FileNode | null;
    "Names": string[];
    "Digest": string;

    /** Creates a new Layer instance. */
    constructor($$source: Partial<Layer> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Index" in $$source)) {
            this["Index"] = 0;
        }
        if (!("Command" in $$source)) {
            this["Command"] = "";
        }
        if (!("Size" in $$source)) {
            this["Size"] = 0;
        }
        if (!("Tree" in $$source)) {
            this["Tree"] = null;
        }
        if (!("Names" in $$source)) {
            this["Names"] = [];
        }
        if (!("Digest" in $$source)) {
            this["Digest"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Layer instance from a string or object.
     */
    static createFrom($$source: any = {}): Layer {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Tree" in $$parsedSource) {
            $$parsedSource["Tree"] = $$createField4_0($$parsedSource["Tree"]);
        }
        if ("Names" in $$parsedSource) {
            $$parsedSource["Names"] = $$createField5_0($$parsedSource["Names"]);
        }
        return new Layer($$parsedSource as Partial<Layer>);
    }
}

// Private type creation functions
const $$createType0 = FileNode.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
