// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Clear(): $CancellablePromise<void> {
    return $Call.ByID(287594379);
}

export function Resize(cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(2328948358, cols, rows);
}

export function Serve(): $CancellablePromise<string> {
    return $Call.ByID(2113105701);
}
