// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ThrottleDevice is a structure that holds device:rate_per_second pair
 */
export class ThrottleDevice {
    "Path": string;
    "Rate": number;

    /** Creates a new ThrottleDevice instance. */
    constructor($$source: Partial<ThrottleDevice> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Rate" in $$source)) {
            this["Rate"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThrottleDevice instance from a string or object.
     */
    static createFrom($$source: any = {}): ThrottleDevice {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThrottleDevice($$parsedSource as Partial<ThrottleDevice>);
    }
}

/**
 * WeightDevice is a structure that holds device:weight pair
 */
export class WeightDevice {
    "Path": string;
    "Weight": number;

    /** Creates a new WeightDevice instance. */
    constructor($$source: Partial<WeightDevice> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Weight" in $$source)) {
            this["Weight"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WeightDevice instance from a string or object.
     */
    static createFrom($$source: any = {}): WeightDevice {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WeightDevice($$parsedSource as Partial<WeightDevice>);
    }
}
