// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Action is used for event-actions.
 */
export enum Action {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ActionCreate = "create",
    ActionStart = "start",
    ActionRestart = "restart",
    ActionStop = "stop",
    ActionCheckpoint = "checkpoint",
    ActionPause = "pause",
    ActionUnPause = "unpause",
    ActionAttach = "attach",
    ActionDetach = "detach",
    ActionResize = "resize",
    ActionUpdate = "update",
    ActionRename = "rename",
    ActionKill = "kill",
    ActionDie = "die",
    ActionOOM = "oom",
    ActionDestroy = "destroy",
    ActionRemove = "remove",
    ActionCommit = "commit",
    ActionTop = "top",
    ActionCopy = "copy",
    ActionArchivePath = "archive-path",
    ActionExtractToDir = "extract-to-dir",
    ActionExport = "export",
    ActionImport = "import",
    ActionSave = "save",
    ActionLoad = "load",
    ActionTag = "tag",
    ActionUnTag = "untag",
    ActionPush = "push",
    ActionPull = "pull",
    ActionPrune = "prune",
    ActionDelete = "delete",
    ActionEnable = "enable",
    ActionDisable = "disable",
    ActionConnect = "connect",
    ActionDisconnect = "disconnect",
    ActionReload = "reload",
    ActionMount = "mount",
    ActionUnmount = "unmount",

    /**
     * ActionExecCreate is the prefix used for exec_create events. These
     * event-actions are commonly followed by a colon and space (": "),
     * and the command that's defined for the exec, for example:
     * 
     * 	exec_create: /bin/sh -c 'echo hello'
     * 
     * This is far from ideal; it's a compromise to allow filtering and
     * to preserve backward-compatibility.
     */
    ActionExecCreate = "exec_create",

    /**
     * ActionExecStart is the prefix used for exec_create events. These
     * event-actions are commonly followed by a colon and space (": "),
     * and the command that's defined for the exec, for example:
     * 
     * 	exec_start: /bin/sh -c 'echo hello'
     * 
     * This is far from ideal; it's a compromise to allow filtering and
     * to preserve backward-compatibility.
     */
    ActionExecStart = "exec_start",
    ActionExecDie = "exec_die",
    ActionExecDetach = "exec_detach",

    /**
     * ActionHealthStatus is the prefix to use for health_status events.
     * 
     * Health-status events can either have a pre-defined status, in which
     * case the "health_status" action is followed by a colon, or can be
     * "free-form", in which case they're followed by the output of the
     * health-check output.
     * 
     * This is far form ideal, and a compromise to allow filtering, and
     * to preserve backward-compatibility.
     */
    ActionHealthStatus = "health_status",
    ActionHealthStatusRunning = "health_status: running",
    ActionHealthStatusHealthy = "health_status: healthy",
    ActionHealthStatusUnhealthy = "health_status: unhealthy",
};

/**
 * Actor describes something that generates events,
 * like a container, or a network, or a volume.
 * It has a defined name and a set of attributes.
 * The container attributes are its labels, other actors
 * can generate these attributes from other properties.
 */
export class Actor {
    "ID": string;
    "Attributes": { [_: string]: string };

    /** Creates a new Actor instance. */
    constructor($$source: Partial<Actor> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Attributes" in $$source)) {
            this["Attributes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Actor instance from a string or object.
     */
    static createFrom($$source: any = {}): Actor {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Attributes" in $$parsedSource) {
            $$parsedSource["Attributes"] = $$createField1_0($$parsedSource["Attributes"]);
        }
        return new Actor($$parsedSource as Partial<Actor>);
    }
}

/**
 * Message represents the information an event contains
 */
export class Message {
    "Type": Type;
    "Action": Action;
    "Actor": Actor;

    /**
     * Engine events are local scope. Cluster events are swarm scope.
     */
    "scope"?: string;
    "time"?: number;
    "timeNano"?: number;

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("Type" in $$source)) {
            this["Type"] = Type.$zero;
        }
        if (!("Action" in $$source)) {
            this["Action"] = Action.$zero;
        }
        if (!("Actor" in $$source)) {
            this["Actor"] = (new Actor());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Actor" in $$parsedSource) {
            $$parsedSource["Actor"] = $$createField2_0($$parsedSource["Actor"]);
        }
        return new Message($$parsedSource as Partial<Message>);
    }
}

/**
 * Type is used for event-types.
 */
export enum Type {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * List of known event types.
     *
     * BuilderEventType is the event type that the builder generates.
     */
    BuilderEventType = "builder",

    /**
     * ConfigEventType is the event type that configs generate.
     */
    ConfigEventType = "config",

    /**
     * ContainerEventType is the event type that containers generate.
     */
    ContainerEventType = "container",

    /**
     * DaemonEventType is the event type that daemon generate.
     */
    DaemonEventType = "daemon",

    /**
     * ImageEventType is the event type that images generate.
     */
    ImageEventType = "image",

    /**
     * NetworkEventType is the event type that networks generate.
     */
    NetworkEventType = "network",

    /**
     * NodeEventType is the event type that nodes generate.
     */
    NodeEventType = "node",

    /**
     * PluginEventType is the event type that plugins generate.
     */
    PluginEventType = "plugin",

    /**
     * SecretEventType is the event type that secrets generate.
     */
    SecretEventType = "secret",

    /**
     * ServiceEventType is the event type that services generate.
     */
    ServiceEventType = "service",

    /**
     * VolumeEventType is the event type that volumes generate.
     */
    VolumeEventType = "volume",
};

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = Actor.createFrom;
