// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Action is used for event-actions.
 * @readonly
 * @enum {string}
 */
export const Action = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ActionCreate: "create",
    ActionStart: "start",
    ActionRestart: "restart",
    ActionStop: "stop",
    ActionCheckpoint: "checkpoint",
    ActionPause: "pause",
    ActionUnPause: "unpause",
    ActionAttach: "attach",
    ActionDetach: "detach",
    ActionResize: "resize",
    ActionUpdate: "update",
    ActionRename: "rename",
    ActionKill: "kill",
    ActionDie: "die",
    ActionOOM: "oom",
    ActionDestroy: "destroy",
    ActionRemove: "remove",
    ActionCommit: "commit",
    ActionTop: "top",
    ActionCopy: "copy",
    ActionArchivePath: "archive-path",
    ActionExtractToDir: "extract-to-dir",
    ActionExport: "export",
    ActionImport: "import",
    ActionSave: "save",
    ActionLoad: "load",
    ActionTag: "tag",
    ActionUnTag: "untag",
    ActionPush: "push",
    ActionPull: "pull",
    ActionPrune: "prune",
    ActionDelete: "delete",
    ActionEnable: "enable",
    ActionDisable: "disable",
    ActionConnect: "connect",
    ActionDisconnect: "disconnect",
    ActionReload: "reload",
    ActionMount: "mount",
    ActionUnmount: "unmount",

    /**
     * ActionExecCreate is the prefix used for exec_create events. These
     * event-actions are commonly followed by a colon and space (": "),
     * and the command that's defined for the exec, for example:
     * 
     * 	exec_create: /bin/sh -c 'echo hello'
     * 
     * This is far from ideal; it's a compromise to allow filtering and
     * to preserve backward-compatibility.
     */
    ActionExecCreate: "exec_create",

    /**
     * ActionExecStart is the prefix used for exec_create events. These
     * event-actions are commonly followed by a colon and space (": "),
     * and the command that's defined for the exec, for example:
     * 
     * 	exec_start: /bin/sh -c 'echo hello'
     * 
     * This is far from ideal; it's a compromise to allow filtering and
     * to preserve backward-compatibility.
     */
    ActionExecStart: "exec_start",
    ActionExecDie: "exec_die",
    ActionExecDetach: "exec_detach",

    /**
     * ActionHealthStatus is the prefix to use for health_status events.
     * 
     * Health-status events can either have a pre-defined status, in which
     * case the "health_status" action is followed by a colon, or can be
     * "free-form", in which case they're followed by the output of the
     * health-check output.
     * 
     * This is far form ideal, and a compromise to allow filtering, and
     * to preserve backward-compatibility.
     */
    ActionHealthStatus: "health_status",
    ActionHealthStatusRunning: "health_status: running",
    ActionHealthStatusHealthy: "health_status: healthy",
    ActionHealthStatusUnhealthy: "health_status: unhealthy",
};

/**
 * Actor describes something that generates events,
 * like a container, or a network, or a volume.
 * It has a defined name and a set of attributes.
 * The container attributes are its labels, other actors
 * can generate these attributes from other properties.
 */
export class Actor {
    /**
     * Creates a new Actor instance.
     * @param {Partial<Actor>} [$$source = {}] - The source object to create the Actor.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("Attributes" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: string }}
             */
            this["Attributes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Actor instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Actor}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Attributes" in $$parsedSource) {
            $$parsedSource["Attributes"] = $$createField1_0($$parsedSource["Attributes"]);
        }
        return new Actor(/** @type {Partial<Actor>} */($$parsedSource));
    }
}

/**
 * Message represents the information an event contains
 */
export class Message {
    /**
     * Creates a new Message instance.
     * @param {Partial<Message>} [$$source = {}] - The source object to create the Message.
     */
    constructor($$source = {}) {
        if (!("Type" in $$source)) {
            /**
             * @member
             * @type {Type}
             */
            this["Type"] = Type.$zero;
        }
        if (!("Action" in $$source)) {
            /**
             * @member
             * @type {Action}
             */
            this["Action"] = Action.$zero;
        }
        if (!("Actor" in $$source)) {
            /**
             * @member
             * @type {Actor}
             */
            this["Actor"] = (new Actor());
        }
        if (/** @type {any} */(false)) {
            /**
             * Engine events are local scope. Cluster events are swarm scope.
             * @member
             * @type {string | undefined}
             */
            this["scope"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["time"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["timeNano"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Message}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Actor" in $$parsedSource) {
            $$parsedSource["Actor"] = $$createField2_0($$parsedSource["Actor"]);
        }
        return new Message(/** @type {Partial<Message>} */($$parsedSource));
    }
}

/**
 * Type is used for event-types.
 * @readonly
 * @enum {string}
 */
export const Type = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * List of known event types.
     *
     * BuilderEventType is the event type that the builder generates.
     */
    BuilderEventType: "builder",

    /**
     * ConfigEventType is the event type that configs generate.
     */
    ConfigEventType: "config",

    /**
     * ContainerEventType is the event type that containers generate.
     */
    ContainerEventType: "container",

    /**
     * DaemonEventType is the event type that daemon generate.
     */
    DaemonEventType: "daemon",

    /**
     * ImageEventType is the event type that images generate.
     */
    ImageEventType: "image",

    /**
     * NetworkEventType is the event type that networks generate.
     */
    NetworkEventType: "network",

    /**
     * NodeEventType is the event type that nodes generate.
     */
    NodeEventType: "node",

    /**
     * PluginEventType is the event type that plugins generate.
     */
    PluginEventType: "plugin",

    /**
     * SecretEventType is the event type that secrets generate.
     */
    SecretEventType: "secret",

    /**
     * ServiceEventType is the event type that services generate.
     */
    ServiceEventType: "service",

    /**
     * VolumeEventType is the event type that volumes generate.
     */
    VolumeEventType: "volume",
};

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = Actor.createFrom;
