// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * DockerOCIImageConfig is a ocispec.ImageConfig extended with Docker specific fields.
 */
export class DockerOCIImageConfig {
    /**
     * User defines the username or UID which the process in the container should run as.
     */
    "User"?: string;

    /**
     * ExposedPorts a set of ports to expose from a container running this image.
     */
    "ExposedPorts"?: { [_: string]: {} };

    /**
     * Env is a list of environment variables to be used in a container.
     */
    "Env"?: string[];

    /**
     * Entrypoint defines a list of arguments to use as the command to execute when the container starts.
     */
    "Entrypoint"?: string[];

    /**
     * Cmd defines the default arguments to the entrypoint of the container.
     */
    "Cmd"?: string[];

    /**
     * Volumes is a set of directories describing where the process is likely write data specific to a container instance.
     */
    "Volumes"?: { [_: string]: {} };

    /**
     * WorkingDir sets the current working directory of the entrypoint process in the container.
     */
    "WorkingDir"?: string;

    /**
     * Labels contains arbitrary metadata for the container.
     */
    "Labels"?: { [_: string]: string };

    /**
     * StopSignal contains the system call signal that will be sent to the container to exit.
     */
    "StopSignal"?: string;

    /**
     * ArgsEscaped
     * 
     * Deprecated: This field is present only for legacy compatibility with
     * Docker and should not be used by new image builders.  It is used by Docker
     * for Windows images to indicate that the `Entrypoint` or `Cmd` or both,
     * contains only a single element array, that is a pre-escaped, and combined
     * into a single string `CommandLine`. If `true` the value in `Entrypoint` or
     * `Cmd` should be used as-is to avoid double escaping.
     * https://github.com/opencontainers/image-spec/pull/892
     */
    "ArgsEscaped"?: boolean;

    /**
     * Healthcheck describes how to check the container is healthy
     */
    "Healthcheck"?: HealthcheckConfig | null;

    /**
     * ONBUILD metadata that were defined on the image Dockerfile
     */
    "OnBuild"?: string[];

    /**
     * Shell for shell-form of RUN, CMD, ENTRYPOINT
     */
    "Shell"?: string[];

    /** Creates a new DockerOCIImageConfig instance. */
    constructor($$source: Partial<DockerOCIImageConfig> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DockerOCIImageConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): DockerOCIImageConfig {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType0;
        const $$createField7_0 = $$createType2;
        const $$createField10_0 = $$createType4;
        const $$createField11_0 = $$createType1;
        const $$createField12_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ExposedPorts" in $$parsedSource) {
            $$parsedSource["ExposedPorts"] = $$createField1_0($$parsedSource["ExposedPorts"]);
        }
        if ("Env" in $$parsedSource) {
            $$parsedSource["Env"] = $$createField2_0($$parsedSource["Env"]);
        }
        if ("Entrypoint" in $$parsedSource) {
            $$parsedSource["Entrypoint"] = $$createField3_0($$parsedSource["Entrypoint"]);
        }
        if ("Cmd" in $$parsedSource) {
            $$parsedSource["Cmd"] = $$createField4_0($$parsedSource["Cmd"]);
        }
        if ("Volumes" in $$parsedSource) {
            $$parsedSource["Volumes"] = $$createField5_0($$parsedSource["Volumes"]);
        }
        if ("Labels" in $$parsedSource) {
            $$parsedSource["Labels"] = $$createField7_0($$parsedSource["Labels"]);
        }
        if ("Healthcheck" in $$parsedSource) {
            $$parsedSource["Healthcheck"] = $$createField10_0($$parsedSource["Healthcheck"]);
        }
        if ("OnBuild" in $$parsedSource) {
            $$parsedSource["OnBuild"] = $$createField11_0($$parsedSource["OnBuild"]);
        }
        if ("Shell" in $$parsedSource) {
            $$parsedSource["Shell"] = $$createField12_0($$parsedSource["Shell"]);
        }
        return new DockerOCIImageConfig($$parsedSource as Partial<DockerOCIImageConfig>);
    }
}

/**
 * HealthcheckConfig holds configuration settings for the HEALTHCHECK feature.
 */
export class HealthcheckConfig {
    /**
     * Test is the test to perform to check that the container is healthy.
     * An empty slice means to inherit the default.
     * The options are:
     * {} : inherit healthcheck
     * {"NONE"} : disable healthcheck
     * {"CMD", args...} : exec arguments directly
     * {"CMD-SHELL", command} : run command with system's default shell
     */
    "Test"?: string[];

    /**
     * Zero means to inherit. Durations are expressed as integer nanoseconds.
     * Interval is the time to wait between checks.
     */
    "Interval"?: time$0.Duration;

    /**
     * Timeout is the time to wait before considering the check to have hung.
     */
    "Timeout"?: time$0.Duration;

    /**
     * The start period for the container to initialize before the retries starts to count down.
     */
    "StartPeriod"?: time$0.Duration;

    /**
     * The interval to attempt healthchecks at during the start period
     */
    "StartInterval"?: time$0.Duration;

    /**
     * Retries is the number of consecutive failures needed to consider a container as unhealthy.
     * Zero means inherit.
     */
    "Retries"?: number;

    /** Creates a new HealthcheckConfig instance. */
    constructor($$source: Partial<HealthcheckConfig> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HealthcheckConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): HealthcheckConfig {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Test" in $$parsedSource) {
            $$parsedSource["Test"] = $$createField0_0($$parsedSource["Test"]);
        }
        return new HealthcheckConfig($$parsedSource as Partial<HealthcheckConfig>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = HealthcheckConfig.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
