// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Digest allows simple protection of hex formatted digest strings, prefixed
 * by their algorithm. Strings of type Digest have some guarantee of being in
 * the correct format and it provides quick access to the components of a
 * digest string.
 * 
 * The following is an example of the contents of Digest types:
 * 
 * 	sha256:7173b809ca12ec5dee4506cd86be934c4596dd234ee82c0662eac04a8c2c71dc
 * 
 * This allows to abstract the digest behind this type and work only in those
 * terms.
 */
export type Digest = string;
