// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {container} from '../models';
import {events} from '../models';
import {image} from '../models';
import {volume} from '../models';

export function ContainerById(arg1:string):Promise<container.Summary>;

export function ContainerList():Promise<Array<container.Summary>>;

export function ContainerLogs(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<events.Message>;

export function ImageList():Promise<Array<image.Summary>>;

export function OpenFolder(arg1:string):Promise<void>;

export function StartContainer(arg1:Array<string>):Promise<void>;

export function StopContainer(arg1:Array<string>):Promise<void>;

export function VolumeList():Promise<Array<volume.Volume>>;
