// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ContainerList() {
  return window['go']['main']['App']['ContainerList']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImageList() {
  return window['go']['main']['App']['ImageList']();
}

export function VolumeList() {
  return window['go']['main']['App']['VolumeList']();
}
