// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {container} from '../models';
import {image} from '../models';
import {volume} from '../models';

export function ContainerList():Promise<Array<container.Summary>>;

export function Greet(arg1:string):Promise<string>;

export function ImageList():Promise<Array<image.Summary>>;

export function VolumeList():Promise<Array<volume.Volume>>;
