// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ContainerById(arg1) {
  return window['go']['main']['App']['ContainerById'](arg1);
}

export function ContainerList() {
  return window['go']['main']['App']['ContainerList']();
}

export function ContainerLogs(arg1) {
  return window['go']['main']['App']['ContainerLogs'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImageList() {
  return window['go']['main']['App']['ImageList']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function StartContainer(arg1) {
  return window['go']['main']['App']['StartContainer'](arg1);
}

export function StopContainer(arg1) {
  return window['go']['main']['App']['StopContainer'](arg1);
}

export function VolumeList() {
  return window['go']['main']['App']['VolumeList']();
}
