// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListContainers() {
  return window['go']['main']['DockerApp']['ListContainers']();
}

export function ListImages() {
  return window['go']['main']['DockerApp']['ListImages']();
}

export function ListVolumes() {
  return window['go']['main']['DockerApp']['ListVolumes']();
}
