// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {container} from '../models';
import {image} from '../models';
import {volume} from '../models';

export function ListContainers():Promise<Array<container.Summary>>;

export function ListImages():Promise<Array<image.Summary>>;

export function ListVolumes():Promise<Array<volume.Volume>>;
